### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by bennyn** [tessel/t2-cli#1000]
I tried to write a small application for my Tessel 2 but got stuck very soon because I ran into this issue:

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

Are there tricks to squeeze out more memory?

**Screenshot**

![unbenannt](https://cloud.githubusercontent.com/assets/469989/18893001/42cda562-850c-11e6-8c23-bedabeead739.PNG)

**Comment by tcr** [comment]
Hi @bennyn,

Could you list what dependencies you're including in your application? You can also show the code that reproduces this error case if that's okay.

**Comment by rwaldron** [comment]
> Could you list what dependencies 

Was thinking the same, but this could be **very hard** to track down a memory leak :|
