### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by StudentESE** [tessel/t2-cli#1009]
`t2 list`
> ERR! WARNING: No usb controller found on this system.
Segmentation fault: 11

- Mac OS X El Captain 10.11.5 (15F34)
- Node 5.10.1
- NVM 0.31.0
- t2-cli@0.0.29

This seams to be a `t2-cli` problem because t2-cli@0.0.19 does not through `Segmentation fault: 11`

---

**EDIT**: Seams to be a problem also with t2-cli@0.0.28 but t2-cli@0.0.27 works with Mac OS X El Captain

**Comment by tcr** [comment]
We've resolved this by yanking a bad `node-usb` version. You should be able to use `t2-cli@0.0.28` again. (We won't need to publish a new CLI build.)

Thanks for filing this @StudentESE.
