### ISSUE TITLE
Why does `t2 run` override my lanPrefer preference?

### ISSUE THREAD

**Issue by tcr** [tessel/t2-cli#1021]
`t2 run` is always slow for me, even with the `--usb` flag. I realized it's because of this line in `tessel-2.js`: https://github.com/tessel/t2-cli/blob/master/bin/tessel-2.js#L204 It appears to override my command line preferences.

**Comment by HipsterBrown** [comment]
I'm not sure why that's there. Seems like it's been there for a while. Does anything fail when that's taken out?

**Comment by tcr** [comment]
@HipsterBrown Nothing fails on my machine. --lanPrefer, --lan flags work to set the preference as usual.

Maybe this was the fallout of when `t2 run` needed SSH for speed? November 2015 was when it was introduced: https://github.com/tessel/t2-cli/commit/ead744cfd4d2c1051c3d600b1aaf1cb2825711db

**Comment by rwaldron** [comment]
> Maybe this was the fallout of when t2 run needed SSH for speed? November 2015 was when it was introduced

Yes, the only thing I can think of is that this predates the USB optimizations, so back then we would've wanted to make the operation as painless as possible. I believe it can be safely removed.
