### ISSUE TITLE
latest t2-cli results in ERR! WARNING: No usb controller found on this system.

### ISSUE THREAD

**Issue by sbromberger** [tessel/t2-cli#1071]
Environment: OSX 10.12.1, node.js 7.0.0

To reproduce: clone the repo, then execute `npm link --local`

Results:

```

> t2-cli@0.1.1 postinstall /Users/me/dev/tessel/t2-cli
> t2 install drivers --loglevel=error || true; t2 install homedir --loglevel=error || true;

ERR! WARNING: No usb controller found on this system.
```

To recover, `kill -9` the process.

**Comment by HipsterBrown** [comment]
@sbromberger We currently support the [Node.js LTS version](https://nodejs.org/en/download/), which currently 4.x.x and the 6.x.x, for `t2-cli`. I'm not sure `node-usb` has support for the latest version of Node yet. When switching versions, be sure to reinstall and rebuild `t2-cli` due to the native bindings required for `node-usb`.

**Comment by sbromberger** [comment]
Thanks - I figured it'd be a 7.0.0 thing - but the maddening thing is that even though I'm trying to access it via the LAN interface, it's still hanging on USB. Is there a way to say "ignore USB, use LAN"?

**Comment by Frijol** [comment]
@sbromberger yes, `--lan` specifies LAN usage. But I'm not sure if it will keep you from hitting the error message anyway.

@HipsterBrown I think the "unsupported USB" message is the most common question we get. Do you know if it's possible to build a more helpful error message for this eventuality into our CLI? Have we investigated this?

**Comment by sbromberger** [comment]
@Frijol one hits the error message anyway, which causes a spike to 100% CPU (and fans), and a nonresponsive terminal - the only way to stop the runaway node process is to `kill -9` it.

**Comment by HipsterBrown** [comment]
@Frijol Yea the message comes from [`lib/usb-connection.js`](https://github.com/tessel/t2-cli/blob/2b08c0a5671308ba9559f1003f95056065100ea7/lib/usb-connection.js#L32). Any ideas on a better error message?

**Comment by rwaldron** [comment]
I have an idea of how we might get around this and allow `--lan` commands to be truly free of USB. I will post back when I've learned more.

**Comment by rwaldron** [comment]
```
rwaldron in ~/clonez/t2-cli on 1071*
$ t2 list
INFO Searching for nearby Tessels...
ERR! WARNING: No usb controller found on this system.
ERR! TypeError: Cannot read property 'on' of undefined
rwaldron in ~/clonez/t2-cli on 1071*
$ t2 list --lan
INFO Searching for nearby Tessels...
 	LAN	dolores
```

 
Just need to figure out that second error

**Comment by rwaldron** [comment]
```
rwaldron in ~/clonez/t2-cli on 1071*
$ t2 list
INFO Searching for nearby Tessels...
ERR! WARNING: No usb controller found on this system.
 	LAN	dolores
rwaldron in ~/clonez/t2-cli on 1071*
$ t2 list --lan
INFO Searching for nearby Tessels...
 	LAN	dolores
```

**Comment by rwaldron** [comment]
@sbromberger can you try a dev version with node 7?

```
npm install tessel/t2-cli#1071
```

**Comment by Frijol** [comment]
@hipsterbrown a better error message could be "An error was encountered. Please ensure you are using the correct (LTS) version of Node. If the problem persists, please file an issue at github.com/tessel/t2-cli/issues"
