### ISSUE TITLE
Pre-compiled module is missing: speaker@0.3.0

### ISSUE THREAD

**Issue by rafaelcmrj** [tessel/t2-cli#1079]
WARN Pre-compiled module is missing: speaker@0.3.0.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
WARN 
WARN This warning might be caused by one of the following:
WARN 
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.

**Comment by rwaldron** [comment]
Looks like mpg123 for mipsel wasn't included in the build config: https://github.com/TooTallNate/node-speaker/blob/master/deps/mpg123/mpg123.gyp#L48-L65
