### ISSUE TITLE
WARN Pre-compiled module is missing: serialport@4.0.6.

### ISSUE THREAD

**Issue by chanceeakin** [tessel/t2-cli#1089]
Hey, here's more of the squawk:

INFO Looking for your Tessel...
INFO Connected to megatron.
INFO Building project.
WARN Pre-compiled module is missing: serialport@4.0.6.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
WARN
WARN This warning might be caused by one of the following:
WARN
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.
ERR! { Error: ENOENT: no such file or directory, stat '/Users/chance/.tessel/binaries/serialport-4.0.6-Release-node-v46-linux-mipsel/Release/serialport.node'
ERR!     at Error (native)
ERR!     at Object.fs.statSync (fs.js:987:18)
ERR!     at Object.statSync (/Users/chance/.nvm/versions/node/v6.4.0/lib/node_modules/t2-cli/node_modules/graceful-fs/polyfills.js:289:22)
ERR!     at Object.copySync (/Users/chance/.nvm/versions/node/v6.4.0/lib/node_modules/t2-cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:20:58)
ERR!     at binaryModulesUsed.forEach.error (/Users/chance/.nvm/versions/node/v6.4.0/lib/node_modules/t2-cli/lib/tessel/deployment/javascript.js:374:16)
ERR!     at Map.forEach (native)
ERR!     at Promise (/Users/chance/.nvm/versions/node/v6.4.0/lib/node_modules/t2-cli/lib/tessel/deployment/javascript.js:348:23)
ERR!     at Object.exportables.injectBinaryModules (/Users/chance/.nvm/versions/node/v6.4.0/lib/node_modules/t2-cli/lib/tessel/deployment/javascript.js:340:10)
ERR!     at project.collect (/Users/chance/.nvm/versions/node/v6.4.0/lib/node_modules/t2-cli/lib/tessel/deployment/javascript.js:578:23)
ERR!     at Promise.all.then (/Users/chance/.nvm/versions/node/v6.4.0/lib/node_modules/t2-cli/node_modules/t2-project/lib/index.js:217:7)
ERR!   errno: -2,
ERR!   code: 'ENOENT',
ERR!   syscall: 'stat',
ERR!   path: '/Users/chance/.tessel/binaries/serialport-4.0.6-Release-node-v46-linux-mipsel/Release/serialport.node' }
INFO Writing project to RAM on megatron (4.096 kB)...
INFO Deployed.
INFO Running index.js...
I'm blinking! (Press CTRL + C to stop)

Checked the folder in the path; no binary was ever compiled. Please advise.

**Comment by chanceeakin** [comment]
Fixed the hard error by deleting the directory in `.tessel`, but still throwing the warnings. Programs build successfully. Leaving open to address warning.

**Comment by rwaldron** [comment]
Unfortunately the process of building the pre-compiled modules for mips is still manual. Basically serialport@4.0.6 was released and someone forgot to give us the heads up. I've built the binaries and deployed them to the server. 

![](https://i.gyazo.com/a1196eb6008ced79e981353a812bab95.png)

**Comment by chanceeakin** [comment]
Awesome! Thank you.
