### ISSUE TITLE
Missing compiled binary for node-hid@0.5.3

### ISSUE THREAD

**Issue by decrawford** [tessel/t2-cli#1126]
Missing compiled binary for node-hid@0.5.3
WARN Pre-compiled module is missing: node-hid@0.5.3.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.

**Comment by HipsterBrown** [comment]
Thanks for filing this issue @decrawford. Maybe @reconbot or @rwaldron can get this compiled and pushed up to our S3 bucket.

**Comment by rwaldron** [comment]
There is no node-hid@0.5.3 published to npm. Presently, 0.5.2 is the latest available version.

**Comment by HipsterBrown** [comment]
Oops, commented at the same time as @rwaldron.

**Comment by rwaldron** [comment]
I'm not sure this is going to cross-compile for us: 

```
make: Entering directory '/root/build/package/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
                    ^
compilation terminated.
hidapi.target.mk:96: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: Leaving directory '/root/build/package/build'
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
```

@reconbot how would we add libusb.h to our docker container for cross compilation?

**Comment by decrawford** [comment]
If it helps, I am using the Johnny 5 kit. This issue came up when I started playing with the USB Camera, using tessel-av.

**Comment by rwaldron** [comment]
I'm not sure I follow—what is node-hid being used for?

**Comment by decrawford** [comment]
I have no clue. I am not intentionally referencing it.  I just deleted node-hid from node_modules and redeployed the app file and the warning went away. So that may be caused by a lingering reference.

**Comment by rwaldron** [comment]
That's very strange, but I'm glad you're unblocked. I'm going to close this for now, since node-hid doesn't compile in our cross compilation toolchain
