### ISSUE TITLE
t2 push always uses rust remote compilation for rust project

### ISSUE THREAD

**Issue by mzgoddard** [tessel/t2-cli#1136]
In a rust project I can `t2 run <bin>` and compile locally. But when I try `t2 push <bin>` it compiles without the `--rustcc` flag both run and push have.

**Comment by rwaldron** [comment]
I wonder if the options isn't getting forwarded?

**Comment by rwaldron** [comment]
I found this, it was just an oversight when local compilation was added.

**Comment by rwaldron** [comment]
@mzgoddard are you using t2-cli from an npm install? If so, then please `npm uninstall -g t2-cli`, clone this repo and do `npm install && npm link`, then checkout the branch I've pushed to verify the fix—thanks!
