### ISSUE TITLE
Better error message for `No USB controller found on this system`

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#1158]
The `No USB controller found on this system` message is a common stumbling block for users. It occurs when they change their version of Node after installing t2-cli.

The fix: re-install `t2-cli` so that it can compile the correct USB drivers.

The `No USB controller` message is surfaced from the `node-usb` module, but it's a confusing message to receive from the t2-cli. A better error message would be `Please run npm install -g t2-cli to compile USB drivers for this version of node` or similar.

We could create this message via a try...catch statement when we `require(node-usb)`.

**Comment by crvineeth97** [comment]
Hello Frijol,

This is my first time contributing to open source and would like to take up this issue.

**Approach:** Change line no. 32 in lib/usb-connection.js from 
`log.error('WARNING: No usb controller found on this system.');` to 
`log.error('WARNING: Please run npm install -g t2-cli to compile USB drivers for the newer version of node');`

If there are any suggestions/improvements to my approach, please do specify.
Thank you.

**Comment by Frijol** [comment]
Thank you, and we're excited to have you! Your approach looks great. Please submit a pull request (let me know if you need help doing this).

I might also suggest a wording change in that error message– ideally, the message should:

1. Notify the user that something is wrong (I know my original issue suggestion doesn't do this, but it's probably a good idea to keep the original error message and just add on)
2. Tell them what is wrong and why (it might not be a newer version of Node, some users downgrade Node and have this issue- so should be "different" version of Node, maybe)
3. Suggest a possible fix (this seems good)

**Comment by Frijol** [comment]
Thanks for the fix, @crvineeth97 and welcome to the open source community :) 🎉
