### ISSUE TITLE
Add instructions for root access

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#116]
OSX: 

```bash
brew install dterm;
dterm /dev/tty.usbmodem1412 
# or `dterm /dev/tty.usbmodem1422
```

Others?

**Comment by johnnyman727** [comment]
It's probably worth noting that you can also SSH into the Tessel. The CLI uses SSH internally after you run `t2 provision` and it uses the key within `~/.tessel`. That means you can also manually do `ssh root@YOUR_IP -i ~/.tessel/id_rsa`

Or you can manually copy your regular SSH key into `/etc/dropbear/authorized_devices` and then use ssh without the `-i` option.

**Comment by rwaldron** [comment]
```
$ ssh root@192.168.1.9 -i ~/.tessel/id_rsa
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/Users/rwaldron/.tessel/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
bad permissions: ignore key: /Users/rwaldron/.tessel/id_rsa
```

**Comment by johnnyman727** [comment]
This key issue will be fixed with https://github.com/tessel/t2-cli/pull/154.

**Comment by nodebotanist** [comment]
Heads up: if you don't include the baudrate, it can hang on macs:

```
dterm /dev/tty.usbmodem**** 115200
```

**Comment by johnnyman727** [comment]
@nodebotanist I hadn't seen that happen before but it's good to know in case it doesn't work!

**Comment by Frijol** [comment]
Where should this be documented?

**Comment by johnnyman727** [comment]
IMO, it should be in the https://www.github.com/tessel/onboarding docs because only Team Members actually have hardware. Some folks who use the CLI use it with the VM so doesn't necessarily belong here.

**Comment by Frijol** [comment]
Want to be more futureproof than "x are the only people who have hardware".

**Comment by johnnyman727** [comment]
Yes, but it will soon be [semi] obselete when https://github.com/tessel/t2-cli/issues/80 is finished.

**Comment by Frijol** [comment]
ah sure

**Comment by flaki** [comment]
So I took a stab at this on Linux/Ubuntu x64. `dterm` is not included, and is not in the binary distros either which complicates things a bit so first one has to:

## Compiling `dterm` from source
Fetch the source from [knossos.net.nz](http://www.knossos.net.nz/resources/free-software/dterm/), I used `[dterm-0.3.tgz](http://www.knossos.net.nz/downloads/dterm-0.3.tgz)`. You would then go on to:
```
tar -xzvf dterm-0.3.tgz
cd dterm-0.3
make
sudo make install
```
For any build prequisites [you should refer to the ubuntu community howto](https://help.ubuntu.com/community/CompilingEasyHowTo).

There is then one more pitfall I bumped into, on ubuntu the socket is referenced as `ttyACM0`, so you use:
```
dterm /dev/ttyACM0
```
It worked without a baudrate for me.

## Once connected via `dterm`
Find `/etc/dropbear/authorized_keys`, and add your public key `~/.tessel/id_rsa.pub` (`t2 provision` should have alredy created this for you):
```
nano /etc/dropbear/authorized_keys
```
## SSH in!
Use your private key to jump in:
```
ssh root@<TESSEL_2_IP> -i ~/.tessel/id_rsa
```
If you need to find out your Tessel's network ip, use `ifconfig` from the `dterm` console.

**Comment by johnnyman727** [comment]
Thanks for putting this together, @flaki! Hope the learning wasn't too painful :)

**Comment by johnnyman727** [comment]
Closing because now we have `t2 root`.
