### ISSUE TITLE
Include connection type with crash report

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#1172]
If the crash occurs while connected, it will be helpful to know what kind of connection was made, ie. USB or LAN

**Comment by rwaldron** [comment]
@tikurahul will t2-crash-reporter need to be updated to accept a new tag?

**Comment by tikurahul** [comment]
Do you want this to be an additional label? Or do you want special treatment like we did for argv ? If it's just a label then no changes needed. Otherwise it's a small change to include that as part of the report and the UI.

**Comment by rwaldron** [comment]
Just a new label!
