### ISSUE TITLE
Task runner and common dev tasks

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#118]
- Pick one, it doesn't matter: Grunt or Gulp? I vote Grunt, but will use either
- Tasks: 
  - JSHint
  - JSCS
  - Test Runner

**Comment by johnnyman727** [comment]
+1 to Grunt

**Comment by rwaldron** [comment]
Cool. I can get started on this

**Comment by johnnyman727** [comment]
That would be fantastic. I don't have much experience building scalable test benches so it'd be great to learn more about Grunt.

**Comment by rwaldron** [comment]
Working through this and I'm a little overwhelmed. These changes necessary to make these new quality control tools happy are massive.

**Comment by rwaldron** [comment]
There are a lot of bugs that will be fixed in this process, so care should be taken to test the patch thoroughly.
