### ISSUE TITLE
Tab completion for `t2 ...`

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#119]
See: https://github.com/gruntjs/grunt-cli

**Comment by chrisbodhi** [comment]
I [submitted a PR](https://github.com/tessel/t2-cli/pull/509) for this, but the builds failed. Reviewing [the npm docs](https://docs.npmjs.com/misc/scripts), I came across this bit:

>Don't use `install`. Use a `.gyp` file for compilation, and `prepublish` for anything else. You should almost never have to explicitly set a preinstall or install script. If you are doing this, please consider if there is another option. The only valid use of `install` or `preinstall` scripts is for compilation which must be done on the target architecture.

Currently, I'm running a shell script to add the tab completion, which happens as part of the `install` hook. This seemed like the most logical place to put the shell script, but I'm open to suggestions for where else -- or how else -- it can be executed.

**Comment by rwaldron** [comment]
Looking at https://github.com/tessel/t2-cli/pull/509/files and I think there is a misunderstanding of the goal for this issue. I want `t2 ...` + `[character]` + `<tab>`. I was using grunt as an example. Grunt cli tab completion for grunt itself is the responsibility of Grunt cli: https://github.com/gruntjs/grunt-cli#shell-tab-auto-completion

**Comment by chrisbodhi** [comment]
Thanks for clearing that up. Are you thinking of something along the lines of this: https://github.com/creationix/nvm/blob/master/bash_completion ?

**Comment by rwaldron** [comment]
@chrisbodhi yep—exactly like that :)

**Comment by chrisbodhi** [comment]
@rwaldron :cool: I should be able to get to it this weekend. :raised_hands:

**Comment by johnnyman727** [comment]
:exclamation: :exclamation: :exclamation:

**Comment by chrisbodhi** [comment]
Finished the bash script over the weekend, but wanted to get in zsh support, too. I based the list of supported commands from what I found in `bin/tessel-2.js`, but I could have misunderstood some of what was going on there. Please feel free to correct me!
