### ISSUE TITLE
Pre-compiled module is missing: midi@0.9.5

### ISSUE THREAD

**Issue by crstffr** [tessel/t2-cli#1203]
```
WARN Pre-compiled module is missing: midi@0.9.5.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
WARN 
WARN This warning might be caused by one of the following:
WARN 
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.
```

Hi, trying to import the node midi package into an otherwise empty project.  This happens when trying to ``t2 run index.js``.

Thanks.

**Comment by HipsterBrown** [comment]
@crstffr It looks like we have the pre-compiled module for `midi@0.9.5` in our storage, so I'll try this out on my local tonight. Otherwise, I'll try to recompile the package and upload it to our storage.

**Comment by crstffr** [comment]
@HipsterBrown thanks for taking a look.  How would I go about accessing the package from your storage?

**Comment by HipsterBrown** [comment]
`t2-cli` does that for you. What version of Node (`node -v`) and `t2-cli` (`t2 version`) are you using?

**Comment by crstffr** [comment]
Local node: v6.9.2

```
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.4
INFO t2-firmware: 0.0.16
INFO Node.js: 4.5.0
```

**Comment by crstffr** [comment]
Sounds good, thanks.

**Comment by rwaldron** [comment]
I've just pre-compiled midi@0.9.5 and pushed it the pre-compiled module server

**Comment by giavani1947** [comment]
> I've just pre-compiled midi@0.9.5 and pushed it the pre-compiled module server

I've got this same issue with running the t2 led.js experiment.
