### ISSUE TITLE
t2 list shows tessel on LAN, other t2 commands cannot find device

### ISSUE THREAD

**Issue by crstffr** [tessel/t2-cli#1204]
When I run ```t2 list``` my device shows up connected to LAN, but whenever I run any thing else (```t2 root```, ```t2 run index.js```, ```t2 restore```, etc) - I usually get the ```WARN No Tessels Found.``` message.  I typically need to run a command dozens of times before it will find my device.

A reboot of the tessel usually helps once, but then it's back to the same problem.

I am using OSX terminal, node v6.9.2, t2-cli v0.1.4, t2 firmware v0.0.16.

I have also tried multiple tessels, each one seems to have the same problem.

**Comment by crstffr** [comment]
I just identified that my internet connection (wireless router) was being a pile of 💩 .

I power cycled my modem and wireless router and it looks like things are better.

**Comment by HipsterBrown** [comment]
Glad you were able to find a fix for that. :+1:
