### ISSUE TITLE
No Authorized Tessels Found

### ISSUE THREAD

**Issue by madskunker** [tessel/t2-cli#1209]
Just updated everything and this is what I get

Jeffs-IMac:btdevice snowdog1506$ t2 list
INFO Searching for nearby Tessels...
 	USB	BowTieDevice	
Jeffs-IMac:btdevice snowdog1506$ t2 provision
INFO Looking for your Tessel...
INFO Connected to BowTieDevice.
INFO Creating public and private keys for Tessel authentication...
INFO SSH Keys written.
INFO Authenticating Tessel with public key...
INFO Tessel authenticated with public key.
Jeffs-IMac:btdevice snowdog1506$ t2 root
INFO Looking for your Tessel...
WARN No Authorized Tessels Found.

Was working fine till 30 minutes ago

Now no matter what I do there is no way to access the device

Completely Bricked

Jeff

**Comment by madskunker** [comment]
Did a t2 restore and wiped the ~/.tessel directory and get the same result after doing a new provision

**Comment by madskunker** [comment]
Resolved but in an odd way.

Using a 2nd Mac I was able to force provision the t2.  Then I could t2 root on the 2nd machine.
Then I was able to reconnect the t2 to the 1st Mac and then I could t2 root and successfully

**Comment by Frijol** [comment]
Thanks for reporting. What do you mean by "force provision"?

**Comment by madskunker** [comment]
I ran t2 provision -f

Sent from my iPhone

On May 25, 2017, at 6:11 PM, Kelsey <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reporting. What do you mean by "force provision"?

**Comment by rwaldron** [comment]
Sometimes that's all it tales ¯\_(ツ)_/¯

**Comment by mbrevda** [comment]
I don't have access to another mac and `-f`. Is there another way to fix this?
