### ISSUE TITLE
Get i2c address

### ISSUE THREAD

**Issue by opkiler22789** [tessel/t2-cli#1257]
Hello, Is there any way to get i2c address? In the likeness of [i2c_scanner](http://playground.arduino.cc/Main/I2cScanner)?

**Comment by rwaldron** [comment]
Thanks for filing an issue. Presently, there is no way to do i2c scanning as it's show in `i2c_scanner`. I'm moving this to [t2-firmware](https://github.com/tessel/t2-firmware)
