### ISSUE TITLE
t2 list will hang forever if you're not connected to Wifi

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#127]
We need to start doing a check before starting the mDNS browser to ensure you are connected to WiFi. It's possible that we can just add an error event handler but I haven't checked if the `mdns-js` lib we're using throws an error when you're offline.

**Comment by LinusU** [comment]
I believe that this is fixed by ac40d9de0fa43ff0ffefdcf6c5fe7045ab8079ec

**Comment by johnnyman727** [comment]
Confirmed! Thanks for checking.
