### ISSUE TITLE
ERR! TypeError: Cannot read property 'length' of null (V0.1.10)

### ISSUE THREAD

**Issue by SandorvanderNeut** [tessel/t2-cli#1288]
After installing the latest version v0.1.10 I get the following error when I run a script:

PS C:\Users\Sandor\j5> t2 run switch.js
INFO Looking for your Tessel...
INFO Connected to <my t2>.
ERR! TypeError: Cannot read property 'length' of null.

Before installing the upgrade everything worked fine.

Kind regards,
Sandor

**Comment by thomas3577** [comment]
I have the same problem

**Comment by SandorvanderNeut** [comment]
I installed a previous release and that solved the problem for now

**Comment by thomas3577** [comment]
Hi,
Why closed? It seems, this issue isn't solved.
