### ISSUE TITLE
Cannot run t2 update or t2 run

### ISSUE THREAD

**Issue by JamesIves** [tessel/t2-cli#1295]
Trying quite a few things here but I'm struggling to get either to work. Whenever I run `t2 update` I get stuck on `Download Completed` and whenever I run `t2 run` or `t2 push` I get stuck on `INFO Writing project to RAM on montezooma (2109.952 kB)...`.

Any workarounds? I was using firmware version 0.0.6 as I was trying to get around an issue I was having.

**Comment by dtex** [comment]
@JamesIves You are not alone in t2 update getting stuck on ```Download Completed```. We had that happening a lot this weekend. However, the firware update seemed to have worked successfully. We just had to hit ```ctrl-c```. 

What version of the t2-cli are you running? If you've updated the firmware you may also need to update that.

**Comment by JamesIves** [comment]
Running the latest version (I was at the Houston event!) 

Right now the device doesn't seem to boot at all, running `t2 list` results in `WARN Detected a Tessel that may be booting.`. Not exactly sure how to proceed. I see there's a `t2 restore` command but not entirely sure if I should be running it or not.

**Comment by JamesIves** [comment]
Another update on this; Tried running `t2 update` and let it sit for over 3 hours, it just refuses. Tried `t2 restore` and it just gets stuck at `INFO Bulk Erasing Flash Memory (this may take a minute)...`. 

The green light near the ethernet port doesn't turn on, instead I have a red light on the board and a rotating green/blue light.

Starting to worry that the board is bricked, but not entirely sure how this came to be.

**Comment by dtex** [comment]
Yes, there is. I'll see if I can track that down...

**Comment by dtex** [comment]
In the dark days before ```t2 update``` this was the process...

https://github.com/tessel/t2-firmware#compiling

**Comment by JamesIves** [comment]
Gave that a shot and I end up with a single flashing blue light on the board now, guessing this just indicates that it has a power source. It still refuses to fully power on though.

`t2 list` shows the same warning of `WARN Detected a Tessel that may be booting.`

**Comment by dtex** [comment]
Did you do the openwrt install also? It's in a link near the bottom

**Comment by JamesIves** [comment]
The documentation only seems to show how to update OpenWRT if `t2 update` is available, which in this case it's not due to the booting error.

**Comment by dtex** [comment]
Sorry, I didn't realize the manual OpenWRT install steps had been removed.

**Comment by dtex** [comment]
Woo hoo!

**Comment by rwaldron** [comment]
> Any workarounds? I was using firmware version 0.0.6 as I was trying to get around an issue I was having.

This was actually the problem :( That version of the firmware would never be able to upgrade to the latest version because there were breaking changes introduced in December 2015—but that was before the Tessel 2 ever shipped and it really only messed up our early development boards. The first firmware version that shipped in production boards was 0.0.12.

Maybe `t2 restore` needs to be more prominent in the docs...?
