### ISSUE TITLE
Post install script assumes a tessel is connected

### ISSUE THREAD

**Issue by dtex** [tessel/t2-cli#1296]
Not sure if this is a a t2-cli issue or a documentation issue (or a "dtex doesn't get it" issue)...

The t2-cli post install script assumes a tessel is connected:

````
> t2 install drivers --loglevel=error || true; t2 install homedir --loglevel=error || true;

ERR! Permissions issue detected.
ERR! Try using 'sudo t2 install drivers --loglevel=error'
ERR! Permissions issue detected.
ERR! Try using 'sudo t2 install homedir --loglevel=error'
````

But http://tessel.io/start doesn't have the users connecting their Tessels until after installing t2-cli.

**Comment by HipsterBrown** [comment]
Hmm yea that's an interesting assumption the CLI makes for every install. How could we enable running this step for users without doing it for every installation of `t2-cli`?

**Comment by rwaldron** [comment]
> The t2-cli post install script assumes a tessel is connected

Nope, it specifically bypasses the `standardTesselCommand` pipeline and just calls one of the "installer" operations. The postinstall script is that's acting up here is from `t2 install drivers` follows: 

- https://github.com/tessel/t2-cli/blob/master/bin/tessel-2.js#L96
- https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L1090-L1093  
- https://github.com/tessel/t2-cli/blob/master/lib/installer.js#L14-L54

And the short description of that is that it makes a copy of https://github.com/tessel/t2-cli/blob/master/resources/85-tessel.rules and writes it in `/etc/udev/rules.d/` on linux machines. If there are permissions problems, an error occurs: https://github.com/tessel/t2-cli/blob/master/lib/installer.js#L29-L30, but no Tessel is involved.
