### ISSUE TITLE
Pre-compiled module is missing: websocket@1.0.24

### ISSUE THREAD

**Issue by akkashaider** [tessel/t2-cli#1329]
WARN Pre-compiled module is missing: websocket@1.0.24.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
WARN 
WARN This warning might be caused by one of the following:
WARN 
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.

**Comment by rwaldron** [comment]
Pre-compiled modules built and deployed 

![](https://i.gyazo.com/9b509cdb7797167291676ce8324dad02.png)

**Comment by akkashaider** [comment]
@rwaldron Thanks for your help. 
I am getting the following error now. Can you please have a look. 
ERR! { Error: ENOENT: no such file or directory, stat '/home/haider/.tessel/binaries/websocket-1.0.24-Release-node-v48-linux-mipsel/Release/bufferutil.node'
ERR!     at Error (native)
ERR!     at Object.fs.statSync (fs.js:1001:11)
ERR!     at Object.statSync (/home/haider/.npm-global/lib/node_modules/t2-cli/node_modules/graceful-fs/polyfills.js:297:22)
ERR!     at Object.copySync (/home/haider/.npm-global/lib/node_modules/t2-cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:20:58)
ERR!     at binaryModulesUsed.forEach.error (/home/haider/.npm-global/lib/node_modules/t2-cli/lib/tessel/deployment/javascript.js:405:16)
ERR!     at Map.forEach (native)
ERR!     at Promise (/home/haider/.npm-global/lib/node_modules/t2-cli/lib/tessel/deployment/javascript.js:378:23)
ERR!     at Object.exportables.injectBinaryModules (/home/haider/.npm-global/lib/node_modules/t2-cli/lib/tessel/deployment/javascript.js:370:10)
ERR!     at project.collect (/home/haider/.npm-global/lib/node_modules/t2-cli/lib/tessel/deployment/javascript.js:639:23)
ERR!     at Promise.all.then (/home/haider/.npm-global/lib/node_modules/t2-cli/node_modules/t2-project/lib/index.js:217:7)
ERR!   errno: -2,
ERR!   code: 'ENOENT',
ERR!   syscall: 'stat',
ERR!   path: '/home/haider/.tessel/binaries/websocket-1.0.24-Release-node-v48-linux-mipsel/Release/bufferutil.node' }

**Comment by rwaldron** [comment]
That's really strange... What modules did you `npm install` yourself?

**Comment by rwaldron** [comment]
Ok, I see what's going on, but not sure how or why this isn't working correctly. There is a second binary that should be created, which is not being created by the compiler https://github.com/theturtle32/WebSocket-Node/blob/master/binding.gyp#L10-L16

**Comment by rwaldron** [comment]
node-pre-gyp doesn't support pre-gyp'ing a module that produces multiple binary objects :|
There's an [issue about it](https://github.com/mapbox/node-pre-gyp/issues/171), but it doesn't look like this is ever going to be fixed for our needs. With that in mind, I just built the tgz manually and put it on the precompiled module server. You'll need to remove the cached copy first: 

```
cd ~/.tessel/binaries
rm -r websocket-1.0.24-Release-node-v48-linux-mipsel
```

**Comment by akkashaider** [comment]
Thanks it worked for me.
