### ISSUE TITLE
Pre-compiled module is missing: grpc@1.6.6.

### ISSUE THREAD

**Issue by jakecahill** [tessel/t2-cli#1349]
Hi,

I'm trying to use the tessel-av Microphone module, but I keep getting this error:
Pre-compiled module is missing: grpc@1.6.6.

Please could someone advise me on what to do.

Thanks,

Jake

**Comment by KyleWMiller** [comment]
@jakecahill I'm wondering if that just means that a tessel 2 compatible version isn't available yet. I have a similar issue

**Comment by rwaldron** [comment]
That's strange, tessel-av doesn't depend on that module. 

Either way, I've built the pre-compiled modules and pushed them to the package server: 

![](https://i.gyazo.com/9f120ee316cfb09a6d85c05328512fba.png)

**Comment by KyleWMiller** [comment]
@rwaldron how do you precompile a module so if I come across this issue again I can help fix said issue?

**Comment by rwaldron** [comment]
To do it manually is kind of a pain in the ass, but like this: 

1. Clone https://github.com/tessel/t2-compiler/
2. Follow the installation and setup instructions
3. Run either `./compile-docker.sh module@X.X.X` or `./compile-vagrant.sh module@X.X.X`
4. Open `t2-compiler/out` and unzip the resulting .tgz into `$HOME/.tessel/binaries/`

When you `t2 run ...` the bundler process will look for the precompiled modules in `$HOME/.tessel/binaries/`

**Comment by KyleWMiller** [comment]
@rwaldron then how do you push them to the public?

**Comment by rwaldron** [comment]
There is no way to do that without providing credentials to the Tessel Project's AWS account

**Comment by KyleWMiller** [comment]
@rwaldron ok Thanks for the info. I have found a few other packages that aren't in the tessel account file: `colony-compiler`, `colors`, `colorsafeconsole`, effess`, `hardware-resolve`, `humanize`, `my-local-ip`, `nomnom`, `semver`, `structured-clone`, temp`, and `usb`. 

Thanks for working to make this project grrrrrrrrreat!

**Comment by KyleWMiller** [comment]
@rwaldron Thanks for the info
