### ISSUE TITLE
Pre-compiled module is missing: serialport@6.0.0

### ISSUE THREAD

**Issue by KyleWMiller** [tessel/t2-cli#1350]
I am trying to work through the J5 inventor's kit and when I got to the `intruder-alert` with `twilio` project I kept getting errors saying that some variable was removed. (It said "t" but it was minified)

I am running this on OSX and my first try after following the instructions I received a slew of errors related to permissions, `serialport` and `node-gyp`. So I tried removing the `node_modules` dir and reinstalled everything with yarn. 

I manually installed `serialport` and `node-gyp`, then when I ran the program again it asked me to file this 'new' issue. 

Any help would be appreciated
thx

**Comment by rwaldron** [comment]
Sorry about that! This just means that `serialport` has a new release and we need to make a pre-compiled binary for this release. I've built the pre-compiled modules and pushed them to the package server: 

![](https://i.gyazo.com/e36fc924b333b4bc40fa11d5a8579e3b.png)

**Comment by KyleWMiller** [comment]
@rwaldron Thanks!
