### ISSUE TITLE
How do see the the log with PUSH command

### ISSUE THREAD

**Issue by manjunathgudisi** [tessel/t2-cli#1356]
Hi

> $ t2 run index.js
I see the logs in the command prompt when I run above command.

> $t2 push index.js
I dont see any logs. Is there any way to see the logs.

here is the screenshot

![screen shot 2017-10-22 at 7 59 24 pm](https://user-images.githubusercontent.com/6059076/31862909-d1e5d456-b763-11e7-8f26-c0ce6e9d188b.jpg)

Thanks, MG

**Comment by HipsterBrown** [comment]
Hi @manjunathgudisi, `t2 push` writes your program to the Tessel flash storage and runs it whenever the device starts. The only way to see logs at that point would be to monitor that process on the device or output your logs to a file or remote service using something like (Winston)[https://www.npmjs.com/package/winston].

**Comment by Student007** [comment]
@HipsterBrown @manjunathgudisi can this be closed ?

**Comment by HipsterBrown** [comment]
@Student007 Yes, thanks for the heads up. We can reopen if this question comes up again.
