### ISSUE TITLE
"INFO Connected over X" additional details

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#139]
When connected via LAN: 

```
INFO Connected over LAN. IP ADDRESS: 192.168.1.9
```

However, via USB: 

```
INFO Connected over USB.
```

The USB connection should include some relevant information about the connection.

**Comment by johnnyman727** [comment]
@rwaldron The issues tagged `spec` have document how each command is supposed to work. Once they are completed, it should print the name of the Tessel you connect to. Does that seem sufficient to you?

**Comment by johnnyman727** [comment]
Closing because we don't print out the IP Address anymore. Consistency achieved!

**Comment by rwaldron** [comment]
:clap:
