### ISSUE TITLE
"Cannot find module"  error from a file in subdirectory

### ISSUE THREAD

**Issue by rraphal** [tessel/t2-cli#1400]
Hi,
I have an index.js  - a very simple api using express, jsonwebtoken, axios, etc. It's running perfectly fine, when executed on local node.js

This index.js requires several files (api routes) from a subdirectory. Those files require certain node modules.

When I excute "t2 run index.js", I get an error, for example "Cannot find module 'axios'" - coming from the files in sub-directory.

Am I missing something?

**Comment by rwaldron** [comment]
> This index.js requires several files (api routes) from a subdirectory. Those files require certain node modules.

Have a look at [`.tesselinclude`](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#project-files).
