### ISSUE TITLE
t2 update failed

### ISSUE THREAD

**Issue by strawherotk** [tessel/t2-cli#1404]
Hi majgis,
Did you find solution for that?
I failed updating Tessel too.
It keep blink the blue LED, and nothing happened.
I tried to find tessel using t2 -list but didn't work.
My log:
`PS C:\Users\10202> t2 update
node-pre-gyp INFO Looking for your Tessel...
node-pre-gyp INFO Connected to TesselBoard.
node-pre-gyp INFO New firmware version found... 0.1.0
node-pre-gyp INFO Updating TesselBoard to latest version (0.1.0)...
node-pre-gyp INFO Downloading files...
node-pre-gyp INFO Download complete!
node-pre-gyp INFO Updating OpenWRT (1/2)
node-pre-gyp INFO Transferring image of size 15.99 MB. This will take 2-4 minutes...
node-pre-gyp INFO Transfer complete.
node-pre-gyp INFO Starting OpenWRT update.
node-pre-gyp INFO Please do not remove power from Tessel.
node-pre-gyp INFO This process will take at least 2 minutes...
node-pre-gyp INFO Configuration is saved during update.
node-pre-gyp INFO Updating firmware (2/2)
node-pre-gyp ERR! Detected CLI crash Error: No device found in bootloader mode
node-pre-gyp ERR! at C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:364:19
node-pre-gyp ERR! at new Promise ()
node-pre-gyp ERR! at USB.Connection._findBootedDeviceBySerialNumber (C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:348:10)
node-pre-gyp ERR! at Timeout.retry [as _onTimeout] (C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:325:12)
node-pre-gyp ERR! at ontimeout (timers.js:475:11)
node-pre-gyp ERR! at tryOnTimeout (timers.js:310:5)
node-pre-gyp ERR! at Timer.listOnTimeout (timers.js:270:5) Error: No device found in bootloader mode
node-pre-gyp ERR! at C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:364:19
node-pre-gyp ERR! at new Promise ()
node-pre-gyp ERR! at USB.Connection._findBootedDeviceBySerialNumber (C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:348:10)
node-pre-gyp ERR! at Timeout.retry [as _onTimeout] (C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:325:12)
node-pre-gyp ERR! at ontimeout (timers.js:475:11)
node-pre-gyp ERR! at tryOnTimeout (timers.js:310:5)
node-pre-gyp ERR! at Timer.listOnTimeout (timers.js:270:5)
undefined
Submit Crash Report to help Tessel Developers improve the CLI ?
If yes(y), subsequent crashes will be submitted automatically. Yes
node-pre-gyp INFO Crash Reported: http://crash-reporter.tessel.io/crashes?fingerprint=0x493daad6
\
`
During update, I tried to find my Tessel using: "t2 -list". Not sure if it affected the updating process.

Looking for your help!
Thank you.
Victor.

**Comment by strawherotk** [comment]
Is there anyway to attach the log file? It maybe easier to watch.

**Comment by strawherotk** [comment]
Now, each time I find the device, it got CLI crash, and pending forever:

`C:\Users\10202>t2 list
node-pre-gyp INFO Searching for nearby Tessels...
node-pre-gyp ERR! Detected CLI crash { Error: LIBUSB_TRANSFER_STALL errno: 4 } Error: LIBUSB_TRANSFER_STALL
node-pre-gyp INFO Crash Reported: http://crash-reporter.tessel.io/crashes?fingerprint=0x4fce9a8d
|
`

What should I do now?
I tried to unplug and plug it PC again. but not work.
Shall I reinstall the driver? Is there anyhow to hard-reset?

**Comment by strawherotk** [comment]
After leave the board for a while, it's still running.
I press CTRL+C to end the task from CMD.
And WOALA. It finished sending request.
And the magic is that everything worked as usuall, the newest firmware (0.1.0) is installed.
The only thing get reset is the board of name. Wifi configuration still there.

Hope everything would be fine.
Cheer!

**Comment by strawherotk** [comment]
It seems the old firmware has caused problem. I can not run my ambient module.

**Comment by strawherotk** [comment]
UPDATED: DO NOT leave focus from your CLI when the update is running.
I restored successfully, hope the update firmware will work as well.

**Comment by strawherotk** [comment]
SOLUTION:
After checking ambient page in page.
I've **changed the ambient module to port B**, and it worked.
The firmware for that module get installed and it ran properly.
Although there is an error on the first time I run the ambient.js

**Comment by rwaldron** [comment]
Thanks for the update.
