### ISSUE TITLE
start/stopRunningScript commands should have an acutal lifetime

### ISSUE THREAD

**Issue by tcr** [tessel/t2-cli#146]
Temporarily in #145 this is changed to `killall node` to emulate the correct behavior, since running a script from RAM does not involve `/etc/init.d/tessel-app`.

`startRunningScript` and `stopRunningScript` should use a daemon, or at least link the lifetime of the PID to the lifetime of the running script.

**Comment by johnnyman727** [comment]
This might be more of an issue of naming `stopRunningScript` and `startRunningScript` are only used for `pushed` scripts. Scripts that are executed with `run` just send a signal to the remote process to kill them.

**Comment by tcr** [comment]
In practice, the process killing (with Ctrl+C) was never executing. At least in my VM. Race error?

**Comment by johnnyman727** [comment]
[It's certainly not the best implementation](https://github.com/tessel/t2-cli/blob/fb2da9f4293ba7755aaabda1aa10cc07e8a2bdb0/lib/tessel/tessel.js#L14-L20) but I don't think it's a race condition. Maybe check if that event listener is being hit?

**Comment by tcr** [comment]
The event listener is being hit. Looks like `this.connection.end(function() {` isn't actually killing the Node process? Simple reproduction in a VM after rolling back the changes in #145:

index.js:

```
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(1337);
console.log('Server running at http://127.0.0.1:1337/');
```

Running the script twice:

```
➜  helloworld  t2 run index.js Tessel-080027FE6BA4
INFO Connecting to Tessel...
INFO Connected over LAN. IP ADDRESS: 192.168.128.225
INFO Bundling up code...
INFO Bundled. Writing to T2.... 3072
INFO Deployed.
INFO Running script...
hello world!
Server running at http://127.0.0.1:1337/
^Csigint
done
➜  helloworld  t2 run index.js Tessel-080027FE6BA4
INFO Connecting to Tessel...
INFO Connected over LAN. IP ADDRESS: 192.168.128.225
INFO Bundling up code...
INFO Bundled. Writing to T2.... 3072
INFO Deployed.
INFO Running script...
hello world!
Server running at http://127.0.0.1:1337/
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE :::1337
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at Server._listen2 (net.js:1165:14)
    at listen (net.js:1195:10)
    at Server.listen (net.js:1282:5)
    at Object.<anonymous> (/tmp/remote-script/index.js:7:4)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
```
