### ISSUE TITLE
Detected a Tessel that may be booting......No Tessel Found

### ISSUE THREAD

**Issue by otieno-o** [tessel/t2-cli#1462]
Hello guys,
I have a tessel 2 board, recently acquired. I have tried to follow the instruction on [http://tessel.github.io/t2-start/] however, when in enter "t2 list". I received the following response 

INFO Searching for nearby Tessels...
WARN Detected a Tessel that may be booting.
WARN No Tessels Found

The power LED is blinking blue and the error LED has a continuous red light, so I suppose there is some error.
I have tried to follow some of the suggestions to fix it, but no success so far.

I'm using a 64bit Win 10 PC.

i appreciate your assistance in getting this solved. Thanks

**Comment by andris310** [comment]
Same issue. t2 used to work fine until a few days ago it got into this same state and no way to get it reboot properly. Blinking blue light, solid red and green.

**Comment by StudentESE** [comment]
You could try to [reset](https://tessel.gitbooks.io/t2-docs/content/API/Hardware_API.html) the Tessel ...


> If you hold down the button while plugging in power, Tessel 2 boots into DFU mode. This is typically used to load firmware built from source.

**Comment by andris310** [comment]
When I do that, plug in while holding down button, I get blinking blue led, and dim, solid red ERR led. And the board gets hot.

**Comment by andris310** [comment]
💩

**Comment by Joel-Torres** [comment]
Hello, 
My tessel 2 was working fine until I was prompted to update the CLI. and now it does not find my tessel. any suggestions?

**Comment by woosungchu** [comment]
both happend to me in window 10

1. get tessel today and follow Blink LED guide
2. Stuck on problem and 't2 update'
3. error occured while 't2 update' and 't2 restore' (not working)
4. cant find tessel ....

! My laptop successfully found my tessel while setup before 't2 update'
