### ISSUE TITLE
Pre-compiled module is missing: serialport@6.2.0.

### ISSUE THREAD

**Issue by stevekinney** [tessel/t2-cli#1473]
Hey friends—getting this warning: 

```
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.
```

This doesn't appear to be problematic, but it says to file an issue—so, here I am. :smile:

**Comment by HipsterBrown** [comment]
Thanks for creating an issue @stevekinney. One of us will compile the binary for this. /cc: @rwaldron @reconbot @tcr

**Comment by HipsterBrown** [comment]
@stevekinney I've uploaded the pre-compiled binaries for serialport@6.2.0. Let me know if you encounter any other issues.
