### ISSUE TITLE
The t2-cli package is no longer support by NPM?

### ISSUE THREAD

**Issue by strawherotk** [tessel/t2-cli#1480]
Hi Team,

Yesterday I’ve just tried to install npm tessel package (`npm install -g t2-cli`) on new computer, but I got this message:
`npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.`

Is that **Tessel package** is no longer support by **NPM**?
I also submit an issue on **tessel.io**, Since I cannot access Tessel website anymore.

Thanks,
Victor.

**Comment by tikurahul** [comment]
Sorry. Accidentally clicked on close issue there.

**Comment by HipsterBrown** [comment]
> nomnom@1.8.1: Package no longer supported.

That message is specifically about the package `nomnom` that we use for reading arguments from the command line. It’s been deprecated by the package author and we need probably need to switch to something actively maintained eventually. 

`t2-cli` is still actively maintained.
