### ISSUE TITLE
Running led.js bringing 3 issues (module is missing, throw err, cannot find accelerometer)

### ISSUE THREAD

**Issue by Mochadadog** [tessel/t2-cli#1482]
I honestly don't know where to start but the stuff in the picture is ran from terminal. I don't know what it's talking about the accelerometer. I tried most of what i can do and I'm on the stuck point. plz help ASAP.
Should I just reset the tessel and the j5ik files?
![image](https://user-images.githubusercontent.com/40326604/41503810-71789830-7192-11e8-8068-7479a7a00243.png)
this is the led experiment code:
''
var Tessel = require("tessel-io");
var five = require("johnny-five");

var board = new five.Board({
  io: new Tessel()
});

board.on("ready", () => {
  var led = new five.Led("a5");
  led.blink(500);
});
''

**Comment by Mochadadog** [comment]
So please help with these three issues and I'm having no luck fixing it. :(

**Comment by HipsterBrown** [comment]
@Mochadadog Thanks for creating an issue. What version of Node are you using? We have a compiled binary for `serialport@6.0.5` on Node 6.

**Comment by Mochadadog** [comment]
I already resolved this issue I just ignored the serialport@6.0.5 (I noticed when i run index.js, it works fine even though the serialport@6.0.5) I fixed the accelerometer by making the node.js version to the version package.json works on. which is 8.11.1

**Comment by Mochadadog** [comment]
wouldn't work if i use node 6.0.5 but can't run the package.json. but the issue is resolved. thanks for trying though. :)

**Comment by HipsterBrown** [comment]
Glad you resolved the issue. Let me know if you run into any other blockers. 👍

**Comment by Mochadadog** [comment]
Okay. 👍 👍 👍
