### ISSUE TITLE
Pre-compiled module is missing: fsevents@1.2.4.

### ISSUE THREAD

**Issue by joshunger** [tessel/t2-cli#1550]
```
WARN Pre-compiled module is missing: fsevents@1.2.4.
WARN Please an file issue at https://github.com/tessel/t2-cli/issues/new with this warning.
WARN 
WARN This warning might be caused by one of the following:
WARN 
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.
```

**Comment by HipsterBrown** [comment]
@joshunger `fsevents` can only be used on OS X. From the package readme:

> This is a low-level library. For a cross-compatible file watching module that uses fsevents, check out Chokidar (https://www.npmjs.com/package/chokidar)

Do you know if this is a direct dependency of your project or a sub dependency?

**Comment by joshunger** [comment]
I just added `jest` to the project.

```
└─┬ jest@23.6.0
  └─┬ jest-cli@23.6.0
    └─┬ jest-haste-map@23.6.0
      └─┬ sane@2.5.2
        └── fsevents@1.2.4 
```

**Comment by HipsterBrown** [comment]
🤔 And are you requiring `jest` in the code you push to Tessel? Or are you still using `--full`?

**Comment by joshunger** [comment]
Nope and nope. Is there a verbose flag I can add to `t2 run`?

**Comment by HipsterBrown** [comment]
Yes, `-v` or `--verbose` works. 

> Choose to view more debugging information

**Comment by HipsterBrown** [comment]
If you're not requiring it, it shouldn't cause any issues in your project. But I'm sure it's a little annoying to see whenever you run your code.

**Comment by HipsterBrown** [comment]
Closing as it is not possible to compile `fsevents` for mipsel architecture. 

> fsevents can only be used on OS X. From the package readme:

>This is a low-level library. For a cross-compatible file watching module that uses fsevents, check out >Chokidar (https://www.npmjs.com/package/chokidar)
