### ISSUE TITLE
Detected CLI crash Error: No device found in bootloader mode (Win 10, Node v8.11.1)

### ISSUE THREAD

**Issue by allenjwelch** [tessel/t2-cli#1599]
Trying to get a new tessel 2 up and running and keep getting the following error when running 't2 update'. After crashing, I use ctrl+c to exit and attempted to run update again, but am told that my tessel is currently on the latest version (0.2.0) of firmware. I've tried running a simple project (t2 run led.js) regardless of the update status and receive a warning reading "Pre-compiled module is missing: serialport@6.0.5." and the project crashes so I assume this update is crucial. 

I've tried running 't2 restore', then setting up tessel again and all steps work fine until update. I've run update in bash and cmd.exe as suggested here (https://github.com/tessel/t2-cli/issues/1037), but still get the 'No device found in bootloader mode' error. Does anyone have any suggestions as to what I may be missing?

t2 update
INFO Looking for your Tessel...
INFO Connected to tessel.
INFO New firmware version found... 0.2.0
INFO Updating tessel to latest version (0.2.0)...
INFO Downloading files...
INFO Download complete!
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 16.78 MB. This will take 2-4 minutes...
INFO Transfer complete.
INFO Starting OpenWRT update.
INFO Please do not remove power from Tessel.
INFO This process will take at least 2 minutes...
INFO Configuration is saved during update.
INFO Updating firmware (2/2)
ERR! Detected CLI crash Error: No device found in bootloader mode
ERR!     at C:\Users\Allen\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:367:19
ERR!     at new Promise (<anonymous>)
ERR!     at USB.Connection._findBootedDeviceBySerialNumber (C:\Users\Allen\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:351:10)
ERR!     at Timeout.retry [as _onTimeout] (C:\Users\Allen\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:328:12)
ERR!     at ontimeout (timers.js:482:11)
ERR!     at tryOnTimeout (timers.js:317:5)
ERR!     at Timer.listOnTimeout (timers.js:277:5) Error: No device found in bootloader mode
ERR!     at C:\...\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:367:19
ERR!     at new Promise (<anonymous>)
ERR!     at USB.Connection._findBootedDeviceBySerialNumber (C:\Users\Allen\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:351:10)
ERR!     at Timeout.retry [as _onTimeout] (C:\...\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:328:12)
ERR!     at ontimeout (timers.js:482:11)
ERR!     at tryOnTimeout (timers.js:317:5)
ERR!     at Timer.listOnTimeout (timers.js:277:5)
INFO Crash Reported: http://crash-reporter.tessel.io/crashes?fingerprint=0x4d9b0fe994b2c08a
ERR! Error: Polling is not active.

**Comment by allenjwelch** [comment]
Tried changing node version to 10.14.0 since it seems latest firmware uses node 8.11.3. Still received the same error.

**Comment by HipsterBrown** [comment]
@allenjwelch Can you share the program you are trying to run initially?

And you said you already tried [running in cmd.exe not as an administrator](https://github.com/tessel/t2-cli/issues/1037#issuecomment-289209487)? Have you also looked at the getting started instructions here? -> http://tessel.github.io/t2-start/

Do commands like `t2 list` and `t2 version` still work?

**Comment by allenjwelch** [comment]
@HipsterBrown 
Initially I was trying to follow run a simple program using johnny-five:
var Tessel = require("tessel-io");
var five = require("johnny-five");

var board = new five.Board({
  io: new Tessel()
});

board.on("ready", () => {
  var led = new five.Led("a5");
  led.blink(500);
});

But the program will not run with the factory settings of the tessel which are:
C:\Users\Allen>t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-02A37F95B93E.
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.22
INFO t2-firmware: 0.0.12
INFO Node.js: 4.2.1

I was however able to run the "blinky' code from the t2-start guide without an update. 
Each time to attempt to run 't2 update' I get an error. 

All other commands seem to work fine (t2 list, t2 version, t2 restore, etc..).

Do you know if this issue is unique to Windows? Next I was planning on attempting the update off a linux os.

**Comment by allenjwelch** [comment]
update: I've used the command 't2 restore' to revert back to original settings and attempted to update to specific firmware versions in hopes that maybe it was only the latest version that was causing the issue. No luck. Each time the install fails when updating firmware with the same 'No device found in bootloader mode' error.
