### ISSUE TITLE
Set up mDNS on Tessel 2

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#16]
This is required to be able to locate Tessel 2's available on a wireless network.

**Comment by Frijol** [comment]
should this be associated with any command line call?

**Comment by johnnyman727** [comment]
Fixed with https://github.com/tessel/openwrt-tessel/pull/2 and https://github.com/tessel/openwrt-tessel/commit/9521e7efd7996b326e8e229290f0fa81c5744a7d
