### ISSUE TITLE
Sometimes Tessel.getname hangs forever

### ISSUE THREAD

**Issue by jiahuang** [tessel/t2-cli#165]
Found this while working on the test rig code and noticed that sometimes plugging & unplugging tessels doesn't emit the 'tessel' event from seeker.

Looks like `self.connection.exec(commands.getHostname()` hangs forever. I can run the same command on dterm and it returns fine.

**Comment by johnnyman727** [comment]
@jiahuang let me know if this ends up being a dup of #110.

**Comment by johnnyman727** [comment]
Closing this b/c I can't repro.
