### ISSUE TITLE
npm.registry.log not defined

### ISSUE THREAD

**Issue by aramk** [tessel/t2-cli#1654]
This line is causing an issue on Node v8 since npm.registry isn't defined.

https://github.com/tessel/t2-cli/blob/master/lib/init/javascript.js#L128

**Comment by HipsterBrown** [comment]
@aramk I just tested this out on Node version 8.11.3. Not sure why `npm.registry` would not be defined since we have the `npm` package pinned to `v6.4.1`. Could you comment with the error you saw when using the CLI?
