### ISSUE TITLE
We should add a help command

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#173]
At the very least it could output the list of commands, but it would be awesome if someone could write some concise documentation for the different commands.

**Comment by rwaldron** [comment]
https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743

**Comment by johnnyman727** [comment]
Right now the spec on the forums only specifies running `t2 -h` or `t2 --help` but I could see the use of `t2 help`.

**Comment by Frijol** [comment]
:/ this used to work according to the spec (https://github.com/tessel/t2-cli/issues/65) but now it just outputs:

```sh
➜  t2-cli git:(master) t2 -h

Usage: /usr/local/bin/iojs t2 <command>

command     one of: provision, run, push, erase, list, init, wifi, key, rename
```

Somehow this got broken.

**Comment by Frijol** [comment]
nomnom docs for this: https://github.com/harthur/nomnom#usage
