### ISSUE TITLE
t2 list exits with status 1 even on success

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#174]

**Comment by LinusU** [comment]
@johnnyman727 I can't assign myself, should I have access to moderate the issue tracker?

**Comment by johnnyman727** [comment]
@LinusU I just made folks in the "Collaborators" team admins. See if you can assign yourself now?

**Comment by LinusU** [comment]
Nope, still doesn't work :(

**Comment by johnnyman727** [comment]
Okay, it should really actually be fixed now. :)

**Comment by LinusU** [comment]
Now it works :+1:
