### ISSUE TITLE
unable to run tessel 2

### ISSUE THREAD

**Issue by Vendre08** [tessel/t2-cli#1746]
Each time I start the tutorial and type t2 run led.js I start getting ERR! Node version mismatched for USB Drivers. and nothing working as it should.

**Comment by simonpeters** [comment]
Hey, did you manage to fix this?

**Comment by rwaldron** [comment]
The answer is there: 

> Each time I start the tutorial and type t2 run led.js I start getting ERR! Node version mismatched for USB Drivers. and nothing working as it should.

You likely installed `t2-cli` with an older version of node, and have since upgraded. The version of node you're using now does not match the version of node that you had when the usb drivers were first installed.
