### ISSUE TITLE
Suggested rewording for "Connecting to Tessel..." 

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#195]
When running a cli command, there is a displayed message that says "Connecting to Tessel...", however this doesn't accurately describe the operation that's taking place at that moment. `Tessel.get(...)` must first "locate" or "look for" a Tessel to connect to. 

Suggested rewordings: 

- "Locating a Tessel..."
- "Locating your Tessel..."
- "Looking for a Tessel..."
- "Looking for your Tessel..."

**Comment by johnnyman727** [comment]
I'm in favor of option 4: "Looking for your Tessel".

**Comment by Frijol** [comment]
+1 to option 4

**Comment by rwaldron** [comment]
I like #4 too, it's got something of a personal touch it :)

**Comment by dalestone** [comment]
"Looking for your Tessel..." sounds good :+1:

**Comment by johnnyman727** [comment]
Fixed by @chrisbodhi!
