### ISSUE TITLE
error Windows_NT 6.3.9600 using npm link after cloning repository

### ISSUE THREAD

**Issue by dalestone** [tessel/t2-cli#196]
Hi,

I have just cloned the repository and then run the following:

    npm link

but then I encounter this error:

```
19798 error Windows_NT 6.3.9600
19799 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "link"
19800 error node v0.12.4
19801 error npm  v2.10.1
19802 error code ELIFECYCLE
19803 error tessel@0.3.23 postinstall: `tessel install-drivers || true; tessel trademark || true`
19803 error Exit status 1
19804 error Failed at the tessel@0.3.23 postinstall script 'tessel install-drivers || true; tessel trademark || true'.
19804 error This is most likely a problem with the tessel package,
19804 error not with npm itself.
19804 error Tell the author that this fails on your system:
19804 error     tessel install-drivers || true; tessel trademark || true
19804 error You can get their info via:
19804 error     npm owner ls tessel

```

Is there something I am doing incorrectly? Is it maybe an issue with the version of node I am running?

**Comment by rwaldron** [comment]
Hi @dalestone! According to @othiym23, you'll need Administrator privileges (reference: https://github.com/npm/npm/issues/3861#issuecomment-67905700 ). Please confirm. Thanks!

**Comment by dalestone** [comment]
@rwaldron  I can confirm setting permissions to "Full control"  on the node_modules folder worked. Thanks very much!

**Comment by rwaldron** [comment]
If you'd like to contribute, you could add info to the readme that describes what you did :)

**Comment by dalestone** [comment]
@rwaldron Yeah ok, I will write something up and do a pull request.

**Comment by rwaldron** [comment]
@dalestone awesome—thanks!
