### ISSUE TITLE
tessel install-drivers on Linux uses wrong VID/PID

### ISSUE THREAD

**Issue by flaki** [tessel/t2-cli#197]
#### Issue:
The `sudo tessel install-drivers` command puts the outdated VID/PID-s into the udev file:
```
ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="6097", ENV{ID_MM_DEVICE_IGNORE}="1", MODE="0666"
```

#### Fix:
Have it output the correct IDs:
```
ATTRS{idVendor}=="1209", ATTRS{idProduct}=="7551", ENV{ID_MM_DEVICE_IGNORE}="1", MODE="0666"
```

**Comment by johnnyman727** [comment]
Fixed with https://github.com/tessel/t2-cli/pull/416.
