### ISSUE TITLE
Rust language support

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#200]
* [x] Initilizing basic Rust project (squashing and merging https://github.com/tessel/t2-cli/pull/131)
* [x] Detecting project is Rust based (as opposed to JS)
* [x] Compiling and bundling rust code
* [x] Running rust code
* [ ] Module porting to Rust

**Comment by johnnyman727** [comment]
I'm going to close this issue since it's mostly complete and the rest of the to-dos can be found in the [`tessel-rust`](https://github.com/tessel/tessel-rust repo.
