### ISSUE TITLE
Configuration path on different platforms

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#207]
I don't really like things being placed in `~/.tessel/` on OS X, it should be `~/Library/Application Support/Tessel/`. And on windows it's even more problematic.

I'm going to extract out the path-finding logic from [LinusU/node-application-config](https://github.com/LinusU/node-application-config) to a separate module and then we could depend on that one to get the right path.

The only obstacle is to write logic that moves old files if we want a smooth upgrade...

**Comment by rwaldron** [comment]
If I had to guess, the motivation for that location is to have directory hierarchy parity with `~/.ssh/`.

**Comment by LinusU** [comment]
Do you have any feelings towards which one we should choose?

**Comment by LinusU** [comment]
I've created [LinusU/node-application-config-path](https://github.com/LinusU/node-application-config-path) now :)

**Comment by rwaldron** [comment]
I don't, but I can see why it was chosen.

**Comment by LinusU** [comment]
@johnnyman727 Do you have any thoughts on this?

**Comment by johnnyman727** [comment]
I don't have strong feelings about this. My motivation for picking `~/.tessel` was simply because I have a lot of other application folders there (`.aws`, `.heroku`, `.npm`, etc.) so I just assumed that it was the standard. I do have a lot of application folders in the path you propose as well though so I don't think it makes a huge difference.

@tcr or @kevinmehall do you have any feelings about this?

**Comment by rwaldron** [comment]
I didn't have a strong opinion until I took the time to research the intended use of `~/Library/` and its subdirectories. According to [The Library Directory Stores App-Specific Files
](https://developer.apple.com/library/prerelease/mac/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1), I don't think t2-cli should be putting user-specific files in `~/Library/Application Support/`. I have many dot-dirs in my home directory that contain user-specific data (generally some kind of configuration) which was created by and used by a binary (ansible, asciidoc, atom, cordova, dropbox, forever, gem, node-gyp, npm, nvm, nw-gyp, particle (this is a competing SBC), pip, racket, replicator, rvm, ssh, subversion, vim).

**Comment by LinusU** [comment]
What made part you think that you shouldn't put user specific files in `~/Library/Application Support/`?

I understood it as thats where you should put user specific files.

> `Library` in the current home directory—This is the version of the directory you use the most because it is the one that **contains all user-specific files**.

> `Application Support`
> Use this directory to **store all app data files** except those associated with the user’s documents. For example, you might use this directory to store app-created data files, **configuration files**, templates, or other fixed or modifiable resources that are managed by the app.

Emphasis mine

All folders that you mentioned are created by tools that also exists on linux, I have yet to see any tools made specifically for OS X place it's config in a dot-folder. Having dot-folders is an UNIX that has been replaced on OS X by the `Library` folder and on Linux with the XDG Base Directory Specification. This library would adhere to both of those (falling back on dot-folder) and also add support for windows (where I guess it doesn't work at all today since it's specified as `osenv.home() + '/.tessel/id_rsa'`).

**Comment by rwaldron** [comment]
Table 1-3  Key subdirectories of the Library directory 

> Application Support/
> Use this directory to store all app data files except those associated with the user’s documents. For example, you might use this directory to store app-created data files, configuration files, templates, or other fixed or modifiable resources that are managed by the app. An app might use this directory to store a modifiable copy of resources contained initially in the app’s bundle. A game might use this directory to store new levels purchased by the user and downloaded from a server.


I read this as being application (ie. a program that's found in the `/Applications` directory) specific, whereas all of my user installed binaries make dot-dirs in my home directory.

**Comment by johnnyman727** [comment]
Closing this now b/c we have bigger fish to fry and there doesn't seem to be a clear answer.
