### ISSUE TITLE
Set up proper installation

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#21]
Currently, you have to manage a config file in this repo to be able to connect to a Tessel 2 remotely. We should be able to get up and running with Tessel over USB (like sending SSH keys over to the device).

Generate an ssh key for a tessel user and store it in a tessel specific folder (like ~/.tessel on OSX). When a Prime is plugged in via USB, transfer that ssh key to the Tessel under a 'tessel' account.

**Comment by Frijol** [comment]
Expecting this to look like this:

```js
// Trigger when a Tessel 2 is plugged in

// If tessel file doesn't already exist...

  // Make ~/.tessel
  // TODO: what does this need to be on other systems?

  // Generate SSH key

  // Put SSH key for Tessel in that folder

// Put the SSH key from the tessel folder in Tessel's /etc/dropbear/authorized_keys
```

**Comment by johnnyman727** [comment]
I'm not sure we can get a trigger when Tessel 2 is plugged in. For now, we might just have to check if the folder exists when any CLI command is run. @kevinmehall thoughts?

**Comment by kevinmehall** [comment]
It only needs to generate the SSH key the first time you `tessel setup` when it would need to copy it to a device.

**Comment by johnnyman727** [comment]
For reference, these are the commands to change the hostname:

uci set system.@system[0].hostname=MY_HOSTNAME
uci commit system
echo $(uci get system.@system[0].hostname) > /proc/sys/kernel/hostname

**Comment by johnnyman727** [comment]
Closing in favor of #64.
