### ISSUE TITLE
Improper provisioning logic

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#213]
If you have two Tessels, and you provision the first, everything works as expected. However, if you then try to provision the second, the CLI will give a warning that the keys already exist and not provision it.

It should realize the keys already exist and continue to provision the second device.

**Comment by johnnyman727** [comment]
The troublesome code [is here](➜  t2-cli git:(jon-general-cleanup) ✗ t2 provision
WARN Keys already exist. Refusing to overwrite them.).

**Comment by rwaldron** [comment]
Just so I understand better: `t2 provision` should simply use the existing contents of `~/.tessel/` to provision a Tessel?

**Comment by johnnyman727** [comment]
Yep - the first use should generate the keys and subsequent uses should transfer those same keys.
