### ISSUE TITLE
Can't provision Tessels already on LAN

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#214]
If a Tessel is already connected to a LAN (perhaps someone else was using it), and you plug in USB to provision it, the provisioning will fail. This is because the discovery of Tessel prefers LAN devices and there is currently no good way to fetch a USB connection (if it's connected over both).

**Comment by rwaldron** [comment]
Can you write up steps to reproduce—I think I'm missing something. I've provisioned my T2 over my neighbor's wifi and then reprovisioned over mine.

1. `rm -r ~/.tessel`
1. `t2 wifi ...` (neighbor wifi)
1. `t2 provision`
1. SSH to board: ok
1. `t2 wifi ...` (mine)
1. `t2 provision -f` <-- force flag to pave over existing provision data
1. SSH to board: ok

I'm definitely missing something

**Comment by johnnyman727** [comment]
Yeah, my description was not very clear.

1. Plug in an unprovisioned Tessel 2
2. `t2 provision` 
3. `t2 wifi ...` (connect to the same WiFi as your computer)
4. `rm -rf ~/.tessel`
5. `t2 list` (just to confirm that you can find the Tessel over USB and LAN but it gives a warning about needing to be provisioned)
6. `t2 provision` (it tries to do the provisioning over LAN, because operations are faster over SSH, but provisioning is not possible over LAN, only USB)

**Comment by rwaldron** [comment]
Ok, will try this.
