### ISSUE TITLE
t2 provision will throw an unhandled error event for all new users/devices

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#216]
A combination of these commits: 

- https://github.com/tessel/t2-cli/commit/42d8c293c2b4f122e6e12c7a8032e19114832277
- https://github.com/tessel/t2-cli/commit/8a9b67cf7ad27f05b4f287db8f1bd0e4196d01c8 

Has resulted in a bug that allows failures that were previously silent to crash the `t2 provision` process. Before, errors would be suppressed, but now they are emitted and if there is no handler, then the whole process fails. This error should be viewable by users, but only if a `verbose` flag has been explicitly provided. The reason for this suppression is because the `/.tessel/id_rsa` will never exist until the first use and we certainly don't want users seeing "File Doesn't Exist" errors the first time they plug in their new Tessel 2.

**Comment by johnnyman727** [comment]
@rwaldron I can't repro this :/

**Comment by rwaldron** [comment]
Did you delete the `~/.tessel` directory?

**Comment by johnnyman727** [comment]
Yes - it may have been fixed by #221?

**Comment by rwaldron** [comment]
Confirmed
