### ISSUE TITLE
Connected to the same Tessel twice

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#232]
Like so:

```sh
➜  test-community  t2 run gesture.js --name Kelsey
INFO Connecting to Tessel...
INFO Connected to Kelsey over USB
INFO Connected to Kelsey over LAN
INFO Writing gesture.js to RAM on Kelsey (2428.928 kB)...
```

And then it hangs

**Comment by johnnyman727** [comment]
I can reproduce this now!

Just run `t2 update -f --name Frank` (but substitute your T2s name for Frank).

**Comment by johnnyman727** [comment]
This is due to https://github.com/tessel/t2-cli/issues/334. Will close in favor of the other.
