### ISSUE TITLE
t2 provision enhancements

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#234]
Migrating non-critical pieces of the t2 provision spec from https://github.com/tessel/t2-cli/issues/64

* [ ] Should be run automatically
* [ ] `provision --remove`
* [x] Needs `-f` flag for overwriting existing SSH keys

**Comment by johnnyman727** [comment]
@Frijol can we move these to #64? This issue seems redundant? Also, I believe we decided to not have Tessels automatically be provisioned so we can remove that checkbox.
