### ISSUE TITLE
Run `tessel list` to let users specify a tessel if nothing else selected

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#235]
If there is no tessel specified by:
* --name
* an environment variable in the terminal, set as `export TESSEL=Bulbasaur`
* a single tessel connected over USB
* only one tessel visible

run `tessel list` and prompt the user to select.

Moved from https://github.com/tessel/t2-cli/issues/93 to de-prioritize

**Comment by johnnyman727** [comment]
Will be fixed with #348.
