### ISSUE TITLE
JavaScript Code Styling - Newline \n is necessary for individual cli help msg !

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#244]
Because of the *nomnom cli framework* doesn't allow to override the "node" with the .script() method, the only way to create an exact usage info for `--help` is the .usage() method.

Because of the JavaScript Code Styling rules we are forced not to use `\n` so [we are not able to create a acceptable layout.](https://github.com/Student007/t2-cli/commit/eb7346e432dbdf7be5e7a368f9e663ba5bf601a6)

I would suggest to switch off/change the JSCS option [validateQuoteMarks](http://jscs.info/rule/validateQuoteMarks.html) to prevent `Invalid quote mark found` errors for working on console styling. (without this I cannot produce a Travis-CI valid brunch prepared for a pull request)

@Frijol this is related to your point at https://github.com/tessel/t2-cli/issues/173

**Comment by rwaldron** [comment]
I suspect there's a misunderstanding because there should be no issue using \n in any string.

**Comment by Student007** [comment]
@rwaldron yes this is possible :partly_sunny: - It had been a translation misunderstanding and mixing up the word "quote" with "escaping" ... = *short-circuit in my head* :relaxed: 
(yesterday I changed double quotes to single quotes and stop working that day - now I see my fault of implicit guess it would be the escaping what was meant)

`grunt test --force` brought up this errors
```
Running "jscs:all" (jscs) task
Invalid quote mark found at bin/tessel-2.js :
   213 |var functional_msg = '\nGain SSH root access to one of your authorized tessels (menu listing if multiple targets)';
   214 |parser.command('root')
   215 |  .usage(functional_msg + "\n\nUsage: t2 root [-i PATH] [--help]\n\n-i PATH:   Optional targeting a different Private Key \n\n(Note: default target created by \"t2 key generate\" is " + default_id_rsa + ")\n")
----------------------------------^
   216 |  .option('path', {
   217 |    abbr: 'i',
Invalid quote mark found at bin/tessel-2.js :
   213 |var functional_msg = '\nGain SSH root access to one of your authorized tessels (menu listing if multiple targets)';
   214 |parser.command('root')
   215 |  .usage(functional_msg + "\n\nUsage: t2 root [-i PATH] [--help]\n\n-i PATH:   Optional targeting a different Private Key \n\n(Note: default target created by \"t2 key generate\" is " + default_id_rsa + ")\n")
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
   216 |  .option('path', {
   217 |    abbr: 'i',
```

 and also Travis-CI failed some runs (e.g. [this one](https://travis-ci.org/Student007/t2-cli/builds/73689330)). But as you assumed something for sure I misunderstand in general. The [last build](https://travis-ci.org/Student007/t2-cli/builds/73693752) succeeded.

I couldn't understand this confusing behavior (maybe because I was tired).

I think I need some vacation - I will travel to [Legoland](https://www.legolandholidays.de/ibecms/en/booking/package/search.html) :tent: :minibus: for some days  :ferris_wheel: :roller_coaster: to forgot this ...
