### ISSUE TITLE
TODO: No usb controller found on this system.

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#246]
While building a Vagrant box to be clean for testing deployment my self, I stumbled over a thing needs to be fixed sometimes later. Not to forget, I file an issue :smile: 
It happens by using `t2 list`
```
WARNING: No usb controller found on this system.
INFO Searching for nearby Tessels...
/home/vagrant/app/t2-cli-t2-root/lib/usb_connection.js:232
  usb.getDeviceList().forEach(deviceInspector);
     ^
TypeError: Cannot read property 'getDeviceList' of undefined
    at USB.Scanner.start (/home/vagrant/app/t2-cli-t2-root/lib/usb_connection.js:232:6)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

```
It needs a change [here](https://github.com/tessel/t2-cli/blob/master/lib/usb_connection.js#L9-14)
or [here](https://github.com/tessel/t2-cli/blob/master/lib/usb_connection.js#L232). Maybe a simple 

```
if(haveusb){
    usb.getDeviceList().forEach(deviceInspector);
    usb.on('attach', deviceInspector);
  } else {
      console.warn('WARNING: No usb controller found on this system.');

  }
```
is enough  [here](https://github.com/tessel/t2-cli/blob/master/lib/usb_connection.js#L232)?

**Comment by johnnyman727** [comment]
Hmm I thought it should be possible to find USB devices with the VM. @tcr can you comment?

**Comment by Student007** [comment]
@johnnyman727 there is no need for looking into. It will be my own misconfiguration finally. The issue report is only for necessary error handling - there are many silly users like me ;) ...
(but if someone knows the vagrant flag to enable usb ... [this way](https://github.com/jeff1evesque/machine-learning/wiki/Vagrant#usb-integration) didn't work for me - I assume I have used a bad base box - are there any `Vagrantfiles` you use internally for referencing and testing on MacOS, Windows, Linux - would save time ??)

Btw: **The reason I do this is to figure out what error handling is necessary to provide answers to basic cases like no ssh installed (or what ever I will notice by testing on my reference VMs)**. 
Also a note: The `mdns-js` seems to find only your own virtual tessels - not that one are running within other VMs or on other computers - is this known ? I am trying to figure out that last days - but if someone knows more at this point - could save time ;)

**Comment by johnnyman727** [comment]
Thanks, Dan.

The mdns library should be able to find VMs on the network (it does for me), assuming those VMs are also connected to the network. Is your VM running a process called `dns-sd`?
