### ISSUE TITLE
t2 update: Sometimes the hostname changes after update

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#252]
We need to figure out why the hostname changes sometimes after update. Once we know why, we can take steps to set it back to what it was previously.

**Comment by johnnyman727** [comment]
This will likely be a fix in OpenWRT.

**Comment by Frijol** [comment]
hostname = the name of your Tessel, settable via `t2 rename`

**Comment by Frijol** [comment]
is this the same issue? https://github.com/tessel/openwrt-tessel/issues/19

**Comment by johnnyman727** [comment]
Yep!

**Comment by johnnyman727** [comment]
Fixed by @wyze with https://github.com/tessel/t2-cli/pull/733/commits/d5c7b7f8e514d4ab5f286802492c4cc4d1d8d0d1.
