### ISSUE TITLE
t2 update: You need to unplug T2 before it can be detected over USB again

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#255]
I'm really not sure why this might be. @kevinmehall may have an idea. 

@kevinmehall do you need to explicitly take the device out of app mode after flashing it with the bootloader?

**Comment by kevinmehall** [comment]
It should reset into the firmware after update unless it's skipping the last step of the firmware update process. Does the LED continue to blink?

**Comment by johnnyman727** [comment]
No, the LED stops blinking which makes me think that it's back in regular firmware.

It's possible that the SAMD21 is a red herring and it's actually a problem with OpenWRT. When you run `t2 list`, if it finds a device over USB, it requests the hostname from OpenWRT - if it's not booted, then it won't show up (and it currently crashes something on the device so you have to restart it).

**Comment by rwaldron** [comment]
When I did an update with @dtex today, mine kept flashing, but IIRC his stopped.

**Comment by johnnyman727** [comment]
@kevinmehall I believe the issue is that OpenWRT seems to be rebooted after the firmware is updated. If you run `t2 list` just after the update, OpenWRT won't be ready to serve the hostname so it doesn't appear with `t2 list`.

@rwaldron you seem to have uncovered a bug. LMK if you can repro it.

**Comment by johnnyman727** [comment]
Nope - I was incorrect. If T2 is running, then the SAMD21 is put in bootloader mode and updated, the OpenWRT instance is not rebooted. However, I believe the SAMD21 is not able to reconnect to the domain socket.

**Comment by johnnyman727** [comment]
After OpenWRT is updated, it is no longer running the SPI Daemon. If I manually try to get it running again, I get 
```
root@Harold:/# /etc/init.d/spid restart
Failed to connect to ubus
Failed to connect to ubus
```

**Comment by johnnyman727** [comment]
I don't exactly know why, but somehow https://github.com/tessel/t2-cli/commit/3ed1f0b8e92431804f5a1a6aa69a4a068734ee82 fixes this. I realized that OpenWRT wasn't being upgraded properly... somehow that was breaking the usb or spi daemon.
