### ISSUE TITLE
t2 update needs visual indicator

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#263]
More on that to come

**Comment by rwaldron** [comment]
There is now a progress bar

**Comment by johnnyman727** [comment]
@rwaldron I think this is only half complete because there is no progress bar for the upload progress. I have a [WIP PR to do that](https://github.com/tessel/t2-cli/pull/605) but it only works over USB for the issue I described in that PR.

**Comment by rwaldron** [comment]
Dread. I've been avoiding that PR because I don't like the approach at all, I figured that would all shake out in time though ;)

**Comment by johnnyman727** [comment]
I agree and I welcome any new suggestions on how to build it! The one I took seems to be impossible without artificially limited the throughput.
