### ISSUE TITLE
t2 run in module subfolder fails

### ISSUE THREAD

**Issue by sidwarkd** [tessel/t2-cli#266]
If you have an **examples** or **tests** folder in a custom module and try to `t2 run` a file from within that folder you get an error like the following:

```
Error: Cannot find module '/tmp/remote-script/graphics.js'
```

This is because the project is pushed to the T2 and then the T2 tries to run the file from the root of the module directory instead of from the subfolder where it resides. This seems to have been caused by a change in the code around [here](https://github.com/tessel/t2-cli/blob/master/lib/tessel/deploy.js#L221) where `entryPoint` doesn't contain the full path to the file you are trying to run.

**Comment by rwaldron** [comment]
Can you give me an explicit command and file hierarchy command that will fail?

**Comment by johnnyman727** [comment]
I believe his heirarchy was something like
-root
 -index.js
 -examples
   - example.js

And he is running `example.js`. @rwaldron I believe @sidwarkd would like to try to fix it himself.

**Comment by sidwarkd** [comment]
That's right @johnnyman727. I was doing `t2 run` on example.js in your comment and the T2 is trying to run it from the root of the **remote-script** folder instead of **remote-script/examples/**

**Comment by rwaldron** [comment]
Sorry, I missed this thread yesterday, but had already written the patch shortly after assigning the issue to myself :\ 

The fix is straightforward, I was just missing the inclusion of `relpath` when forwarding the script name. Here's the patch in action: 

```
rwaldron at new-host-2 in ~/robotz/tessel-gps-monitor
$ t2 run eg/app.js
INFO Connecting to Tessel...
INFO Connected to bishop over LAN
INFO Writing app.js to RAM on bishop (5.632 kB)...
INFO Deployed.
INFO Running eg/app.js...
Device Running
1440860451269
1440860451888
1440860452410
1440860452915
INFO Stopping script...
rwaldron at new-host-2 in ~/robotz/tessel-gps-monitor
$ t2 push eg/app.js
INFO Connecting to Tessel...
INFO Connected to bishop over LAN
INFO Writing app.js to Flash on bishop (5.632 kB)...
INFO Deployed.
INFO You may now disconnect from the Tessel. Your code will be run whenever Tessel boots up. To remove this code, use `tessel erase`.
INFO Running eg/app.js...
```
