### ISSUE TITLE
t2 run|push <file> -s (single file run/push)

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#272]
When the `-s` is present, only the file is deployed.

- Skips the folder delete
- Skips the folder create

**Comment by Frijol** [comment]
is `-s` standard for this?

**Comment by rwaldron** [comment]
I was told this was the flag used for T1 cli?

**Comment by johnnyman727** [comment]
[Indeed!](https://github.com/tessel/cli/blob/master/bin/tessel-run.js#L73-L77)

**Comment by Frijol** [comment]
cool, just checking!

**Comment by wprater** [comment]
I don't mind taking this on, if @rwaldron isn't.

**Comment by johnnyman727** [comment]
I believe @rwaldron is traveling the globe for a few more days. If you've got time time before then, feel free to steal this one!

**Comment by wprater** [comment]
is there a spec somewhere I can look at?  from v1?

**Comment by johnnyman727** [comment]
@wprater unfortunately, I don't think we have a spec for this command. It was tacked on for the T1 CLI and it has been tacked on for the T2 CLI as well. :/ 

My take is that it takes the path to a single file, places that file in `/tmp/remote-script/FILE` or `/app/FILE` (depending on if deployed with `run` or `push`) and runs that file. I don't think it needs to be any more complicated than that.

**Comment by wprater** [comment]
ok, that's what I figured as well!

**Comment by rwaldron** [comment]
Fixed by https://github.com/tessel/t2-cli/pull/311
