### ISSUE TITLE
update command: progress bar

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#275]
It would be cool if `t2 update` showed a progress bar while downloading files.

**Comment by Frijol** [comment]
from https://github.com/tessel/cli/blob/master/bin/tessel-update.js

```js
        var holdUp = setInterval(function(){
          logs.info("...");
        }, 2000);
```

**Comment by LinusU** [comment]
I was thinking more of something like this: https://github.com/tj/node-progress

**Comment by Frijol** [comment]
yeah, that's even better :P

**Comment by johnnyman727** [comment]
https://github.com/tessel/t2-cli/pull/281
