### ISSUE TITLE
Tessel remote commands: add "run command and give me all output" functionality

### ISSUE THREAD

**Issue by MrNice** [tessel/t2-cli#289]
## The Problem:
We can execute arbitrary shell commands over USB and LAN through SSH, but the ssh interface returns an remote process, which has stdout and stderr event emitters.

This is great for complicated use cases, but it's a bit of a hassle when you just want to run a command to get its stdout output.

```js
return self.connection.exec(commands.command())
  .then(function(rp) {
    var err = '';
    var result = '';

    rp.stderr.on('data', function(d) {
      err += d.toString();
    });
    rp.stdout.on('data', function(d) {
      result += d.toString();
    });

    rp.once('close', function() {
      if (err.length) reject(new Error(err));
      // DO STUFF HERE
    });
  });
```

## A Solution
It would be nice to be able to instead write something like

```js
return self.connection.execOnce(commands.command())
  .then(function(result) {
    // DO STUFF HERE
  })
  .catch(function(err) {
    reject(err);
  });
```

**Comment by johnnyman727** [comment]
Agreed! There are lots of places the code could use this format.

**Comment by wprater** [comment]
I like this approach as well!
