### ISSUE TITLE
t2 run can die with "/tmp/remote-script" not found

### ISSUE THREAD

**Issue by tcr** [tessel/t2-cli#319]
The solution is to wait, but also "killall node" also seems to work, even though it doesn't kill anything!

</armchair debugging>

**Comment by johnnyman727** [comment]
Note: this occurs at least as early as 4c773cf.

**Comment by johnnyman727** [comment]
Another note: fixed by deleting `/tmp/remote-script` on the T2. Note sure why.

**Comment by johnnyman727** [comment]
Yeah, this one is really killer and will be at the top of my to-do list.

**Comment by johnnyman727** [comment]
Fixed with #337.
