### ISSUE TITLE
Can't use the --lan flag with --name

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#323]

**Comment by wprater** [comment]
can a device have the same name on `lan` and `usb`?  I assume so, so this is probably a discovery heuristics issue?

**Comment by Frijol** [comment]
It should have the same name regardless. I think there's something broken in the parsing of `--lan` such that it thinks it requires an argument

**Comment by johnnyman727** [comment]
Actually, it's much simpler than that. If you pass the `--name` flag the `controller` is checking each found Tessel against that name and returns as soon as it finds a match. USB connections are found pretty much immediately because they are hard wired so the `usb` connection is always returned.

**Comment by johnnyman727** [comment]
Dup of #238
