### ISSUE TITLE
board requires reboot after quitting a process with ctrl-c

### ISSUE THREAD

**Issue by ultralame** [tessel/t2-cli#324]
when i try to run my code again 
```
INFO Looking for your Tessel...
WARN No Tessels Found.
```
resolved by rebooting board

**Comment by rwaldron** [comment]
Todo: confirm that this reproducible with the latest cli and firmware

**Comment by johnnyman727** [comment]
Confirmed with my personal Tessel.

**Comment by johnnyman727** [comment]
`git bisect` did not find the culprit :/

**Comment by rwaldron** [comment]
Interesting. I can't reproduce

**Comment by johnnyman727** [comment]
@rwaldron are you on `0.0.4`?

**Comment by rwaldron** [comment]
@johnnyman727 I'm always on latest-master

**Comment by johnnyman727** [comment]
Fixed with #339.
