### ISSUE TITLE
NECESSARY upgrading async (0.9->1.4) causes in failing test

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#331]
As I noted at [async controller.menu](https://github.com/tessel/t2-cli/pull/309) pull request:
> Note: This pull request changes a dependencies version: async needs to be updated from 0.9 to 1.4 due to proper implemented method async.forEachOf what in difference to async.each will provide the arrays key (index) what is necessary to create the menu in the right order.

As you also can see, "All checks have passed" ... but looking into [Travis-CI](https://travis-ci.org/tessel/t2-cli/builds/81197165) the successful run stops at `provision.js unit test` with the following problem:

> `Unhandled rejection TypeError: Cannot read property 'connectionType' of undefined`

While figuring out whats going wrong I added `console.log(tessel)` into affected method `controller.closeTesselConnections`
```
{ exec: [Function],
  end: [Function],
  close: [Function],
  connectionType: 'USB' }
```
I also tried to change `async.each` to `async.forEachOf` and adding an `index` param but this didn't make things better. Same as rewriting the method with replacements like `lanConnection` and inner conditions about `authenticated`.

I am out of capabilities to fix this issue by my own due to skills and knowledge about reasons why things are done like they are done.
HELP :cry: @johnnyman727 @LinusU @rwaldron ... :pray:

**Comment by johnnyman727** [comment]
@Student007 actually, I notice that I'm getting this on master now which is very bad. I don't believe it's related to the `async` upgrade. I will investigate.

**Comment by johnnyman727** [comment]
Weirdly - I can't make a single commit in the history pass its unit tests...

**Comment by Student007** [comment]
@johnnyman727 I would assume the Travis-CI had a flag about conditions to pass tests also in (special) cases failures are causing. But I do not remember at the moment what flag it is and where documented.

**Comment by johnnyman727** [comment]
Fixed by https://github.com/tessel/t2-cli/pull/332.

**Comment by Student007** [comment]
@johnnyman727 cool - thanks :+1:
