### ISSUE TITLE
Unhandled rejection Error: No response from server

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#341]
When `seeker.on('tessel', ....)` is discovering a Tessel and the SSH client didn't got further responses from the found Tessel, there are additional events we have to listen to.
**This issue is hard to be reproduced** but from my point of view this will be prevented by adding new event handlers to `lib/lan_connection.js` `LAN.Connection.prototype.open`

### Error
```
Unhandled rejection Error: No response from server
    at Socket.<anonymous> (/Users/{anonym}/github/t2-cli/node_modules/ssh2/lib/client.js:226:15)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:166:7)
    at TCP.close (net.js:464:12)
```
### Possible solution based on
As [described](https://github.com/mscdex/ssh2#client-events) I added two additional event handlers:

- end() - The socket was disconnected.
- close(< boolean >hadError) - The socket was closed. hadError is set to true if this was due to error.

I am going to prepare a pull request for discussion.

**Comment by Student007** [comment]
@johnnyman727 it seams it is necessary to add removeEventListener at some point. Any idea where to do this the best way ?
(If the covered situation happens multiple times at same seeking process, there will come up a node-memory-leak warning. In my case this happens with masses of Tessel2-VMs ... because I do not own ... yea ... no Tessel2s :smirk_cat: )

**Comment by Student007** [comment]
@johnnyman727 but using this fix within my local work on `t2 select` it is covering the issue #342 successfully :smile:

**Comment by johnnyman727** [comment]
Closing this for now because we haven't seen this in a long time.
