### ISSUE TITLE
T2 CLI does not properly terminate USB transfers

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#346]
Tessel 2 takes a while to boot up. If you run a command while it is still booting, it messes up the USB comms.

**Comment by rwaldron** [comment]
I think there needs to be some way of checking that it's ready to go. I'm not sure how though.

**Comment by Frijol** [comment]
@johnnyman727 was using the existence of USB comms from the Tessel to determine whether it's ready. Does that work in this case?

**Comment by johnnyman727** [comment]
Yes, I was working in [this PR](https://github.com/tessel/t2-cli/pull/291/files). It does work in theory but then the `usb` module seems to crash each subsequent time it's used...

**Comment by tcr** [comment]
See #386 for a fix.

**Comment by Frijol** [comment]
:raised_hands:
