### ISSUE TITLE
Changing and having different keys for different Tessels

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#347]
As discussed [here](https://github.com/tessel/t2-cli/pull/307/files#r40217947) it should be possible to create multiple Keys for different Tessels and also exchange the Keys (like changing the password).
This PR https://github.com/tessel/t2-cli/pull/330 could be a starting point.

**Comment by johnnyman727** [comment]
I'm curious how other developers use SSH keys. I generally just use one pair to log in to all sorts of other computers. Do others use them differently?

My main concern with this is its effect on the user experience. I would guess a majority of users will only have one Tessel and a majority of those who don't will not even consider making more SSH keys. In fact, most may not even know that we're using SSH keys! @Student007 did you have an idea for how users would create unique keys for every Tessel?

**Comment by Student007** [comment]
> @Student007 did you have an idea for how users would create unique keys for every Tessel?

Thanks for asking - YES:

For example you are using the Tessel 2 as base for a real product you will sell on different customers in different numbers. For security service technicians will use different private keys for different customers.

Another example is the case an employee is working as a service technician went out of the company. In that case all keys of customers have to be exchanged. As well es after hacked and stolen service computers/keys.

If I would know you sell a bunch of products to multiple customers based on Tessel2. I would hack you by buying also one and take the key. That way I would be able to hack all Tessel2 based Products you are selling (your service key is the same everywhere).

**Comment by Student007** [comment]
@johnnyman727 
> I generally just use one pair to log in to all sorts of other computers. Do others use them differently?

In that case you also could use `~/.ssh/id_rsa` as default key.

**Comment by johnnyman727** [comment]
> For example you are using the Tessel 2 as base for a real product you will sell on different customers in different numbers. For security service technicians will use different private keys for different customers.

I think in an enterprise deployment, companies would probably want to use a tool that lets them service devices even off the local network. They would need something a little more robust like what particle.io is building rather than the CLI (which is mostly for development).

> If I would know you sell a bunch of products to multiple customers based on Tessel2. I would hack you by buying also one and take the key. That way I would be able to hack all Tessel2 based Products you are selling (your service key is the same everywhere).

I'm not sure I follow you here. If you can get physical access to any device, we should assume it has been compromised. And, again, I don't think the CLI is something that folks will be using for large scale deployment.

**Comment by Student007** [comment]
>  And, again, I don't think the CLI is something that folks will be using for large scale deployment. 

@johnnyman727 I planed this.

> [...] something a little more robust like what particle.io is building rather than the CLI (which is mostly for development)

I didn't work with particle.io but I think you cannot use a Tessel with their tools - isn't it ?
And as you said you have in mind to design the CLI to be portable easily - so the requirements need to be robust like tools other target own at this moment.

**Comment by johnnyman727** [comment]
@Student007 you can't currently use particle.io with Tessel but I spoke with them about it briefly and they said it shouldn't be difficult.

I'm not expert on actual fleet deployment tools but I don't think our SSH model will work very well. If you have thousands or tens of thousands of devices, you don't want to maintain an equivalent number of SSH keys... 

@Student007 do you know how other services handle provisioning devices and authentication at that scale?

**Comment by Student007** [comment]
@johnnyman727
 > @Student007 do you know how other services handle provisioning devices and authentication at that scale?

No, I didn't take a look on concurring solutions. But there are hard facts on business internals when I learned my first job in an industrial company. I was responsible (trainee) for remote support and due to leaving employees we need to changes keys. Companies like banks e.g. required us to have different key pairs than other customers.
Of cause the most interesting solution would be to have different keys on a single Tessel - but I know about limits of the firmware and space - so I didn't talk about this (as well as being `root` all the time ...)
This would be acceptable if it would be possible to change keys (not remotely - for security - the USB provisioning solution is a modern one. If I know it right, some solutions also base on serial number for an additional security element).
>  If you have thousands or tens of thousands of devices, you don't want to maintain an equivalent number of SSH keys... 

that is not the point. It is more to be able to have several keys for groups of devices. And it isn't useful to require support personnel to provide a single login-user on their desk to help a customer.

Of cause in practice I assume there where cloud solutions for holding keys and right management for accessing this keys. But the ability to use different keys by a single support technician would be necessary.
`t2 root --ip http://myRelayStationTheTesselisSendingItsIpto.Extranet123.net --key https://mySecureCloudserver.Intranet/customerName/Group1Key/id_rsa?u=sup1&p=1234LOL`

`t2 version --ip http://myRelayStationTheTesselisSendingItsIpto.Extranet123.net --key https://mySecureCloudserver.Intranet/customerName/Group1Key/id_rsa?u=sup1&p=1234LOL`

As you know I am currently working on a `t2 select` command. Since you closed a related issue I am thinking about to re-create the concept based on working directories if wanted. Means: By default you would use `~/.tessel/id_rsa` but if you like to have a *project based key* (e.g. `t2 generate key --projectdir ~/myProject/`) it would be stored within `<projectdirectory>/.tessel/id_rsa`.

In general it looks like it wouldn't be much magic to expand the current key-concept. There is an open task to make the TESSEL_AUTH_KEY accessible global. And working on this, it also would be possible to make it possible to use different keys (by simple storing multiple keys and having a option `--key`)..
Finally the need is:
- use `t2 provision` a second time (I think it is currently possible - maybe a shorthand could generate and provision: `t2 flipkey --name`)
- use `t2 generate key` with different targets (`--dir` `--name` or default to `~/.tessel/id_rsa`)
- make it possible to use `--key` within all commands

**Comment by johnnyman727** [comment]
@Student007 I understand your use case of wanting several authorized people to have access to a Tessel, but I don't think the CLI is a good way to do that because the CLI only operates on local area networks.

The architecture you'll want to use if you have a bunch of devices in the field that you need to deploy to has three components:

[ TESSEL] <--------> [CLOUD] <------------> [DEVELOPER]

The server (or cloud) will be responsible for authorization and handling keys. The Tessel simply connects to the cloud and waits for new commands to be issued to it.

I think unless we have that sort of architecture, it doesn't make sense to worry about in the field deployment or various keys for different users. The CLI is much more suited to building the prototype of a device in front of you.

**Comment by Student007** [comment]
> [...] several authorized people to have access to a Tessel [...]

@johnnyman727 sorry if my wording has been confusing - no I do not want to have different keys for a single Tessel. I want multiple Tessels with group of keys (e.g.)

-> Tessel-A ==> Key1
-> Tessel-B ==> Key1
-> Tessel-C ==> Key2
-> Tessel-D ==> Key2

User1 => Key1,Key2  (.... this case needs a solution)
User2 => Key2
User3 => Key1


> The CLI is much more suited to building the prototype of a device in front of you.

@johnnyman727 I think it should be possible to change keys and work with different Tessels (and separate keys) as a single user account also for prototyping. There are several **use case (e.g. giving classes and training) where you like to use a remote key, import keys or share temporary keys.**

**At least it should be possible to use `--key URL` or `--key PATH` with all commands.**

Doing this the hole CLI has to be cleaned up. After this it wouldn't be a big thing to add scale abilities. And this is something could be done by sub-projects if it isn't wanted by the team.

**Comment by johnnyman727** [comment]
@Student007 I'm not sure why users in classes and trainings wouldn't just use a single key. In the case of development the key isn't used so more for security as for keeping track of which Tessel you are working on when there are other people hacking in the same room.

In any case, I think it's reasonable to have the `--key PATH` option because that will have the smallest impact on user experience and only those really looking for the option will find it. :)

**Comment by Student007** [comment]
> In any case, I think it's reasonable to have the --key PATH option because that will have the smallest impact on user experience and only those really looking for the option will find it. :)

:smile_cat: :+1:

**Comment by johnnyman727** [comment]
Fixed with #432.
