### ISSUE TITLE
Swallowing Errors on Deploy

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#352]
We are [currently swallowing errors](https://github.com/tessel/t2-cli/blob/85b113867bb3d71e0682d6e71fe66485b365ca16/lib/tessel/deploy.js#L93-L96) for a few commands during the deploy sequence. The original motivation was because we tell the service that runs tessel apps on boot (if they were `push`ed) to stop even if they were never started. If it was not started, the command will return an error (`Command failed: not found'). 

We should refactor this section and catch any unexpected errors.

**Comment by rwaldron** [comment]
Can you write up a "steps to reproduce", or some similar way to observe? Thanks!

**Comment by johnnyman727** [comment]
@rwaldron I'm not sure that this is actually causing any issues at the moment - it's just concerning that it could cause issues in the future. Perhaps the best way to check is to just log any errors that are received in the code linked in my first comment and see if any of them are something other than `Command failed: not found`.

**Comment by rwaldron** [comment]
Ok, I'll take a look

**Comment by johnnyman727** [comment]
This was resolved by @rwaldron in https://github.com/tessel/t2-cli/commit/24fdd7d28c58f5183c900f5f8258dcd76dcc57a0.
