### ISSUE TITLE
tessel push no longer works

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#353]
We need to transfer over `/resources/start_node_script.sh` into `/app/start` and then change the permission with `chmod +x /app/start`. This used to [to be working](https://github.com/tessel/t2-cli/blob/3a85992a0ec6837e321c168ea07b81688eb21b07/lib/tessel/deploy.js#L174-L199) but we must have lost it in refactoring. 

NEED MORE TESTS.

**Comment by rwaldron** [comment]
Maybe I'm missing something here? With t2-cli/master, I just did `t2 push` on two different T2s and both work exactly as expected. I can unplug them, hook up battery and they run. 

I took screenshots of my process for the second one that I deployed to: 

![](https://i.gyazo.com/10899334548fef1731c2f9e370acdb69.png)

At this line: 

```
root@bishop:/app# ls
```

I've moved over to another terminal and ran this: 

![](https://i.gyazo.com/24e569a481ba082467d04e2ff8d725d9.png)


(Note that I _did_ have to ssh to both boards to manually delete the previous contents, but that's unrelated)

**Comment by johnnyman727** [comment]
@rwaldron interesting! So to be clear, you *did* delete the entire contents of `/app` first? I wonder if maybe the start script just never got deleted (broken until https://github.com/tessel/t2-cli/pull/354 lands) and so you didn't see this problem. 

But, taking a look at the source, [it appears the code is still in here](https://github.com/tessel/t2-cli/blob/85b113867bb3d71e0682d6e71fe66485b365ca16/lib/tessel/deploy.js#L279-L283)... I'll have to investigate further on my T2.

**Comment by johnnyman727** [comment]
@rwaldron you're right! It was an issue with my branch that was fixing `erase`. But I will try to add a test to catch the problem (it deployed to `/appstart` instead of `/app/start`).
