### ISSUE TITLE
Tessel name with space

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#364]
> maybe this is a `t2-vm` or a `t2-firmware` issue ??

I am currently working with `t2-vm` and cloned the VMs with new MAC-Addresses for all networking devices.
Caused by this way to create multiple Tessels (because I do not own at least one Tessel 2 .... for ... now) ... The base Name of the Tessel is currently `Tessel-08002727EC88` but while cloning and booting clones it gets a new name like `Tessel-08002727EC88 (2)` and `Tessel-08002727EC88 (3)` ...

When using e.g. `t2 version` the `Tessel.get`method and `heuristics`is trying to find the right Tessel to use but is only finding `Tessel-08002727EC88` ...
This couldn't be right, because there are only 
- Tessel-08002727EC88
- Tessel-08002727EC88 (2)
- Tessel-08002727EC88 (3)

The original `Tessel-08002727EC88` isn't up while testing.

Also if there is a wall to create Tessels with same name or spaces in name, this should be handled.

Btw; `t2 list` shows 
```
INFO Searching for nearby Tessels...
	Tessel-08002727EC88	LAN	
	Tessel-08002727EC88	LAN	
	Tessel-08002727EC88	LAN	
INFO Multiple Tessels found.
INFO Set default Tessel with environment variable (e.g. 'export TESSEL=bulbasaur') or use the --name flag.
```
The Tessels itself each have their own IP, fullname and host (reproduce this by adding `console.log('opts: ', opts);` to `lib/lan_connections.js` method `LAN.Connection`):
```
opts:  { addresses: [ '192.168.178.64' ],
  query: [ '_tessel._tcp.local' ],
  type: 
   [ { name: 'tessel',
       protocol: 'tcp',
       subtypes: [],
       description: undefined } ],
  port: 22,
  fullname: 'Tessel-08002727EC88 (2)._tessel._tcp.local',
  txt: [ '' ],
  host: 'Tessel-08002727EC88-2.local',
  interfaceIndex: 0,
  networkInterface: 'en1' }
opts:  { addresses: [ '192.168.178.65' ],
  query: [ '_tessel._tcp.local' ],
  type: 
   [ { name: 'tessel',
       protocol: 'tcp',
       subtypes: [],
       description: undefined } ],
  port: 22,
  fullname: 'Tessel-08002727EC88 (3)._tessel._tcp.local',
  txt: [ '' ],
  host: 'Tessel-08002727EC88-3.local',
  interfaceIndex: 0,
  networkInterface: 'en1' }
opts:  { addresses: [ '192.168.178.63' ],
  query: [ '_tessel._tcp.local' ],
  type: 
   [ { name: 'tessel',
       protocol: 'tcp',
       subtypes: [],
       description: undefined } ],
  port: 22,
  fullname: 'Tessel-08002727EC88._tessel._tcp.local',
  txt: [ '' ],
  host: 'Tessel-08002727EC88.local',
  interfaceIndex: 0,
  networkInterface: 'en1' }
	Tessel-08002727EC88	LAN	
	Tessel-08002727EC88	LAN	
	Tessel-08002727EC88	LAN	
INFO Multiple Tessels found.
INFO Set default Tessel with environment variable (e.g. 'export TESSEL=bulbasaur') or use the --name flag.
```

**Comment by Student007** [comment]
@tcr @johnnyman727  did you change the VM http://storage.googleapis.com/tessel-builds/ccc157a289db14791ee7250733a0b7b5fb9c06c8.vdi last days ?

I couldn't see any changes on `t2 vm`so this would be my only idea why the behavior changes when cloning with VirtualBox. Before I could clone with new MAC for each network device and current state of VM and got a new Tessel-Name (based on MAC I think) and a new IP from the DHCP-Server. Now I only get new IPs but same names with what causes in this issue in general.

**Comment by rwaldron** [comment]
Does `system.@system[0].hostname` accept hostnames with spaces?

**Comment by johnnyman727** [comment]
@rwaldron no, it doesn't. If you run a command like `t2 rename Bob Barker` it will interpret Bob has the new name and Barker as another argument that just doesn't get used. 

If you try to do `t2 rename "Bob Barker", the CLI will yell at you because it's not a valid Unix host name.

@Student007 Essentially you gave all of your Tessels the same name.

**Comment by Student007** [comment]
> If you run a command like t2 rename Bob Barker it will interpret Bob has the new name and Barker as another argument that just doesn't get used

> [...] Essentially you gave all of your Tessels the same name.

@johnnyman727 I close this issue due to it is a minor task. The purpose had been simply to get your eyes on it for the case it is something hadn't been seen until now.
