### ISSUE TITLE
Should `Tessel.get` have a conditional auth filter ?

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#368]
Some internal commands would like to show only authorized Tessels if multiple devices are discovered and the menu comes up. At the moment it will show also not authorized Tessels.

**Comment by johnnyman727** [comment]
@Student007 great find! I didn't realize that if you have only an unauthorized Tessel, it will be the one returned by `Tessel.get`. 

We should make `authorized` be an optional [parameter passed to the seeker](https://github.com/tessel/t2-cli/blob/8848a73c1c0b0d27c2aa291e8390c2e0e4200b36/lib/controller.js#L113-L120). Then check that flag [in the seeker after attempting to open](https://github.com/tessel/t2-cli/blob/8848a73c1c0b0d27c2aa291e8390c2e0e4200b36/lib/discover.js#L52). If the Tessel is not authorized, do not emit it.

@Student007 are you up for this patch?

**Comment by Student007** [comment]
@johnnyman727 yes I can do this.
