### ISSUE TITLE
t2 provision doesn't find valid USB provision target

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#375]
`controller.js` specifies that the Tessel Seeker [should only find return unauthorized Tessels](https://github.com/tessel/t2-cli/blob/dac8975498b3d39e7e9646d805502b2ee1a4b107/lib/controller.js#L507) but USB connections are authorized by definition. 

After a USB connection is opened it his [this if block](https://github.com/tessel/t2-cli/blob/dac8975498b3d39e7e9646d805502b2ee1a4b107/lib/discover.js#L55) which blocks it from becoming provisioned (`opts.authorized` is false and `tessel.connection.authorized` is true).

**Comment by johnnyman727** [comment]
@Student007 do you want to take a stab at fixing this regression and adding tests to make sure we don't miss it again?

**Comment by Student007** [comment]
@johnnyman727 yes - assign it to **me** ... ahm .. @Student007 ... I mean :laughing:

**Comment by rwaldron** [comment]
I didn't realize this was the same bug as I found earlier today when @flaki and I were trying to connect in a LAN-less world. https://github.com/tessel/t2-cli/pull/376

**Comment by Student007** [comment]
@rwaldron I am blocked to reproduce until I received my test equipment - but thanks for cross linking. Shipping to Europe takes 1-2 weeks.

**Comment by johnnyman727** [comment]
@rwaldron beat you to it, @Student007!

Fixed with #376.

**Comment by Student007** [comment]
:pray: @rwaldron :pray: .... I will pay back when I've positioned my army of Tessel 2 testing equipment another day :laughing: :+1:
