### ISSUE TITLE
Single USB-connected Tessel should be selected when "--usb" specified

### ISSUE THREAD

**Issue by flaki** [tessel/t2-cli#379]
Now when I only have several Tessels around, but only a single one connected over USB:
```
flaki$ t2 list
INFO Searching for nearby Tessels...
	tessel-europe	USB	
	hip-hardware	LAN	(USB connect and run `tessel provision` to authorize)
	JonnyTessel	LAN	(USB connect and run `tessel provision` to authorize)
	navi	LAN	(USB connect and run `tessel provision` to authorize)
INFO Multiple Tessels found.
INFO Set default Tessel with environment variable (e.g. 'export TESSEL=bulbasaur') or use the --name flag.
```

...specifying `--usb` returns a "Multiple possible Tessel connections found." error, while in reality there is only a single one connected via USB:
```
flaki$ t2 wifi --usb -l
INFO Looking for your Tessel...
INFO Please specify a Tessel by name [--name <tessel name>]
WARN Multiple possible Tessel connections found.
```

**Comment by johnnyman727** [comment]
This is definitely an issue with the [runHeuristics](https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L374) function that `controller.js` uses to figure out which Tessel you want.

**Comment by johnnyman727** [comment]
Fixed with https://github.com/tessel/t2-cli/pull/360.
