### ISSUE TITLE
Reduce 'push' or 'run' bundle size by following 'require' paths

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/t2-cli#383]
At the moment, running and pushing code to Tessel 2 takes the `entryPoint` file and everything in `node_modules/` to build a tarball to send over. [Reference](https://github.com/tessel/t2-cli/blob/dac8975498b3d39e7e9646d805502b2ee1a4b107/lib/tessel/deploy.js#L171)

I'm aware of the [`.tesselignore`](https://github.com/tessel/t2-cli/blob/dac8975498b3d39e7e9646d805502b2ee1a4b107/lib/tessel/deploy.js#L214) file, which is used to blacklist files from being used in tarball. That workflow would require developers to modify that file every time they install a new module and blacklist everything they don't use in their program. 

It would be nice to have an option to pass into the bundle process for only following the `require` paths of the `entryPoint`, similar to how Browserify works, to create a bundle of only the code needed for the program to run. It could be a flag in the cli, i.e. `t2 run index.js --follow-requires` or `t2 run index.js --slim`.

**Comment by rwaldron** [comment]
Notes: 

- This **must** respect .tesselignore lists. 
- This **must** gracefully handle compiled modules
