### ISSUE TITLE
Document '.tesselignore' dotfile

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/t2-cli#384]
Similar to `npm`, the `t2-cli` looks for a `.tesselignore` dotfile to use in blacklisting files being sent over to Tessel 2 when pushing/running code. [Reference](https://github.com/tessel/t2-cli/blob/dac8975498b3d39e7e9646d805502b2ee1a4b107/lib/tessel/deploy.js#L214)

This should be documented in the Tessel docs, probably under the [Tessel 2 CLI page](https://tessel.io/docs/cli).

**Comment by Frijol** [comment]
Moved to https://github.com/tessel/t2-docs/issues/32
