### ISSUE TITLE
t2 update: sometimes the wifi credentials are wiped

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#391]

**Comment by kevinmehall** [comment]
Just wifi credentials, or the entire overlay?  Parts of the overlay get archived to RAM while `sysupgrade` writes the kernel/squashfs and formats a new JFFS2 overlay partion.

**Comment by johnnyman727** [comment]
@kevinmehall it's unclear and inconsistent. In the case of wiping the password, I've seen it only wipe the key and not the ssid. It also sometimes wipes the username and sometimes doesn't.

**Comment by johnnyman727** [comment]
I haven't seen this in a long time and I think it may have been due to improper updating. Closing until it's reproducible (or at least re-encountered).
