### ISSUE TITLE
Add -s (security) flag to t2 wifi

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#393]
Per spec:

`>  -s <security>:   security protocol to connect with (i.e. WEP, WPA, PSK)`

*moved from https://github.com/tessel/t2-cli/issues/82*

**Comment by Frijol** [comment]
Looks like some of the setup for this is already in place, just not fully implemented: in lib/tessel/commands.js:

```js
module.exports.setNetworkEncryption = function(encryption) {
  return ['uci', 'set', 'wireless.@wifi-iface[0].encryption=' + encryption];
};
```

**Comment by rwaldron** [comment]
@HipsterBrown same here!
