### ISSUE TITLE
Faster Operations for "low throughput" commands

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#406]
I have a suggestion for making it faster to use Tessel and I'd love to hear other's thoughts on it. I used Tessel 1 recently and was impressed at how fast each command was (`t2 wifi`, etc.) and I thought it was a shame that T2 can be so slow because we spend 5 seconds (by default) "finding" your Tessel. The thought process behind this was that finding a LAN connection will be faster than USB which is true for deploying code bundles. But for simple commands with very small transactions like `rename`, `wifi`, `provision`, `erase` (pretty much everything but `run` and `push`), we might as well just use a USB connection if it exists because we'll default to that Tessel anyway.

**In essence, I'm suggesting a class of "simple commands" in which a USB connection will be selected right away, thus saving almost 5 seconds each time.**

**Comment by Frijol** [comment]
> I used Tessel 1 recently and was impressed at how fast each command was

hahaha

I like this idea but we would need to be careful about messaging to the user; it's already fairly confusing from the user perspective what's going on with USB vs LAN connections, and this would make the automatic selection seem even more stochastic

**Comment by johnnyman727** [comment]
> I like this idea but we would need to be careful about messaging to the user; it's already fairly confusing from the user perspective what's going on with USB vs LAN connections, and this would make the automatic selection seem even more stochastic

Agreed! Perhaps we should not print out the connection method selected when we run operations?

**Comment by tcr** [comment]
I was going to propose we actually make `--lan` NOT the default. Might take a lot more discussion in person, as well as fixing the USB transfer speeds, but I think this makes sense for most of our usecases.

**Comment by johnnyman727** [comment]
@tcr I agree that `-usb` by default would be great if we can get the speed up but I'm not sure how much room for improvement there really is.

**Comment by MrNice** [comment]
@johnnyman727 Where are the notes on what's going on during a deployment?

Intuitively, it doesn't make sense for wireless operations to be faster than wired ones. And also, wireless deployment didn't work easily when I tried a month ago.

I wonder if there's a solution that looks similar to `sudo dd rdisk` - straight copying bytes over in order.

![img_20151027_101219](https://cloud.githubusercontent.com/assets/2587335/10766178/74392a68-7c93-11e5-9abc-6dd263f79714.jpg)

**Comment by MrNice** [comment]
But to fix the problem now, I think we should default to USB and add a temporary console.warn that says "Warning: USB deployment is very slow, please use WLAN deployment if possible until we've fixed this"

**Comment by johnnyman727** [comment]
@MrNice the technical overview is [here](https://github.com/tessel/onboarding/blob/master/T2-TECHNICAL-OVERVIEW.md#system-architecture) and it describes how code gets transferred over.

Basically, the CLI sends bash commands through the coprocessor into a daemon on OpenWRT. There is overhead involved with every packet because we need control over process lifecycle and process stream backpressure (ie we can't pipe data faster than the daemon can process it).

A `dd rdisk` type solution might be possible but it would definitely take a different architecture than what we have (not that that's a bad thing!).
