### ISSUE TITLE
Hanging on "Looking for your Tessel"

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#408]
Since `0.0.5` I've noticed hanging on the discovery process occasionally.

```
➜  t2-cli t2 update
INFO Looking for your Tessel...
^C
```

**Comment by Frijol** [comment]
dup of https://github.com/tessel/t2-cli/issues/407 but yours is more specific

**Comment by johnnyman727** [comment]
This is a dup of #271.
