### ISSUE TITLE
tessel list can show two of the same Tessel using mDNS

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#41]
Currently, I am picking up two instances of the same Tessel when running `tessel list`. The objects returned by the `mdns-js` library look like this (where the only difference is the `networkInterface` and `interfaceIndex` fields:
```
update { addresses: [ '172.20.10.16' ],
  query: [ '_tessel._tcp.local' ],
  type:
   [ { name: 'tessel',
       protocol: 'tcp',
       subtypes: [],
       description: undefined } ],
  port: 22,
  fullname: 't2._tessel._tcp.local',
  txt: [ '' ],
  host: 't2.local',
  interfaceIndex: 0,
  networkInterface: 'en0' }


update { addresses: [ '172.20.10.16' ],
  query: [ '_tessel._tcp.local' ],
  type:
   [ { name: 'tessel',
       protocol: 'tcp',
       subtypes: [],
       description: undefined } ],
  port: 22,
  fullname: 't2._tessel._tcp.local',
  txt: [ '' ],
  host: 't2.local',
  interfaceIndex: 1,
  networkInterface: 'en4' }
```

I'm not sure exactly what those fields indicate and whether or not this is an issue with the mdns implementation on the T2 or should just be accounted for in the CLI.

**Comment by HarleyKwyn** [comment]
I believe I fixed this already with: https://github.com/tessel/t2-cli/blob/master/lib/lan_connection.js#L131

 Are you still running into this?

**Comment by johnnyman727** [comment]
No, you fixed it.
