### ISSUE TITLE
Creating slim bundle excludes files used by `fs`

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#423]
I'm not sure how we want to deal with this but I'm curious to get @rwaldron and @HipsterBrown's thoughts in particular.

The use case I was running into was the ambient module. It has a .hex file that Node reads in and flashes to the attiny on the module if the firmware is out of date. When using the `--slim` option, that .hex file is not included in the bundle and the update can't complete.

Do we need to go through, scan every file for `fs` operations and include any of those files?

**Comment by LinusU** [comment]
There is a preprocessor for browserify available which converts all `fs.readFileSync` to inlined data, that could be used to fix _some_ cases, probably this one in particular.

**Comment by johnnyman727** [comment]
@LinusU good to know! Do you know why it only handled `readFileSync` operations?

**Comment by HipsterBrown** [comment]
That will be a tricky problem to solve because not every `readFileSync` is for project files, meaning it's doing file operations on the Tessel. There is the option of having a `.tesselinclude` file for explicitly declaring other files to include with the slim bundle.

**Comment by johnnyman727** [comment]
@HipsterBrown what's the use case for reading a file operation on a file outside of the project? I think we can make it super unlikely by adding functionalities to the `tessel` module that folks might want to do using the OpenWRT filesystem (like `tesse.setWiFiCredentials` or `tessel.setAP`.

**Comment by HipsterBrown** [comment]
@johnnyman727 I was doing it a lot to develop this feature because I couldn't access the system through `ssh` or `dterm` on El Capitan. But I suppose that's a unique use case and I used `child_process.exec` more than `fs`.

**Comment by LinusU** [comment]
@johnnyman727 Here is the module: https://github.com/substack/brfs

I don't know exactly, although I think that is probably enough for most use cases.

It only works with paths that can be resolved at compile time though.

**Comment by johnnyman727** [comment]
@HipsterBrown sounds good. Why couldn't you access through `ssh` and `dterm`?

@LinusU it looks like that module can also grab `fs.readFile` calls. It's too bad it's missing `fs.createReadStream` though.

**Comment by HipsterBrown** [comment]
@johnnyman727 For `dterm` it was probably a compatibility issue with the latest Mac OS X because it was fine on another Mac running Yosemite. For `ssh` I think it was a weird `lan` discovery issue.

**Comment by johnnyman727** [comment]
@HipsterBrown hmm interesting. @nodebotanist mentioned having to add a baudrate to get it to connect properly: ```dterm /dev/tty.usbmodem1411 115200`. Maybe try that?

I've seen LAN discovery issues on enterprise networks. I wrote up [a debugging walkthrough](https://github.com/tessel/t2-docs/blob/jon-usb-debug/debugging/lan_discovery.md) if it's still plaguing you.

**Comment by rwaldron** [comment]
I actually missed this until now, thanks for the ping @johnnyman727

**Comment by rwaldron** [comment]
@LinusU @johnnyman727 I really don't want to get stuck with any more magical browserify things, especially ones that don't allow _all_ code to work as expected.

**Comment by rwaldron** [comment]
#423 will address this by allowing end programs to specify glob patterns for file inclusion _outside_ of the bundle file. (Note that it's a good thing we held fast on keeping both --slim and --full a tarred directory).

**Comment by rwaldron** [comment]
This is resolved: 8cf1f8d795bbdce3ecc45bde826fe8b7ff5f00d4
