### ISSUE TITLE
The package.json requirement is strange in practice. 

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#426]
I'm creating tutorials for Johnny-Five + Tessel and as I go along, the package.json requirement is becoming increasingly albatross-like: every example insists on this strange step that's totally unnecessary when a file name is provided.

The requirement should only be enforced when the `run` or `push` command is given a directory—as this is the only time that some additional lookup might be necessary to figure out the "main" program file.

**Comment by LinusU** [comment]
I thought we fixed this recently? #284, marked as fixed by #311.

But it seems to require a `--single` flag though.

**Comment by rwaldron** [comment]
@LinusU I was hoping to figure out a way to do it implicitly, while satisfying all of the semantics in that thread. After spending a couple of hours with it, I don't think it's going to happen—which is ok, because this is not a pressing matter.

**Comment by LinusU** [comment]
Yeah, I agree, I would have loved to do it implicitly. Unfortunately, I came to the same conclusion as you...

**Comment by johnnyman727** [comment]
I agree that it can be burdensome but with the options of either `t2 init` or the `-s` flag, I think it's as good as it's going to get. :/
