### ISSUE TITLE
Occasionally, no existing remote Tessels are logged with `tessel list`

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#44]

**Comment by HarleyKwyn** [comment]
Can you think of a way to reproduce this? There's already a flag that allows you to set a time out if you consistently run into this issue.

**Comment by johnnyman727** [comment]
I don't have a reliable way to reproduce this besides just running `t2 list` enough times.

**Comment by johnnyman727** [comment]
This seems to be a timeout issue. Will look into it.

**Comment by johnnyman727** [comment]
I think this wasn't an mDNS issue as much of an logging issue. It seems to have been fixed with #102. Closing for now.
