### ISSUE TITLE
Remove 'generating slim build' from deploy output

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#440]
Now that `--slim` is the default, it's a little strange to print out 'generating slim build' when you deploy. It seems like we should just print 'deploying full project` if the `--full` flag is provided.

Here is what it looks like now:
```
➜  ambient-attx4 git:(master) ✗ t2 run examples/ambient.js
INFO Looking for your Tessel...
INFO Connected to Frank over USB
INFO Generating slim build.
INFO Writing project to RAM on Frank (24.064 kB)...
INFO Deployed.
INFO Running bundled project...
```

**Comment by rwaldron** [comment]
Resolved https://github.com/tessel/t2-cli/commit/c7e7c2e0dce8c50ec0f40ff325611862ec419f40
