### ISSUE TITLE
`-s` flag no longer works

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#442]
You can no longer deploy a single file with the `-s` flag. I received this error:
```
➜  spi-test  t2 run spi.js -s
INFO Looking for your Tessel...
INFO Connected to Frank over USB
WARN Invalid project directory
```

To recreate, make a new directory and place a single file in it. Then run `t2 run FILE_NAME -s`.

**Comment by rwaldron** [comment]
That error is produced when the _target_ directory doesn't have a `package.json` file.

**Comment by johnnyman727** [comment]
No, I don't but my understanding of -s is that it wouldn't matter whether or not you have a package.json.

**Comment by rwaldron** [comment]
Well, looking back through the relevant discussions, I'd judge the outcome as vague at best... 

- https://github.com/tessel/t2-cli/issues/426
- https://github.com/tessel/t2-cli/issues/284


But looking at it for a third time now, I think I have an idea of how to make this work with minimal changes.

**Comment by johnnyman727** [comment]
:+1: Fair enough!
