### ISSUE TITLE
CLI not able to make SSH connection to provisioned VM

### ISSUE THREAD

**Issue by Drizej** [tessel/t2-cli#443]
I am running the t2-vm and am able to connect to the VM via an ssh call, but when running "t2 list" it reports that the Virtual Tessel is not provisioned.  Here is the output from t2 list:

when running this command: DEBUG=discovery:lan t2 list --timeout 30
INFO Searching for nearby Tessels...
  discovery:lan Device found: +0ms Tessel-080027F7DA27._tessel._tcp.local
key: /Users/andrzej/.tessel/id_rsa
  discovery:lan Device open error: +27s Tessel-080027F7DA27.local { [Error: Timed out while waiting for handshake] level: 'client-timeout' }
	Tessel-080027F7DA27	LAN	(USB connect and run `t2 provision` to authorize)

**Comment by rwaldron** [comment]
Are you using t2-cli from an npm install or from the repo?

**Comment by huseyinkozan** [comment]
Disabling the ufw at ubuntu fixes, but allowing mdns is not. I couldnt find a proper solution in my case.

**Comment by johnnyman727** [comment]
I'm closing this because I don't think it's anything we can fix from the CLI (seems to be a firewall issue on the VM).
