### ISSUE TITLE
Linux install still not working

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#447]
Installed CLI from master on a Linux machine, `t2 list` did nothing (and resolved in under a second), `sudo t2 install-drivers` returns command not found.

What is the expected interaction?

cc @johnnyman727

**Comment by johnnyman727** [comment]
@Frijol My guess is that the CLI installed with npm, rather than from master because we haven't published since the `install-drivers` function was released. Can you confirm?

**Comment by Frijol** [comment]
tried installing both ways, this was from github

**Comment by johnnyman727** [comment]
@flaki can you confirm?

**Comment by flaki** [comment]
I'm travelling and don't have my Linux machine handy at the moment unfortunately. :(
I'll make sure to have a look at this on Monday as I get home!

**Comment by asez73** [comment]
Hello,

I face this situation after having upgraded quite a lot of things on Ubuntu 14.04 LTS:


`12568 (2016-04-09 12:20:46)  alain@alain-Vostro-3500 ~ $sudo npm install -g t2-cli
/home/alain/.npm-global/bin/t2 -> /home/alain/.npm-global/lib/node_modules/t2-cli/bin/tessel-2.js

> usb@1.1.1 install /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/alain/.node-gyp/4.4.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/.node-gyp"
make: entrant dans le répertoire « /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/build »
make: *** Pas de règle pour fabriquer la cible « ../.node-gyp/4.4.2/include/node/common.gypi », nécessaire pour « Makefile ». Arrêt.
make: quittant le répertoire « /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-85-generic
gyp ERR! command "/usr/bin/nodejs" "/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/src/binding"
gyp ERR! cwd /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.13.0-85-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb
node-pre-gyp ERR! node -v v4.4.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.26
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/src/binding' (1)
/home/alain/.npm-global/lib
└── (empty)

npm WARN In usb@1.1.1 replacing bundled version of node-pre-gyp with node-pre-gyp@0.6.26
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "-g" "t2-cli"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! usb@1.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usb@1.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs usb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls usb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alain/npm-debug.log
npm ERR! code 1
12569 (2016-04-09 12:21:51)  alain@alain-Vostro-3500 ~ $npm ls usb
/home/alain
└── usb@1.1.2 
`

Any idea????

**Comment by rwaldron** [comment]
All of the errors are permissions related problems, which aren't issues that t2-cli can fix :(

Can you double check all of those permissions—then make sure you're running commands accordingly

**Comment by asez73** [comment]
Hello, thanks for reading me!
So I did something like this, and it shown even more errors...
The question is: Why should I become and npm/nodejs install guru?

12617 (2016-04-10 05:53:06)  alain@alain-Vostro-3500 ~ $sudo bash
[sudo] password for alain: 
12616 (2016-04-10 07:49:46)  root@alain-Vostro-3500 ~ $npm -v
3.8.6
12617 (2016-04-10 07:49:52)  root@alain-Vostro-3500 ~ $node -v
v4.4.2
12618 (2016-04-10 07:49:56)  root@alain-Vostro-3500 ~ $nodejs -v
v4.4.2
12619 (2016-04-10 07:50:02)  root@alain-Vostro-3500 ~ $npm install t2-cli -g
npm WARN skippingAction Module is inside a symlinked module: not running remove abbrev@1.0.7 node_modules/t2-cli/node_modules/abbrev
npm WARN skippingAction Module is inside a symlinked module: not running remove affirmative@0.1.1 node_modules/t2-cli/node_modules/affirmative
npm WARN skippingAction Module is inside a symlinked module: not running remove amdefine@1.0.0 node_modules/t2-cli/node_modules/amdefine
npm WARN skippingAction Module is inside a symlinked module: not running remove ansi-escapes@1.3.0 node_modules/t2-cli/node_modules/ansi-escapes
npm WARN skippingAction Module is inside a symlinked module: not running remove ansi-wrap@0.1.0 node_modules/t2-cli/node_modules/ansi-wrap
npm WARN skippingAction Module is inside a symlinked module: not running remove ansi-white@0.1.1 node_modules/t2-cli/node_modules/ansi-white
npm WARN skippingAction Module is inside a symlinked module: not running remove ansi-underline@0.1.1 node_modules/t2-cli/node_modules/ansi-underline
n

**Comment by asez73** [comment]
And now, as root user, after having:
a - wiped out nodejs, node-legacy, npm
b - reinstall nodejs from nodejs.org download
c - relinked npm and nodejs to the resulting binary files
d - tried this and failed:
12733 (2016-04-10 09:28:32)  root@alain-Vostro-3500 ~/Téléchargements $npm install t2-cli -g
npm WARN engine mdns-js@0.4.0: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"4.4.2","npm":"2.15.0"})
-
> usb@1.1.2 install /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

make: entrant dans le répertoire « /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/build »
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
  AR(target) Release/obj.target/usb.a
  COPY Release/usb.a
  CXX(target) Release/obj.target/usb_bindings/src/node_usb.o
  CXX(target) Release/obj.target/usb_bindings/src/device.o
  CXX(target) Release/obj.target/usb_bindings/src/transfer.o
  SOLINK_MODULE(target) Release/obj.target/usb_bindings.node
  COPY Release/usb_bindings.node
  COPY /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/src/binding/usb_bindings.node
  TOUCH Release/obj.target/action_after_build.stamp
make: quittant le répertoire « /home/alain/.npm-global/lib/node_modules/t2-cli/node_modules/usb/build »
/home/alain/.npm-global/bin/t2 -> /home/alain/.npm-global/lib/node_modules/t2-cli/bin/tessel-2.js

> t2-cli@0.0.16 postinstall /home/alain/.npm-global/lib/node_modules/t2-cli
> t2 install-drivers || true

*** Error in `node': free(): invalid pointer: 0x000000000326e1ef ***
Aborted (core dumped)
t2-cli@0.0.16 /home/alain/.npm-global/lib/node_modules/t2-cli
├── bindings@1.2.1
├── usb-daemon-parser@0.0.2
├── url-join@0.0.1
├── shell-escape@0.2.0
├── async@1.5.2
├── fs-temp@1.0.0
├── progress@1.1.8
├── common-tags@0.0.1
├── semver@5.1.0
├── sprintf-js@1.0.3
├── colors@1.1.2
├── osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.1)
├── stream-to-buffer@0.1.0 (stream-to@0.2.2)
├── debug@2.2.0 (ms@0.7.1)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4)
├── minimatch@3.0.0 (brace-expansion@1.1.3)
├── nomnom@1.8.1 (underscore@1.6.0, chalk@0.4.0)
├── acorn@3.0.4
├── promzard@0.3.0 (read@1.0.7)
├── tar-stream@1.5.1 (bl@1.1.2, xtend@4.0.1, end-of-stream@1.1.0, readable-stream@2.0.6)
├── tar@2.2.1 (inherits@2.0.1, block-stream@0.0.8)
├── sshpk@1.7.4 (assert-plus@0.2.0, jsbn@0.1.0, ecc-jsbn@0.1.1, tweetnacl@0.14.3, asn1@0.2.3, jodid25519@1.0.2, dashdash@1.13.0)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.10)
├── fstream@1.0.8 (inherits@2.0.1, graceful-fs@4.1.3, mkdirp@0.5.1, rimraf@2.5.2)
├── ssh2@0.4.15 (readable-stream@1.0.33, ssh2-streams@0.0.23)
├── fs-extra@0.26.7 (path-is-absolute@1.0.0, klaw@1.1.3, jsonfile@2.2.3, graceful-fs@4.1.3, rimraf@2.5.2)
├── uglify-js@2.6.2 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.3, yargs@3.10.0)
├── request@2.70.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, form-data@1.0.0-rc4, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, combined-stream@1.0.5, mime-types@2.1.10, aws4@1.3.2, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── mdns-js@0.4.0 (semver@4.3.6, mdns-js-packet@0.1.12)
├── t2-project@0.1.0 (builtins@1.0.3, glob@6.0.4, resolve@1.1.7, array-includes@3.0.2, module-deps@4.0.5)
├── node-rsa@0.2.30 (asn1@0.2.3, lodash@3.3.0)
├── inquirer@0.8.5 (ansi-regex@1.1.1, figures@1.5.0, through@2.3.8, cli-width@1.1.1, readline2@0.1.1, chalk@1.1.3, lodash@3.10.1, rx@2.5.3)
├── npm@2.15.3
└── usb@1.1.2 (nan@2.2.1)

**Comment by kevinmehall** [comment]
`user "root" does not have permission to access the dev dir "/home/alain/.node-gyp/4.4.2` permissions issue is https://github.com/tessel/t2-cli/issues/414

**Comment by RameshRM** [comment]
Similar problems, 

1. `nodejs 4.2`

Errors : 
```
npm WARN engine mdns-js@0.4.0: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"4.4.2","npm":"2.15.0"})
/
> usb@1.1.1 install /usr/lib/node_modules/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:15:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/t2-cli/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.16.0-50-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/t2-cli/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/t2-cli/node_modules/usb
node-pre-gyp ERR! node -v v4.4.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/t2-cli/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm ERR! Linux 3.16.0-50-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "t2-cli"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! usb@1.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usb@1.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs usb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls usb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pran/npm-debug.log

```

**Comment by asez73** [comment]
Hi @kevinmehall , thank you.
I no more have a permission problem but:
 "*** Error in `node': free(): invalid pointer: 0x000000000326e1ef ***
Aborted (core dumped)".
Although I am doing everything, installs of npm and nodejs included as root.
Actually, nodejs 4.4.2 and npm seem to be OK with my config. However I doubt about this.
I did manually installed :

- nodejs and npm 4.4.2 from nodejs.org with ln -s in order to get ndejs, node and npm as provided by nodejs.org,
- usb which is now 1.1.2 with npm
- rimraf and mdns-js from npm also, they had been desinstalled when I removed npm via apt-get which was required as nodejs 4.4.2 did not tolerate default ubuntu 14.04 npm...

Now, your link is certainly worth to spend some more time on it.

**Comment by huseyinkozan** [comment]
Hi,

Works on Ubuntu 14.04, npm 3.8.3, and node v5.10.1 using this command :

```bash
sudo /opt/node/bin/node /opt/node/lib/node_modules/t2-cli/bin/tessel-2.js install-drivers
```

And this udev rule file:

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="7551", ENV{ID_MM_DEVICE_IGNORE}="1", MODE="0666", GROUP="plugdev"
```

Reload udev rule :

```bash
sudo udevadm control --reload-rules
```

**Comment by rifotu** [comment]
hey Huseyin!
great job! thanks a lot

**Comment by juanmanavarro** [comment]
@huseyinkozan what is and where is the _udev rule file_?

**Comment by huseyinkozan** [comment]
@juanmanavarro Sorry. Here it is :
```bash
sudo nano /etc/udev/rules.d/85-tessel.rules
```

**Comment by huseyinkozan** [comment]
@juanmanavarro Sorry. Here it is :
```bash
sudo nano /etc/udev/rules.d/85-tessel.rules
```

**Comment by greyvugrin** [comment]
@huseyinkozan and all - I had node installed with nvm and ended up having to do the following to get it working:
`sudo /home/MY_USERNAME/.nvm/versions/node/v6.2.0/bin/node /home/MY_USERNAME/.nvm/versions/node/v6.2.0/lib/node_modules/t2-cli/bin/tessel-2.js install-drivers`

Hope this helps someone else out in the future. Thanks!

**Comment by rwaldron** [comment]
@greyvugrin 

> `/home/MY_USERNAME/.nvm/versions/node/v6.2.0/...`

Please note that t2-cli expects the Node.js LTS release, which is the 4.x.x range.

**Comment by greyvugrin** [comment]
@rwaldron noted, thanks for the heads up!

**Comment by johnnyman727** [comment]
I'm going to close this issue as it's not really a problem with the CLI. `t2 install-drivers` was fixed and more verbose instructions (that work around `sudo` issues) were posted on the Start experience: https://github.com/tessel/t2-start/pull/120/. Most users are able to install the CLI on Linux without problems any when issues do arise, they are usually on a VM or Chromebook or some other unique setup that we can handle on a case by case basis.

**Comment by shreyas-satish** [comment]
Had this issue while using nvm on Debian Linux. Got around this by adding the rule manually as described in https://github.com/tessel/t2-cli/issues/447#issuecomment-209966327.
