### ISSUE TITLE
CLI errors out on any command if no key in ~/.tessel

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#455]
Reproduction:
* Remove any existing `~/.tessel` folder
* Run `t2 list` (or any CLI command)

Error:
```
➜  t2-cli git:(jon-root) ✗ t2 list
ERR! Error: ENOENT: no such file or directory, stat '/Users/Jon/.tessel/id_rsa'
```

**Comment by johnnyman727** [comment]
Workaround: run `t2 key generate`.

**Comment by rwaldron** [comment]
To whoever takes this: t2-cli should just print what @johnnyman727 wrote :)

**Comment by johnnyman727** [comment]
@rwaldron I think it should `t2 list` should run as usual (because it will report any unauthorized Tessels and to run `t2 provision` and other commands can just not search for LAN Tessels.

**Comment by rwaldron** [comment]
@johnnyman727 ah, yeah that makes sense.
