### ISSUE TITLE
Restoring lost options creates file naming conflict with t2 push semantics

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#460]
In order to avoid overwriting project files, `t2 run <file>` and `t2 push <file>` create a file called `__tessel_program__.js` to push to the device. The `run` path doesn't care what the end file is called, because it controls the start of the program. The `push` path uses the push script, which looks like: 

```
#!/bin/sh
cd /app
exec node .
```

To fix this, that script needs to be modified if the `entryPoint` is anything but `index.js`

**Comment by johnnyman727** [comment]
Actually, this was going to be necessary anyway, because once we get to using other languages, we'll have to modify that last line of the script to be, for example, `exec ./EXECUTABLE_NAME` or `exec python FILENAME`.

**Comment by rwaldron** [comment]
Ok, I have the fix written for this case, just making tests now

**Comment by johnnyman727** [comment]
:+1:
