### ISSUE TITLE
Access Point mode breaks mDNS discovery somehow

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#464]
After using `t2 ap -n SSID -p PASS`, I can see the network being created, but I can no longer detect the Tessel using `t2 list`. Can we have it connected to the network and serving a network at the same time?

Also, is there a way to turn `ap` off so I can connect it to the network like usual?

@HipsterBrown

**Comment by rwaldron** [comment]
Don't you have to connect to that AP network? When I made an AP, I connected my machine to the newly created network and it worked fine.

**Comment by rwaldron** [comment]
`t2 ap off`

https://github.com/tessel/t2-cli/pull/405#issuecomment-157184061

**Comment by johnnyman727** [comment]
I confirmed that once I connect to the Access Point network, I'm able to discover it over LAN again. And `t2 ap off` does work correctly, thanks @rwaldron!

I think people may be confused, as I was, that they can no longer deploy over LAN to the Tessel once the access point is created. I was under the impression that it would stay on my network and just make a new one. @HipsterBrown is there a way to do that? Otherwise, we may want to print something that advises them to connect to the new network.

**Comment by HipsterBrown** [comment]
@johnnyman727 When starting work on the `ap` command, I asked about the implications of running an access point while connected to a network, [reference](https://github.com/tessel/t2-cli/issues/87#issuecomment-151177133), and was informed that it should be possible to stay connected, [reference](https://github.com/tessel/t2-cli/issues/87#issuecomment-151178383). 

> The only limitation is that all the networks joined or created have to be on the same channel.

That may be what's happening when you spin up an access point and Tessel drops LAN.

**Comment by johnnyman727** [comment]
I think @kevinmehall was just saying that you can have a "station" network and an ap network happening at the same time. We might have to get a little more clever to get Tessel advertising mDNS on the correct network.

I tried adding 
```
option channel 11 // Also tried 7
```
to both interfaces on `/etc/config/wireless` and then running `/etc/init.d/network restart` but it didn't seem to change anything.

**Comment by HipsterBrown** [comment]
@johnnyman727 Try running `wifi` after as well to restart the `wireless` process, if you haven't already.

**Comment by johnnyman727** [comment]
I think `/etc/init.d/network restart` calls that internally but I called it manually as well just to be sure with the same results.

**Comment by johnnyman727** [comment]
Closing because this was due to my own misunderstanding of how `ap` works.
