### ISSUE TITLE
Decide which version of Node.js to target

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#470]
As noted in #467 the code currently doesn't work because we are using template strings which isn't available in Node.js < 4 (I don't know about iojs). On the other hand, there are a lot of features in Node 4.x that we aren't taking advantage of.

I think that we should take a decision on which version to target, and then use all the new features available on that version.

The largest benefit would be fat-arrow functions which would eliminate the need for `self = this` sprinkled all over the code. It would also eliminate most uses of `.bind(...)`.

Me and @Student007 had a small discussion about it here: https://github.com/tessel/t2-cli/pull/466#discussion_r45955570

*(note that this is the version of Node that the CLI should run on, it has nothing to do with code on the actual tessel)*

**edit:**

Expected outcome:

- [ ] Add `'use_strict'` at the top of files (this is needed for next step)
- [ ] Switch all `var` to `const` and `let`
- [ ] Stop using `self = this` and `.bind(...)` in favour of `=>`
- [ ] Use template literals in favour of `+`-ing together strings
- [ ] Use `class` and `extend` keyword for making classes (instead of the cumbersome `function`, `prototype = Object.create`, `prototype.x = _`)
- [x] Use the builtin `Promise` (~~maybe we already are?~~ indeed :+1:)
- [ ] Mark a minimum `engine` in the `package.json` (e.g. `>4.0.0`, which is the current LTS)

**Comment by rwaldron** [comment]
Node.js 4.2.x should be the minimum, as I said in the other thread: managing multiple versions is trivial with nvm.

**Comment by LinusU** [comment]
As said in #467, 0.12 is only in LTS mode until the end of the year, which is very soon. Me and @rwaldron therefor think that we should target Node 4.x and newer.

I think that we should go thru the codebase with the following fixes:
- [ ] Add `'use_strict'` at the top of files (this is needed for next step)
- [ ] Switch all `var` to `const` and `let`
- [ ] Stop using `self = this` and `.bind(...)` in favour of `=>`
- [ ] Use template literals in favour of `+`-ing together strings
- [ ] Use `class` and `extend` keyword for making classes (instead of the cumbersome `function`, `prototype = Object.create`, `prototype.x = _`)
- [ ] Use the builtin `Promise` (maybe we already are?)

I would love to help out with this!

**Comment by Student007** [comment]
@johnnyman727 @LinusU @rwaldron 
I belief the impact would be very big so it is reasonable to think about it is necessary to do this with a major version number (s0 from 0.X.x to 1.0.0).
I think we should prepare this and teach each other during next weeks (I mean it could be a really bad idea to rewrite contributed code without teaching the original or involved authors).
@Frijol Doing this changes is also a project risk factor because the number of potential new contributors will go down (maybe). The answer to this risk is to make it a chance - maybe it would be a good pitch for "this week in Tessel".
@LinusU Maybe it helps to write a very short code snipped which will make it reasonable for ES5 coders. I mean something like this (for example):
[ ] switch `var` to `const` and `let`  (this is good for clean [use of block scoping](http://www.es6fiddle.net/ihj0ixvs/))
(**pattern**: [task] - ([benefit] link to example))

maybe @flaki would be also an expert could help to do this - he is a good author I think. 

I don't know where and who - but I remember about a discussion why `prototype` is still better than `class` (I have no time to review this and argument at this moment) - I mean this is because of deeper inheritance ?! Maybe someone could make a es6fiddle about to show it ? :smile: 

So long my two cents ...

**Comment by LinusU** [comment]
> I belief the impact would be very big so it is reasonable to think about it is necessary to do this with a major version number (s0 from 0.X.x to 1.0.0).

I really don't think that. It should *only* be a **patch** release since we aren't changing any of the visible api. Also, as a user I would be very confused by a sudden major release when seemingly nothing has been changed.

> I think we should prepare this and teach each other during next weeks (I mean it could be a really bad idea to rewrite contributed code without teaching the original or involved authors).

We're not really rewriting that much code though, these are very small changes which mostly is just "sugar", it makes the code look nicer.

> Doing this changes is also a project risk factor because the number of potential new contributors will go down (maybe). The answer to this risk is to make it a chance - maybe it would be a good pitch for "this week in Tessel".

I really don't think that this is true at all. ES6 is not a new language, and we'll only be using a subset of it. There really only is 4 new features, and it's just sugar. I actually don't think that anyone at all would be scared of contributing just because of this.

> Maybe it helps to write a very short code snipped which will make it reasonable for ES5 coders. I mean something like this (for example)

That could be a very good idea, we should also see what's already available :+1: 

> I don't know where and who - but I remember about a discussion why prototype is still better than class (I have no time to review this and argument at this moment) - I mean this is because of deeper inheritance ?! Maybe someone could make a es6fiddle about to show it ? :smile:

I haven't heard this but the `prototype` will still be used. As I said, this is just syntactic sugar that makes it easier to read and easier to write.

-----

They way I see it there are two approaches, we can either 1) update the files as we make other changes, or 2) I'll take a day (which is night for you guys) to just churn thru every file and update it.

**Comment by rwaldron** [comment]
Pre-1.0.0 isn't bound to any particular semver rules, as specified by #4 of semver ;)

**Comment by rwaldron** [comment]
Also, the changes we make _shouldn't_ break the code, since they should absolutely abide by the existing tests

**Comment by Student007** [comment]
I really don't think that this is true at all. ES6 is not a new language [...]

It feels like that for a lot people are not familiar with the discussions lead to the new feature. And this is the majority of people. But we could sell this as a chance to train ES6 by contributing.

    That could be a very good idea, we should also see what's already available :+1: 

:+1: but it should be simplified - most of the tutorials and snippets I know are either to large or incomplete. I remember there was a ES6 multiple choice test somewhere.

    Also, the changes we make shouldn't break the code, 
    since they should absolutely abide by the existing tests

:+1: 
My vote by the condition we use it to teach the web similar I suggested within a this week in Tessel ...

**Comment by dtex** [comment]
> As said in #467, 0.12 is only in LTS mode until the end of the year

0.12.x is in LTS until April of 2017 but I believe targeting >=4.x is perfectly reasonable.

**Comment by LinusU** [comment]
@dtex Not according to [their latest blogpost](https://nodejs.org/en/blog/release/v0.12.8/)

> According to the new LTS plan for the Node.js project, v0.12 will continue as LTS until the end of 2015 at which point it will switch to Maintenance and continue as such until the end of 2016 when support will cease.

**Comment by flaki** [comment]
Well my 2 cents is that we should most definitely aim to ship the official Tessel 2 builds with the latest LTS versions of node (that probably means 4.2 LTS  for the initial release), maybe on the long term we could provide a beta/nightly channel which might include more recent versions of the node runtime.

**Comment by johnnyman727** [comment]
@LinusU is the expected outcome of this issue that we mark a specific version in the `engine` field of the package.json?

**Comment by LinusU** [comment]
@johnnyman727 That and going thru the code to take advantage of the newer features that this brings us. As outlined in this comment: https://github.com/tessel/t2-cli/issues/470#issuecomment-160171309

I'll add a checklist to the actual issue now :)

**Comment by rwaldron** [comment]
Consensus is 4.2.1—thanks everyone!
