### ISSUE TITLE
First use of `t2 ap`, if over USB, will fail

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#475]
I updated a fresh T2 up to `0.0.6`. Note that the wireless config files (related to `t2 ap`) won't actually be overwritten by OpenWRT going from (sub `0.0.6`, when we add the functionality, to `0.0.6`) so you'd have to [manually reset them to their original default state](https://github.com/tessel/openwrt-tessel/tree/f64d0046313bcd6855e37a999213bfb90f75a03e/files/etc/config) if you've already used `t2 ap`).

Running `t2 ap -n SSID -p PASS` results in a failure if it's run over USB:
```
➜  ambient-attx4 git:(jon-t2-compat) ✗ t2 ap -n Frank_Net -p Frank_Pass --usb
INFO Looking for your Tessel...
INFO Connected to Tessel-02A3E843B7A8.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error upon remote process exit: 1
    at USBProcess.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/usb/usb_process.js:56:26)
    at USBProcess.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at USBProcess.emit (events.js:169:7)
    at Parser.<anonymous> (/Users/Jon/Work/technical/t2-cli/lib/usb/usb_daemon.js:127:14)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/Users/Jon/Work/technical/t2-cli/node_modules/usb-daemon-parser/index.js:152:16)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Readable.push (_stream_readable.js:110:10)
```

The reason is because the CLI attempts to fetch the [SSID of the access point network](https://github.com/tessel/t2-cli/blob/master/lib/tessel/access-point.js#L130) which, since this is a fresh install, doesn't exist yet. If you run the command on T2 itself, you'll see that it emits an error message and the error code is non-zero:
```
root@Tessel-02A3E843B7A8:~# uci get wireless.@wi
fi-iface[1].ssid
uci: Entry not found

root@Tessel-02A3E843B7A8:~# $?
-ash: 1: not found
```

The USB Process that's running the command [notices the exit code of 1, interprets it as an error](https://github.com/tessel/t2-cli/blob/master/lib/usb/usb_process.js#L54-L570) and because there is nothing there to catch it, the error is thrown and process is aborted.

The question here is how the USBProcess *should* handle an error. I'm not convinced just emitting an error is the right way to go.

Also, the Access Point logic will need to check for a non-existent SSID.

**Comment by HipsterBrown** [comment]
> The question here is how the USBProcess should handle an error. I'm not convinced just emitting an error is the right way to go.

So could this be more of an issue with the USBProcess than the `ap` setup? I can still look into this, just wondering where to narrow down the search.

**Comment by johnnyman727** [comment]
@HipsterBrown after thinking about this for a bit, I think the `usb_connection` behavior should be as similar to the `lan_connection` as possible. That way, we abstract the physical channel as much as possible.

I've started a PR [here](https://github.com/tessel/t2-cli/pull/489/files).

It should work with this change but I haven't tested it yet.

**Comment by HipsterBrown** [comment]
@johnnyman727 Awesome. I'll try it out tonight.

**Comment by johnnyman727** [comment]
@HipsterBrown did you get a chance to try this out?

**Comment by HipsterBrown** [comment]
Not yet. I will be trying it out this week though.
