### ISSUE TITLE
New tessel 2 needs to be provisioned

### ISSUE THREAD

**Issue by jasonmartens** [tessel/t2-cli#478]
Tessel 2 start page (http://tessel.github.io/t2-start/) instructs you to list your tessel, however the first time I got the error: 
```Jasons-Mac-mini:local elliott$ t2 list
ERR! Error: ENOENT: no such file or directory, stat '/Users/elliott/.tessel/id_rsa'
```
After running ```t2 provision``` I could list it (thanks @tcr!)

**Comment by johnnyman727** [comment]
Thanks @jasonmartens!

This was fixed a few days ago with https://github.com/tessel/t2-cli/pull/469 and will be out with the next npm release (schedule for Wednesday).
