### ISSUE TITLE
Remove '--slimPath' flag

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/t2-cli#480]
As discussed [here](https://github.com/tessel/t2-docs/pull/36#discussion-diff-46782882), there's no real use case for giving the user an option to change the name of the temporary, compiled bundle run on Tessel after deployment. We can hardcode "__tessel_program__.js" into [`deploy.js`](https://github.com/tessel/t2-cli/blob/master/lib/tessel/deploy.js) without the user ever having to worry about it.

**Comment by rwaldron** [comment]
So, I just hit an issue that's forced me to remove this, so it will be closed with the next deploy update

**Comment by rwaldron** [comment]
Resolved https://github.com/tessel/t2-cli/commit/c7e7c2e0dce8c50ec0f40ff325611862ec419f40
