### ISSUE TITLE
Investigate why it takes ~5 seconds to load CLI `require`s

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#490]
It takes a super long time before `"Looking for your Tessel"` gets printed after running any command (about 3-5 seconds for me on OSX10). We should look into why this takes so long and how to reduce that time.

**Comment by flaki** [comment]
Oh yes I was wondering why running any `t2` command were this unnervingly slow.

**Comment by johnnyman727** [comment]
@flaki I did a preliminary investigation and it looks like the 3-5 seconds are actually just processing all the `require` statements. We might want to implement a way to more lazily load those dependencies.

**Comment by rwaldron** [comment]
I'm immediately suspicious of third party modules.

A quick survey turns up a few we could do without (whether they are causing issues, I can't say, but unnecessary none-the-less):

- bluebird 
  - just use built in Promise
- debug 
  - used inconsistently anyway?
- osenv 
  - getting "home" is done in deploy.js without a 3rd party module, we can refactor and reuse our own utility
- async 
  - as used here: https://github.com/tessel/t2-cli/blob/master/lib/tessel/provision.js#L109 can be replaced by two promises that use `Promise.all([a, b]).then` 
  - here: https://github.com/tessel/t2-cli/blob/master/lib/usb/usb_daemon.js#L56 I'm not sure why that's async.eachSeries? 
  - here: https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L350 again, not sure why?
- lib/tessel/deploy.js
  - can be lazy required
- lodash
  - can likely be optimized (needs further investigation)

**Comment by rwaldron** [comment]
Addressing various fixes should be done in different PRs, vs one huge change set

**Comment by LinusU** [comment]
> bluebird
> just use built in Promise

Yes please

> async
> here: https://github.com/tessel/t2-cli/blob/master/lib/usb/usb_daemon.js#L56 I'm not sure why that's async.eachSeries?

It seems like the `.closeProcess` is asynchronous and that all processes should be closed after each other. There is however a big problem with this code since it will never return if `(proc)` ever is falsely, since the then the callback will never fire.

> here: https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L350 again, not sure why?

This could be much easier written using `Promise.all`

> lodash
> can likely be optimized (needs further investigation)

lodash provides all functions as separate modules, this make nodejs only load the actual things that it needs instead of everything. (e.g. `_.pick` is available as the package `lodash.pick`, imported with `const pick = require('lodash.pick')`)

**Comment by rwaldron** [comment]
> It seems like the .closeProcess is asynchronous and that all processes should be closed after each other. 

Ah, I think I understand now. I'll ping you if I have more Qs.

> This could be much easier written using Promise.all

Great!

**Comment by rwaldron** [comment]
I've been collecting require times with the following patch: 

```patch
From 43c68a63ffa5dfff9b1f7431c1412e0b4e07d4c2 Mon Sep 17 00:00:00 2001
From: Rick Waldron <waldron.rick@gmail.com>
Date: Mon, 8 Feb 2016 14:05:06 -0500
Subject: [PATCH] Capture timing

---
 bin/tessel-2.js | 20 ++++++++++++++++++++
 1 file changed, 20 insertions(+)

diff --git a/bin/tessel-2.js b/bin/tessel-2.js
index 3c07401..1728e3d 100755
--- a/bin/tessel-2.js
+++ b/bin/tessel-2.js
@@ -1,5 +1,7 @@
 #!/usr/bin/env node
 
+var time = process.hrtime();
+
 // System Objects
 var path = require('path');
 
@@ -13,6 +15,24 @@ var key = require('../lib/key');
 var logs = require('../lib/logs');
 var drivers = require('./tessel-install-drivers');
 
+
+var diff = process.hrtime(time);
+var ns = (diff[0] * 1e9 + diff[1]);
+var ms = ns / 1e6;
+var ss = ns / 1e9;
+
+console.log("Resolved in: ");
+console.log(`${ns} nanoseconds`);
+console.log(`${ms} milliseconds`);
+console.log(`${ss} seconds`);
+
+
+var bin = path.basename(process.argv[1]);
+var command = process.argv.slice(2).join(" ");
+var data = `"${bin} ${command}",${ss.toFixed(6)}\n`;
+require('fs').appendFileSync(path.join(process.cwd(), 'require-resolution-time.txt'), data);
+
+
 function makeCommand(commandName) {
   return parser.command(commandName)
     .option('timeout', {
-- 
2.2.1
```


Here are the samples I've collected: 


| Requires | Seconds |
| -------- | ------- |
| \* | 1.241460 |
| \* | 0.770719 |
| \* | 0.771913 |
| \* | 0.762594 |
| \* | 0.781253 |
| \* | 0.771329 |
| \* | 0.776777 |
| \* | 0.802594 |
| \* | 0.770142 |
| \* | 0.778224 |


| Requires | Seconds |
| -------- | ------- |
| no requires | 0.000552 |
| no requires | 0.000521 |
| no requires | 0.000514 |
| no requires | 0.000509 |
| no requires | 0.000535 |
| no requires | 0.000529 |
| no requires | 0.000543 |
| no requires | 0.000586 |
| no requires | 0.000804 |
| no requires | 0.000545 |


| Requires | Seconds |
| -------- | ------- |
| parser | 0.041139 |
| parser | 0.037752 |
| parser | 0.038578 |
| parser | 0.034208 |
| parser | 0.029301 |
| parser | 0.027295 |
| parser | 0.027976 |
| parser | 0.030321 |
| parser | 0.028526 |
| parser | 0.025933 |


| Requires | Seconds |
| -------- | ------- |
| controller | 0.687592 |
| controller | 0.668337 |
| controller | 0.672104 |
| controller | 0.710061 |
| controller | 0.666924 |
| controller | 0.696653 |
| controller | 0.711061 |
| controller | 0.688737 |
| controller | 0.720844 |
| controller | 0.677363 |


| Requires | Seconds |
| -------- | ------- |
| init | 0.124307 |
| init | 0.121610 |
| init | 0.123842 |
| init | 0.121242 |
| init | 0.119768 |
| init | 0.124794 |
| init | 0.123246 |
| init | 0.121616 |
| init | 0.124911 |
| init | 0.197858 |


| Requires | Seconds |
| -------- | ------- |
| logs | 0.022695 |
| logs | 0.021206 |
| logs | 0.020510 |
| logs | 0.022346 |
| logs | 0.020685 |
| logs | 0.023063 |
| logs | 0.022449 |
| logs | 0.023639 |
| logs | 0.031704 |


| Requires | Seconds |
| -------- | ------- |
| drivers | 0.026438 |
| drivers | 0.025974 |
| drivers | 0.029616 |
| drivers | 0.025443 |
| drivers | 0.025017 |
| drivers | 0.028146 |
| drivers | 0.027863 |
| drivers | 0.024573 |
| drivers | 0.025658 |
| drivers | 0.033903 |


| Requires | Seconds |
| -------- | ------- |
| parser,controller | 1.131934 |
| parser,controller | 0.681400 |
| parser,controller | 0.679873 |
| parser,controller | 0.718931 |
| parser,controller | 0.682339 |
| parser,controller | 0.673516 |
| parser,controller | 0.683063 |
| parser,controller | 0.685132 |
| parser,controller | 0.679716 |
| parser,controller | 0.714631 |


| Requires | Seconds |
| -------- | ------- |
| parser,controller,init | 1.258900 |
| parser,controller,init | 0.807290 |
| parser,controller,init | 0.786188 |
| parser,controller,init | 0.779685 |
| parser,controller,init | 0.801378 |
| parser,controller,init | 0.772447 |
| parser,controller,init | 0.766832 |
| parser,controller,init | 0.766944 |
| parser,controller,init | 0.774835 |
| parser,controller,init | 0.800441 |


| Requires | Seconds |
| -------- | ------- |
| parser,controller,init,key | 1.339716 |
| parser,controller,init,key | 0.778741 |
| parser,controller,init,key | 0.824482 |
| parser,controller,init,key | 0.776943 |
| parser,controller,init,key | 0.795719 |
| parser,controller,init,key | 0.780844 |
| parser,controller,init,key | 0.768039 |
| parser,controller,init,key | 0.768651 |
| parser,controller,init,key | 0.763481 |
| parser,controller,init,key | 0.778972 |


| Requires | Seconds |
| -------- | ------- |
| parser,controller,init,key,logs | 0.842016 |
| parser,controller,init,key,logs | 0.775231 |
| parser,controller,init,key,logs | 0.773014 |
| parser,controller,init,key,logs | 0.840368 |
| parser,controller,init,key,logs | 0.772183 |
| parser,controller,init,key,logs | 0.780655 |
| parser,controller,init,key,logs | 0.783500 |
| parser,controller,init,key,logs | 0.782006 |
| parser,controller,init,key,logs | 0.761674 |
| parser,controller,init,key,logs | 0.776615 |


| Requires | Seconds |
| -------- | ------- |
| parser,controller,init,key,logs,drivers | 1.323371 |
| parser,controller,init,key,logs,drivers | 0.803361 |
| parser,controller,init,key,logs,drivers | 0.895562 |
| parser,controller,init,key,logs,drivers | 0.786487 |
| parser,controller,init,key,logs,drivers | 0.802692 |
| parser,controller,init,key,logs,drivers | 0.771629 |
| parser,controller,init,key,logs,drivers | 0.768442 |
| parser,controller,init,key,logs,drivers | 0.817924 |
| parser,controller,init,key,logs,drivers | 0.765560 |
| parser,controller,init,key,logs,drivers | 0.778988 |


Each set was created by either commenting out none, some or all of the requires at the top of `bin/tessel-2.js`. The requires that are resolved are listed in the Requires column, `*` means "all of them, as is".

**Comment by LinusU** [comment]
@rwaldron Awesome work! Looking forward to spending more time on this :)

**Comment by rwaldron** [comment]
There hasn't been any further activity here, so I'm going to close this for now. If we need to audit again in the future (we should), then it will be appropriate to open a new issue
