### ISSUE TITLE
Deployments to /app/ over USB hang

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#495]
I am able to deploy a 600kb over USB to RAM (on `/tmp`) but when I try to deploy to Flash (on `/app`), the deploy hangs after only 138.7kB are transferred.

**Comment by johnnyman727** [comment]
It's worth noting that I'm pretty sure the issue is due to a difference in Flash/RAM because I've ran `t2 push` and just changed the [deploy path](https://github.com/tessel/t2-cli/blob/55c51328e39915a846657dbb74214e45d45b89cf/lib/tessel/deploy.js#L120) to be the `run` path in RAM (ie all other `push` code was ran like usual) and it succeeded.

**Comment by johnnyman727** [comment]
Ugh this appears to be a race condition issue. If I run the USB Daemon in debugging mode, so it takes more time because it's logging to the console, the code is deployed just fine. When the USB Daemon is run as a shell script and no output, it hangs.

**Comment by rwaldron** [comment]
cc @HipsterBrown
