### ISSUE TITLE
No default Key for root command (if multiple Tessels are plugged)

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#497]
When running `t2 root` the default key is not set.
> INFO Starting SSH Session on Tessel. Type 'exit' at the prompt to end.
Warning: Identity file undefined not accessible: No such file or directory.
Permission denied (publickey).

reproduce this by plugging at least two Tessels and run `t2 root`

[x]    default key is present at ~/.tessel/id_rsa
[x]    Both Tessels are provisioned !
[ ]    `t2 root` also **should default to the default key** if it is not set by --key (it doesn't when multiple Tessels are plugged)

**Comment by johnnyman727** [comment]
@Student007 are you passing in a key option? [The default key is set](https://github.com/tessel/t2-cli/blob/55c51328e39915a846657dbb74214e45d45b89cf/lib/tessel/provision.js#L23) when `provision.js` loads.

**Comment by Student007** [comment]
> @Student007 are you passing in a key option? The default key is set when provision.js loads.

it seams it is not used if the `opts.key` is *undefined*. Means there is no path also if a key is present at `~/.tessel/id_rsa` but this is necessary if you have multiple Tessels accessible by wifi and you do not use the `--key` option (because you like to use the default key).

**I am suggesting three different solutions:**
https://github.com/tessel/t2-cli/pull/502 => ([handle a possible opts.key===*undefined* within `controller.root`](https://github.com/tessel/t2-cli/pull/502/files))
https://github.com/tessel/t2-cli/pull/498 => ([Override the default `--key` option with a default key path](https://github.com/tessel/t2-cli/pull/498/files))
https://github.com/tessel/t2-cli/pull/501 => ([Add a default path to the default `--key` option](https://github.com/tessel/t2-cli/pull/501/files))

My preference would be #498 because it is a valid pattern to override default behaviors if necessary.
My second favorite would be #501 because other commands would ignore `opts.key` if they do not use it. And former this was discussed [here](https://github.com/tessel/t2-cli/pull/330)
If no alternative solution is provided I would suggest to fix the issue by #502 because it simple catches a not defined `opts.key`until a better solution will be given by deeper researches.

...please add your own ideas (by discussion).

**Comment by Student007** [comment]
@rwaldron what is your preference - ask you because you did the lightweight implementation of `t2 root` ?

**Comment by johnnyman727** [comment]
@Student007 I was able to recreate the issue today. I wasn't able to recreate it before because I used the `ssh-add` utility to add my `.tessel` folder to the path SSH looks when attempting to connect to a device - that's why it wasn't a problem that the key was undefined. I apologize for not taking a closer look at the code earlier.

I believe #512 is the simplest way of solving this problem. What do you think?

**Comment by Student007** [comment]
@johnnyman727 
> I apologize for not taking a closer look at the code earlier

OK - this explains why I couldn't follow your arguments and why I got angry about things you did I interpreted as bad game. :love_letter: 
 
> I believe #512 is the simplest way of solving this problem. What do you think?

I commented the code and created a new PR #514 including your tests due to the idea @rwaldron idea to take Tessel instead of Controller as base for the default parameter.
