### ISSUE TITLE
t2-cli for IntelEdison

### ISSUE THREAD

**Issue by mulderp** [tessel/t2-cli#508]
To continue the discussion from https://github.com/tessel/project/issues/123

The first idea might be to have:

    t2 list

show additional IntelEdison devices.

Device information might be defined in a new directory `boards/intel-edison.js`

**Comment by Student007** [comment]
@mulderp [here](https://github.com/tessel/openwrt-tessel/tree/master/package/tessel/tessel-mdns
) you can find a good starting point what you have to do for the IntelEdisons firmware!

Let me know your steps you go when you can see IntelEdison by using `t2 list` :smile_cat: - love your intend !!!

**Comment by mulderp** [comment]
Thanks. My first steps are exploring [mdns](http://agnat.github.io/node_mdns/user_guide.html#introduction)

    var mdns = require('mdns')
      , ad = mdns.createAdvertisement(mdns.tcp('http'), 4321)
      ;
    ad.start();

Actually, the Intel Edison and Galileo boards seem to use something called [Connman](https://01.org/connman) to setup connectivity.

**Comment by mulderp** [comment]
@Student007 that command `dns-sd` seems to work:

```
root@galileo:~/mdns# dns-sd -R galileo '_tessel._tcp' 'local' 22
Registering Service galileo._tessel._tcp.local port 22
DATE: ---Sat 02 Jan 2016---
17:08:10.553  ...STARTING...
17:08:11.292  Got a reply for service galileo._tessel._tcp.local.: Name now registered and active
```

Btw, uci does not work:


```
root@galileo:~/mdns# uci
-sh: uci: command not found
```

**Comment by mulderp** [comment]
Hm.. now how to ping that mdns service?

`t2` gives:

```
pm:mdns pmu$ t2 list
INFO Searching for nearby Tessels...
dgram.js:461
    throw new Error('Not running'); // error message from dgram_legacy.js
    ^

Error: Not running
    at Socket._healthCheck (dgram.js:461:11)
    at Socket.address (dgram.js:371:8)
    at SendWrap.callback (/Users/pmu/.nvm/versions/node/v4.0.0/lib/node_modules/t2-cli/node_modules/mdns-js/lib/networking.js:178:52)
    at SendWrap.afterSend [as oncomplete] (dgram.js:347:8)
```

And that Node mnds lib gives no pong back either:

```
var mdns = require('mdns');

var browser = mdns.createBrowser(mdns.tcp('http'));

browser.on('serviceUp', function(service) {
  console.log("service up: ", service);
});
browser.on('serviceDown', function(service) {
  console.log("service down: ", service);
});

browser.start();
```

**Comment by johnnyman727** [comment]
> Btw, uci does not work:

That is to be expected - `uci` is an OpenWRT utility. I don't think you'll need it in any case.

I'm not sure why `t2 list` is throwing an error for you. Perhaps one of the underlying OSX or Linux mDNS services is not running.

Your second example won't find it because of this line:
```
var browser = mdns.createBrowser(mdns.tcp('http'));
```

You need to be browsing for the `tessel` type since that's how you're advertising on your Edison: `dns-sd -R galileo '_tessel._tcp' 'local' 22`:
```
var browser = mdns.createBrowser(mdns.tcp('tessel'));
```
Or if that doesn't work, [this is what we do in the t2-cli](https://github.com/tessel/t2-cli/blob/master/lib/lan_connection.js#L152):
```
self.browser = mdns.createBrowser('_tessel._tcp');
```

On OSX, I often just use a command line utility to debug whether any Tessels are advertising:
```
dns-sd -B _tessel._tcp .
```

I hope that helps!

**Comment by mulderp** [comment]
Thanks for the info. Indeed, it helped me understand better how mDNS works, but on the Poky Linux image I have some troubles. Opened a support ticket with Intel: https://communities.intel.com/message/363704#363704

**Comment by mulderp** [comment]
About 

> I'm not sure why t2 list is throwing an error for you. Perhaps one of the underlying OSX or Linux mDNS > services is not running.

Not sure, was also seen here https://github.com/tessel/t2-cli/issues/343 - but has less prio for me now.

**Comment by Student007** [comment]
@mulderp are you working within a vagrant image (virtual machine I mean)?

**Comment by johnnyman727** [comment]
@mulderp yeah, I had seen it a few times but never got to the root of it. Are you on OSX?

To rule out weird network infrastructure problems, you might want to see if you can advertise with your host machine and pick it up in another terminal window:
```
# Advertise in one window
dns-sd -R $(whoami) '_tessel._tcp' 'local' 22
```
```
# Detect in another window
dns-sd -B _tessel._tcp .
```

**Comment by mulderp** [comment]
Thanks, nice trick. Yes, that works. I have the feeling that the problem might be this `connman` tool, that overwrites files in `/etc/` on my device. Or, it is the router that does not act properly as bridge between WLAN and ETH0.
Anycase, there is also the option to retry this on an Raspberry Pi or Beaglebone if I have time.

**Comment by johnnyman727** [comment]
@mulderp yeah sounds like something funky happening on the Edison. Unfortunately, I'm not very familiar with the platform so hopefully someone on the forums can chime in.

**Comment by Student007** [comment]
@mulderp 
> Anycase, there is also the option to retry this on an Raspberry Pi or Beaglebone if I have time.

would love to hear about your results :+1:  !!!

**Comment by mulderp** [comment]
Ok, with another subnet on the Router 192.168.3.0 and an Edison, `mdns` is working. Now, I need to start extending the browser command from t2-cli.

**Comment by Student007** [comment]
@mulderp cool !! thought you stopped working because of this. Go forward its great what you are doing :+1: 
Easiest way is you fork the t2-cli ([as all contributors should do](https://github.com/tessel/project/blob/master/CONTRIBUTING.md#2-set-up-your-branch)) and work in a branch. Maybe it fits and we could merge it !

**Comment by johnnyman727** [comment]
:clap: Nice job @mulderp!

**Comment by mulderp** [comment]
Some note that the Redbear Duo comes with an Arduino sketch that supports mdns:

https://github.com/redbear/STM32-Arduino/blob/master/arduino/libraries/RedBear_Duo/examples/01.Basics/Duo_WebServer/Duo_WebServer.ino#L42-L44

Might try later to discover the device with t2-cli

**Comment by johnnyman727** [comment]
@mulderp are you still working on this issue? If not, I'm going to go ahead and close it because it's not a priority at the moment.

**Comment by mulderp** [comment]
no, since I am working with other boards currently, lack of mdns on Edison seems less important
