### ISSUE TITLE
copySync errors swallowed, hanging deploy

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/t2-cli#524]
While working on a [smoke test](https://github.com/tessel/t2-compiler/issues/14#issuecomment-171880205) for t2-compiler, the deployment would hang after `INFO Connected to...`. I discovered this was due to [`fs.copySync`](https://github.com/jprichardson/node-fs-extra#copysync) blocking errors inside of the `actions.injectBinaryModules` function.

**Comment by johnnyman727** [comment]
@HipsterBrown could this also be the cause of https://github.com/tessel/t2-cli/issues/271? Or maybe just one of a number of causes.

**Comment by HipsterBrown** [comment]
It could be. The best practice in the future would be to add a `.catch()` to every Promise chain, so we can throw or reject those swallowed errors.

**Comment by johnnyman727** [comment]
:+1: good point. I'll keep my eye out to see if I hit this hanging issue anymore. I've tried to make sure all errors are being passed up the chain but it's totally possible I missed a few cases.
