### ISSUE TITLE
Binary not found in details.extractPath, 'Release', details.binName

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/t2-cli#526]
While working on a [smoke test](https://github.com/tessel/t2-compiler/issues/14#issuecomment-171880205) for t2-compiler, I discovered the path to `leveldown` binary was not found in `~/.tessel/binaries/leveldown-1.4.3-Release/Release/leveldown.node`. Instead it was located in `~/.tessel/binaries/leveldown-1.4.3-Release/package/build/Release/leveldown.node`. 

Should we use `path.resolve` before trying to copy the source binary to the temp project path? 

How do generally search for those target binaries?

**Comment by johnnyman727** [comment]
@rwaldron would be the expert on this.

**Comment by rwaldron** [comment]
I will take a look at this as soon as I can (probably Wednesday). I have a pretty good idea of what needs to be fixed, I just need time to work through it.

**Comment by rwaldron** [comment]
I'm going to hold off on this for now because the binary isn't available anymore and was also built incorrectly (according to @reconbot). I just did a local npm install and the path matched the one that would be expected.

**Comment by johnnyman727** [comment]
@rwaldron does your latest patch fix this?

**Comment by rwaldron** [comment]
Indeed it does
