### ISSUE TITLE
getTessel fails if there are no USB or no LAN Tessels

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#53]
There are a couple of issues with `getTessel` (that, frankly, I should have caught in my last code review). 

First, I believe the `lan.findConnections` and `usb.findConnection` functions in the Promise.join need to be invoked with parenthesis. 

Second, Promise.join returns two arrays and those need to be consolidated.

**Comment by HarleyKwyn** [comment]
Current pull request that is open uses promise.all but yes if one fails
they a will. I'll find a way to fix that.
