### ISSUE TITLE
"Golden Image" firmware incompatible with CLI at master

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#538]
The `t2 provision` command (and any command that needs to send more than 255 bytes to the T2 before finishing) will fail when using `t2-cli` on https://github.com/tessel/t2-cli/commit/1e2c781e3e1f341993894aba41041ab165fc441f (Dec 11) or later with a device coming out of the factory. The factory's golden image is using [this OpenWRT build](https://github.com/tessel/openwrt-tessel/tree/209b5d98c2aa973ff1f604199a6b747b558840a6) and [this firmware build](https://github.com/tessel/t2-firmware/tree/38ad738060d6f71ff3945fa9d75345eb3f0a4302) (as best as I can tell from checking when jia and kevin contributed code last from the factory). This is because recent USB speed improvements depend on larger packets being sent and the old firmware doesn't account for those larger packets.

Current Workaround:
`git checkout 96f823abf55f1f0fd24a333c556a9f76484d5927` or earlier of the CLI.

Possible Longer Term Solutions:
1. Update the golden image at the factory. This seems most appealing. The downside is that there is some risk of failing the tests or Seeed not installing it correctly, thus delaying shipment.

2. Detect firmware version on T2 and adjust usb packet size accordingly. Yuck.

3. Revert the change. Yuck.

**Comment by rwaldron** [comment]
Why are they using such an old version?

> 1. Update the golden image at the factory. 

This seems like the _only_ solution :\


Also, +1 to both of your "yucks"

**Comment by Frijol** [comment]
+1 to @rwaldron 's comment. Ugh.

**Comment by johnnyman727** [comment]
I fixed this by uploading the latest OpenWRT and firmware (`0.0.7`) to the server that returns builds to the testalator (option 1).

For future reference, this is how it's done: https://gist.github.com/jiahuang/bdd0b5abd0421a94ed7d.

**Comment by rwaldron** [comment]
So this is resolved?? :O

**Comment by johnnyman727** [comment]
I don't want to mark it resolved until I've tested it on the test bench and confirmed with Seeed that we're good to go.

**Comment by johnnyman727** [comment]
This is resolved for all future Tessels via a series of commits in `tessel/t2-test-rig-sw`.
