### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by io2work** [tessel/t2-cli#540]
_npm install -g t2-cli_ fails on Windows 10. I've tried installing it with Node 0.12.7 and with Node 4.2.6. I've also tried it with and without running CMD as an admin. See stdout & stderr below...

```
> usb@1.1.1 install C:\Users\qcras\AppData\Roaming\npm\node_modules\t2-cli\node_modules\usb
> node-pre-gyp install --fallback-to-build

[usb] Success: "C:\Users\qcras\AppData\Roaming\npm\node_modules\t2-cli\node_modules\usb\src\binding\usb_bindings.node" is installed via remote
C:\Users\qcras\AppData\Roaming\npm\t2 -> C:\Users\qcras\AppData\Roaming\npm\node_modules\t2-cli\bin\tessel-2.js

> t2-cli@0.0.9 postinstall C:\Users\qcras\AppData\Roaming\npm\node_modules\t2-cli
> t2 install-drivers || true

't2' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "t2-cli"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! t2-cli@0.0.9 postinstall: `t2 install-drivers || true`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the t2-cli@0.0.9 postinstall script 't2 install-drivers || true'.
npm ERR! This is most likely a problem with the t2-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     t2 install-drivers || true
npm ERR! You can get their info via:
npm ERR!     npm owner ls t2-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\qcras\npm-debug.log
```

**Comment by johnnyman727** [comment]
This is interesting: it looks like even though you installed globally, the post script was unable to find `t2` binary on your PATH. I'm not sure why that would be if it installed properly. Have you been able to use other globally installed packages on this machine?

**Comment by io2work** [comment]
I ended up finding this on StackOverflow...
http://stackoverflow.com/questions/27344045/installing-node-js-and-npm-on-windows-10

After reinstalling Node.js 4.2.6 and setting the path variables to
%AppData%\npm & %ProgramFiles%\nodejs it installed just fine.


--------------------

"Here's the key to becoming irreplaceably valuable in any organization. In
4 words: Bring solutions, not problems." -Steven Furtick

**Comment by io2work** [comment]
I ended up finding this on StackOverflow... http://stackoverflow.com/questions/27344045/installing-node-js-and-npm-on-windows-10

After reinstalling Node.js 4.2.6 and setting the path variables to %AppData%\npm & %ProgramFiles%\nodejs it installed just fine.

**Comment by johnnyman727** [comment]
Fantastic, thanks for investigating!

**Comment by gdibble** [comment]
@dudleyjosh were you able to connect with `t2 list` or anything else in Windows?
I'm having a tough time with win7/win10/etc. Any tips would be greatly appreciated!

**Comment by dudleyjosh** [comment]
I have had success with Windows 10 64 bit but not with Windows 7... it is a known issue that they are actively working on.

See [this](https://forums.tessel.io/t/tessel-2-driver-issues-on-windows-10/2238/151) and more specifically [this](https://gist.github.com/tcr/992978a5dbe5bff2e18f495c5c0973c3)
