### ISSUE TITLE
[code] USB.Connection.prototype._close are releasing zalgo

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#554]
[Releasing zalgo](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony) is very bad, it releases H̵͘͡e ̡wh́o͠ ̶Prom̀͟͝i̴s̀es̀ o҉̶nl̨͟y̧ ̛̛m̴͠͝a̡̛͢d̡n̴̡e͝s̸s͠, T̢҉̸h̴̷̸̢ȩ͡ ͘͠N͢͢e͏͏͢͠z̛͏͜p̸̀̕͠ȩ́͝͝r҉̛́͠d̴̀i̴̕҉͞a̴̡͝͠n̢͜͟͢͟ ̶̴̢͝h̷̕͠í̸̧̛͜v̶̢͢͡e̕͡-̸̀͝m̷͜i̛͘͞ņ̛͘͟҉d̶̶̡̧͜ ̷̛͞o̵̢͘͟͞f̶̢̀͢͢ ̶̧͟͡c̕͝h̶̀͘͘à͏o҉̴́͢s̸͘͘͝͞.̨͢͞.

**Comment by johnnyman727** [comment]
I didn't click the link but I think I know what you're talking about. Actually, I just fixed it as I was improving integration with our test rig software: https://github.com/tessel/t2-cli/pull/555/files#diff-b6ac01199a2ad325c2bc013dd0a23ee6R196

**Comment by LinusU** [comment]
That's not quite it, a function is said to release zalgo when it takes a callback, and when that callback might be called immediately _or_ in some other tick, but there is no way to know which one.

I should mention that the link goes to blog of Isaac Z. Schlueter, the creator of Npm. It's in no way dangerous, the broken text has merely become an inside joke when referring to zalgo :)

**Comment by rwaldron** [comment]
@johnnyman727 this line: https://github.com/tessel/t2-cli/blob/master/lib/usb_connection.js#L206 needs to be wrapped in a `process.nextTick` or `setImmediate`

**Comment by johnnyman727** [comment]
Ah got it. Yeah Zalgo sounds bad. We should fix that.

**Comment by johnnyman727** [comment]
Probably fixed with #571 but still needs tests.

**Comment by johnnyman727** [comment]
I'm going to close this now unless we get another glimpse of Zalgo.
