### ISSUE TITLE
[code] Why isn't USBDaemon using the prototype

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#556]
Instead of using the prototype, it defines all the functions locally in the constructor instead. Is there a valid reason for this?

**Comment by johnnyman727** [comment]
I was essentially making a Singleton class. Is there a better way to do it?

**Comment by LinusU** [comment]
The line that makes it a singleton in this case is just the `module.exports = new USBDaemon();`, so the class in itself could use to more standard way of defining a class.

It could therefor look like this which makes it, at least in my opinion, much more readable:

```javascript
class USBDaemon {
  constructor () {
    this.entries = {}
    this.currentID = 0
  }

  register (connection) {
    // ...
  }

  // ...
}
```

**Comment by johnnyman727** [comment]
Well, also [this part](https://github.com/tessel/t2-cli/blob/master/lib/usb/usb_daemon.js#L16-L20) but you're still totally right. We could make it use the `prototype` chain - I was just trying something new at the time :)

**Comment by LinusU** [comment]
> Well, also this part

True, although it won't actually hit that since the class itself isn't exported, so there is no way to actually instantiate it again :)

**Comment by johnnyman727** [comment]
I'm going to close this issue because it's not a priority. If this non-standard initialization starts causing problems, we can re-open the discussion.
