### ISSUE TITLE
Add ws to deploy blacklists

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#574]
`ws` doesn't compile for our openwrt build, but isn't necessary for socket.io to function correctly. Before https://github.com/tessel/t2-cli/commit/32f95fe163986ba482a96aae04d4eb1393ea564a, the missing .node was just ignored and socket.io worked just fine when deployed to a tessel. After https://github.com/tessel/t2-cli/commit/32f95fe163986ba482a96aae04d4eb1393ea564a, there are warnings about it being missing (which is the correct thing to do), but in this case, we know that it's not necessary.

**Comment by johnnyman727** [comment]
@rwaldron are you getting the same `TypeError: Cannot read property 'targets' of undefined` error when you try to compile or something different?

**Comment by rwaldron** [comment]
No, I'm seeing 

```
WARN Pre-compiled module is missing: ws.
This might be caused by any of the following:

1. The binary is platform specific and cannot be compiled for OpenWRT.
2. A pre-compiled binary has not yet been generated for this module.
3. The binary didn't compile correctly for the platform that you're developing on.
    It's possible that the binary is Linux-only or even OpenWRT specific,
    try npm installing with "--force" and rerun your deployment command.

Please file an issue at https://github.com/tessel/t2-cli/issues/new
```


Can you file a separate issue for that error—thanks!

**Comment by johnnyman727** [comment]
@rwaldron to be clear, I got that error from `t2-compiler` - I wasn't using the CLI yet. I'll open an issue on `t2-compiler`.

**Comment by rwaldron** [comment]
No, it was: 

```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.21
node-pre-gyp info using node@4.2.1 | linux | x64
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: ws package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack main
```

**Comment by johnnyman727** [comment]
Here is the issue I filed: https://github.com/tessel/t2-compiler/issues/17.

**Comment by rwaldron** [comment]
It looks like the missing `main` poperty has been resolved: https://github.com/websockets/ws/commit/523b61f7d7aa92fdc15ac406c5c6b03b71b4259a


Also, I believe the issues here were caused by my using a much older version of `ws`

**Comment by johnnyman727** [comment]
Okay great - so once they make a new release, we can throw it up on packages.tessel.io and this shouldn't be an issue anymore.

**Comment by rwaldron** [comment]
I've just tried my example socket chat app with latest socket.io (which installs latest ws)

https://www.youtube.com/watch?v=q06xu8_E2IA

**Comment by johnnyman727** [comment]
That has got to be the cutest socket.io example I've ever seen.

**Comment by rwaldron** [comment]
hahaha
