### ISSUE TITLE
Possible problems with the tests

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#592]
I've been reading thru the testing code and found quite a few things that we should probably look at.

1) The use of `test.fail`

`test.fail` isn't documented at all in `nodeunit`, rather, it's an internal method with the signature of `function fail(actual, expected, message, operator, stackStartFunction)`. However I've seen a number of places where it's being used like this: `test.fail('Something bad happend')`.

2) Throwing inside promises

Another thing that seems to happen quite a lot, is throwing inside promises. This is often hidden by a call to `test.*`. Problematic code:

```javascript
provision.setDefaultKey(testPath)
  .then(...)
  .catch((err) => {
    test.ok(false, 'Something bad happened')
  })
```

The problem with this code is that `test.ok` internally calls `test.fail`, which will throw an `AssertionError`. The idea with nodeunit is that it listens for this error and then records it as a failure. But in this example, the only thing that will happen is that the promise returned from the `setDefaultKey` call, will be recorded as "rejected".

I've also seen the following code in a few places which I think is a way to work around that you can't actually throw inside a promise handler...

```javascript
fs.remove(testDir, (err) => {
  if (err) {
    console.log('Error removing tmp directory: ' + err);
    process.exit();
  }

  // ...
});
```

Had this been outside any promise, it could have been written as `if (err) throw err;` or even `test.ifError(err)`. (the naming is `ifError` because it usually lives on an object called `assert`. `assert.ifError` makes sense while `test.ifError` sounds like it will test if the parameter is an error)

3) `.then(test.fail)`

This doesn't actually do anything, a product of both of the above problems. Example:

```javascript
    // Attempt to provision
    this.tessel.provisionTessel()
      // If an error is not thrown, this test failed
      .then(test.fail)
```

4) `if (err) test.fail()`

This hides the message about why it failed. It should be replaced with `test.ifError(err)`

5) Assigning unused stuff to `this`

Many tests seems to assign quite a lot of stuff to `this` (the test context) that never gets used. ~~The one thing I can think of is that it was used before the use of `sinon.sandbox` to restore the stubs.~~ It's probably done because some of these gets the `.callCount` checked. It would be nice to remove the assignment to make the code more readable.

6) The failing test isn't shown

To me this is a very unhelpful message:

```text
Running "nodeunit:tests" (nodeunit) task
Testing access-point.js......OK
Testing bin-tessel-2.js..........................OK
Testing constructor.js......OK
Testing controller.js..............................OK
Testing deploy-lists.js.OK
Testing deploy.js............................................................OK
Testing discover.js........Fatal error: tessel.connection.open(...).then is not a function
```

I had to resort to counting the number of `.`s and then counting the number of functions in the file to find out in which test the problem was.

*I'll edit the issue if/as I discover more things*

**Comment by LinusU** [comment]
I would like to propose that we investigate using [ava](https://github.com/sindresorhus/ava) which is a modern test runner for node. One really cool thing is that it would allow us to use `async`/`await` in our tests which I think would really clean up the code base. It would also solve all the above problems for us.

**Comment by rwaldron** [comment]
I fully support fixing the actual issues you've observed, but I'm opposed to switching the test runner "just because".

> had to resort to counting the number of .s 

If you add the `-v` (verbose) flag, you'll see what test failed.

> allow us to use async/await

These features aren't standard yet and are more than a year away from being so. Additionally, V8 hasn't made much effort to implement: https://bugs.chromium.org/p/v8/issues/detail?id=4483 using a transpilation step for tests is out of the question.

**Comment by LinusU** [comment]
I don't think that it is "just because", I stated a number of problems with the current one. But I agree that it's not something one would do lightly, which is why I just said that we investigate it.

> If you add the `-v` (verbose) flag

I haven't even figured out how to run only the tests since I get this error message :)

```text
$ grunt nodeunit:test
Running "nodeunit:test" (nodeunit) task
Verifying property nodeunit.test exists in config...ERROR
>> Unable to process task.
Warning: Required config property "nodeunit.test" missing. Use --force to continue.

Aborted due to warnings.
```

Running `node_modules/grunt-contrib-nodeunit/node_modules/.bin/nodeunit` manually just spews out a ton of `TypeError`s and `ReferenceError`s...

**Comment by johnnyman727** [comment]
@LinusU thanks for digging up these issues. The `test.fail`s are mostly an artifact of me lazily trying to make a test fail (I didn't realize it was an actual method). You're absolutely right that we should be using the method in the proper way or, better yet, using documented functions,

I believe you can run `nodeunit` in `verbose` mode with `grunt nodeunit -v`. If you want to run a single file, for instance, you can run `grunt nodeunit:only:provision -v`.

**Comment by rwaldron** [comment]
A lot of action taken here, I'm going to close for now. If we need to audit again in the future (we should), then it will be appropriate to open a new issue
