### ISSUE TITLE
Finish CLI design

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#60]
CLI is under design. This needs to be finalized and codified into issues.

Design completeness of commands:

* [x] tessel provision: [#64](https://github.com/tessel/t2-cli/issues/64)
* [x] tessel \[-h | --help]: [#65](https://github.com/tessel/t2-cli/issues/65)
* [x] tessel init: [#76](https://github.com/tessel/t2-cli/issues/76)
* [x] tessel rename: [#77](https://github.com/tessel/t2-cli/issues/77)
* [x] tessel erase: [#78](https://github.com/tessel/t2-cli/issues/78)
* [x] tessel run: [#79](https://github.com/tessel/t2-cli/issues/79)
* [x] tessel root: [#80](https://github.com/tessel/t2-cli/issues/80)
* [x] tessel update: [#81](https://github.com/tessel/t2-cli/issues/81)
* [x] tessel wifi: [#82](https://github.com/tessel/t2-cli/issues/82)
* [x] tessel logs: [#88](https://github.com/tessel/t2-cli/issues/88)
* [x] tessel select: [#93](https://github.com/tessel/t2-cli/issues/88)
* [x] tessel push: [#91](https://github.com/tessel/t2-cli/issues/91)
* [x] tessel ap: [#87](https://github.com/tessel/t2-cli/issues/87)
* [x] tessel status: [#95](https://github.com/tessel/t2-cli/issues/95)
* [x] tessel list: [#86](https://github.com/tessel/t2-cli/issues/86)

**Comment by Frijol** [comment]
Currently in RFC on the forums [here](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743).
Planning to close RFC Monday and formalize into issues.

**Comment by Frijol** [comment]
All set, everything is moved to GH issues.

**Comment by johnnyman727** [comment]
:clap: :clap: thanks for handling that @Frijol
