### ISSUE TITLE
Make a command for fetching the current version of the CLI

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#604]
This is useful for debugging purposes.

The likely implementation will take the current `t2-cli` commit sha and either compare it to Github tags (where we save each version) or we'll save a copy of each version on our AWS server like we did with Tessel 1.

**Comment by wyze** [comment]
Couldn't this be as simple as just reading in the version field from `package.json`? I added the output really quick and could look something like this:

```
❯ t2 version
INFO Looking for your Tessel...
INFO Connected to t2-testing.
INFO Tessel [t2-testing] CLI version: 0.0.18
INFO Tessel [t2-testing] Firmware version: 0.0.12
INFO Tessel [t2-testing] Node version: 4.2.1
```

**Comment by johnnyman727** [comment]
@wyze It's been a while now but what I think I meant was that we want a way to compare the version of the CLI being used with the most recently published (which I referred to as "current") CLI. In any case, that was closed with #665 but outputting the CLI version in the `t2 version` command would definitely still be useful.

**Comment by wyze** [comment]
Alright, that makes sense. I will send a PR over adding CLI version to output of `t2 version` and it can be discussed there further if the team would like it to be added or not. Thanks for the clarification.

**Comment by johnnyman727** [comment]
:+1:
