### ISSUE TITLE
Wifi info timeout can be too short 

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#606]
I ran into an issue with the test rig where the time between when we commit wireless credentials and when we check the result of the connection attempt is too short such that the process that prints connection info completes before the connection is taken up and it considers the connection a failure even though it succeeds a few seconds later.

Specifically, this code is [here](https://github.com/tessel/t2-cli/blob/12e4e212c9e540604f0ed27ffcf6bf3b86c2da78/lib/tessel/wifi.js#L145-L187). You can see that we call `reconnectWifi` which starts the process of connecting using credentials just saved in `/etc/config/wireless` then we set a timeout for 2 seconds to "give the connection time to settle". Then we create a process to print out the connection status which we scan for a keyword that indicates a successful connection. Unfortunately, this last process gets called before the connection has settled.

My guess is that a timeout is not the right way to go here if we want robust code. I'm surprised that we haven't been analyzing the output of `reconnectWifi` for a positive keyword.

**Comment by johnnyman727** [comment]
For references, I ended up using an 8 second timeout in the test rig just to be safe. I had failures even at 4 seconds.

**Comment by rwaldron** [comment]
Resolved https://github.com/tessel/t2-cli/pull/610
