### ISSUE TITLE
tessel wifi --list fails and tessel wifi -n <name> -p <password> does not work.

### ISSUE THREAD

**Issue by tikurahul** [tessel/t2-cli#619]
I am trying to use my new Tessel 2, and for whatever reason I cannot get the Tessel 2 to connect to my Wireless network.

If i use the command `tessel wifi --list` I just get the following exception.

```
INFO Looking for your Tessel...
INFO Connected to rahulrav over USB
INFO Scanning for available networks...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Error upon remote process exit: 4
    at USBProcess.<anonymous> (/usr/local/lib/node_modules/t2-cli/lib/usb/usb_process.js:49:26)
    at USBProcess.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at USBProcess.emit (events.js:182:7)
    at Parser.<anonymous> (/usr/local/lib/node_modules/t2-cli/lib/usb/usb_daemon.js:121:14)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Parser._write (/usr/local/lib/node_modules/t2-cli/node_modules/usb-daemon-parser/index.js:152:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Parser.Writable.write (_stream_writable.js:215:11)
    at ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Readable.push (_stream_readable.js:111:10)
```

I modified `wifi.js` with the following patch:

```
diff --git a/lib/tessel/wifi.js b/lib/tessel/wifi.js
index d70fb1b..26367cc 100644
--- a/lib/tessel/wifi.js
+++ b/lib/tessel/wifi.js
@@ -38,6 +38,10 @@ Tessel.prototype.findAvailableNetworks = function() {

         return networks;
       }, []).sort(compareBySignal);
+    }).catch(function(error) {
+      logs.err('Error while scanning for available networks...', error);
+      // continue to throw the error
+      throw error;
     });
 };
```

With my changes, when step through the code using `node-inspector` I see the following:

```
➜  CLI git:(master) ✗ node-debug t2 wifi --list
Node Inspector v0.12.7
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Debugging `t2`

Debugger listening on port 5858
INFO Looking for your Tessel...
INFO Connected to rahulrav.
INFO Scanning for available networks...
ERR! Error while scanning for available networks... [Error: No such wireless device: wlan0
]
ERR! Error: No such wireless device: wlan0
```

Any ideas on how to fix this ?

**Comment by johnnyman727** [comment]
Hi @tikurahul I think I've seen this issue on an older version of firmware. Can you run `t2 version` and report what it outputs?

**Comment by tikurahul** [comment]
@johnnyman727, the version is `0.0.10`.

```
➜  ~ t2 version
INFO Looking for your Tessel...
INFO Connected to rahulrav over USB
INFO Tessel [rahulrav] version: 0.0.10
```

**Comment by johnnyman727** [comment]
@tikurahul I believe the most recent version is `0.0.11` so you should run `t2 update` so make sure you have the most up-to-date code.

I'm not sure this will fix the underlying issue because updates don't usually overwrite config files unless explicitly stated to do so. If it doesn't work, one temporary workaround would be to [edit this line](https://github.com/tessel/t2-cli/blob/30a8fedd4fd6a2ac08e5283b559da0022393a0fa/lib/tessel/commands.js#L89) to be `return ['sysupgrade', '-n', path];`. It basically tells the operating system to overwrite the configuration files. Bonus points if you submit a PR that adds a optional flag for the `update` procedure that allows you to run `t2 update -d` to do exactly this! :)

**Comment by tikurahul** [comment]
`t2 update` would not have worked. @johnnyman727 helped me install new firmware and connect to Wi-Fi. After that everything just worked.

**Comment by johnnyman727** [comment]
It's also worth noting that some of the issues arose because of confusion generated around where `nvm` installs packages globally. I created #620 which is an actual issue that we need to fix.

**Comment by Injac** [comment]
I had a very similar problem as well. The first problem was, that WIFI was not even enabled, for whatever reason. A  "t2 wifi --on" helped me with the error "ERR! Error: No such wireless device: wlan0
".

**Comment by johnnyman727** [comment]
Thanks @Injac. It should be fixed by https://github.com/tessel/t2-cli/pull/648.

**Comment by Injac** [comment]
Thanks for all the hard work @johnnyman727  :)

**Comment by johnnyman727** [comment]
You should thank @boneskull! I just complained.

**Comment by Injac** [comment]
Well, than a big thank you to @boneskull :)
