### ISSUE TITLE
Move grunt tools to devDependencies?

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#625]
Grunt and related plugins increase the `t2-cli` size from 13Mb to 24Mb. Can we move them to the `devDependency` section of our `package.json`?

**Comment by rwaldron** [comment]
They always have been. https://github.com/tessel/t2-cli/blob/master/package.json#L33-L43

**Comment by rwaldron** [comment]
Not figuratively, literally: https://github.com/tessel/t2-cli/commit/d84cd349deae75ab16af975514890505ac409303

**Comment by johnnyman727** [comment]
My mistake!
