### ISSUE TITLE
Cannot "push" code to board

### ISSUE THREAD

**Issue by d1runberg** [tessel/t2-cli#635]
I am able to run code using 't2 run app.js', but when I try to push code ('t2 push app.js') I get an error and the code is never pushed. I have tried using 'erase', but I get a message that nothing is on the board to erase. Screen shot of error attached.
![pasted image at 2016_04_04 04_21 pm](https://cloud.githubusercontent.com/assets/9256788/14285038/e2203816-fafe-11e5-8f55-e820dc5196f3.png)

**Comment by d1runberg** [comment]
I force updated firmware to 0.0.11 and now it works

**Comment by johnnyman727** [comment]
Thanks for reporting @d1runberg!
