### ISSUE TITLE
[deploy] --slim 4 generator function fails

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#642]
Analyzing things by using PR https://github.com/tessel/t2-cli/pull/640 leads to the fact we cannot work with generator function like KOA js is basing on:

```
function *(next) {//...}
```
causes 
```
WARN Unexpected token operator «*», expected punc «(» at line 19:18 in file: [...] 
node_modules/koa/node_modules/koa-compose/index.js
```
This is related to @rwaldron issue https://github.com/mishoo/UglifyJS2/issues/968 at UglifyJS2 

I would suggest to identify the major reasons `--slim` fails and include a link to more information. In parallel it is a good idea to organize further manpower working on this.
It will become overwhelming to get lots of request next months. Most of the problems will come from deep dependencies.

Looking at the code in the current solution we seam to do the following at the moment:

- create an AST `uglify.AST_Node.from_mozilla_ast`
- fallback to `uglify.parse` source triggered by warnings
- fallback to `--full` on `uglify.parse` warnings

In my special case this causes in deployed code with errors like:
```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined [...]
```

**Please reference this issue if you found additional related issues to get an overview.**

**Comment by rwaldron** [comment]
The error your seeing wouldn't be caused by a syntax parsing failure, as TypeError is a runtime error—which means parsing was successful enough to run the program.

**Comment by johnnyman727** [comment]
@Student007 have you been able to confirm whether it's a runtime or pre-processing error?

**Comment by rwaldron** [comment]
@Student007 

> fallback to --full on uglify.parse warnings

That never, ever happens. `--full` does not just mean "the source is not compressed", it means "every single file, no matter what it is, is deployed". 

@johnnyman727 There is nothing this project can do right now, because...

## Smoke Test

```
mkdir generators && cd generators && t2 init;
echo "function * generator() { yield 1; yield 2; } for (var value of generator()) { console.log(value); }" > index.js;
t2 run index.js;
```

Result: 

```
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to maria.
INFO Building project.
INFO Writing project to RAM on maria (3.072 kB)...
INFO Deployed.
INFO Running index.js...
1
2
```


**However... https://github.com/mishoo/UglifyJS2/issues/1043**

But when I try the koa examples with `--full`, they work fine.

**Comment by johnnyman727** [comment]
@rwaldron to be clear, this is an issue with Uglify, not the CLI?

**Comment by Student007** [comment]
> That never, ever happens. --full does not just mean "the source is not compressed", it means "every single file, no matter what it is, is deployed".

@rwaldron does this mean deploying every time is changing code ? Is there an documented overview what happens during deployment ?
I promise: There was an error - I am currently not able to reproduce this due to time pressure. The only difference between both codes was commenting `require("tessel")`... @johnnyman727  But it is ok to close this issue until I will see it again.

**Comment by rwaldron** [comment]
> does this mean deploying every time is changing code 

I don't understand this question. 

> Is there an documented overview what happens during deployment ?

If only I had time. Right now I rely entirely on the extensive unit tests. Eventually I will have time to actually write a complete spec-like document.
