### ISSUE TITLE
New warning about tesselinclude is annoying

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#644]
I'm over here testing different versions of a program, generating a bunch of files in a directory and every time I run code, this warning comes up. I don't know what we should do.

**Comment by Student007** [comment]
@rwaldron  we could add a `--silence` flag. Or as I suggested [here](https://github.com/tessel/t2-cli/pull/640#issuecomment-207446672) we could change things into a debugging mode but blame in a single line with the hint to use debugging mode for more information.

> an alternative solution would be to add a debug mode and only warn once like this:
```
WARN Problems detected while shrinking files. 
INFO Please run the command with `DEBUG=deploy` to get more information.
```
The debug mode would do what this PR is doing.
Maybe this feels much cleaner ?

**Comment by Student007** [comment]
@rwaldron sorry - mixed up things.

**Comment by Student007** [comment]
The text should be part of `--help` and the the WARN should be like this
> WARN Ignored folders due to missing .tesselinclude (see: t2 run --help)

instead of
>WARN The following items were found in your project directory, but not deployed.

          .tesselinclude
    auth.js
    login.html
    public

        If you need to deploy them to your Tessel 2, you must have a .tesselinclude
        file that lists the file and directory assets for your application. This can be
        created manually or by typing 't2 init'.

        For more information, visit: https://tessel.io/docs/cli#starting-projects

**Comment by boneskull** [comment]
I was going to address this, but due to #649 I couldn't make heads or tails of what I was doing.
