### ISSUE TITLE
unit tests pass when they fail

### ISSUE THREAD

**Issue by boneskull** [tessel/t2-cli#649]
to reproduce this, I added the following at line 1650 of `test/unit/deploy.js`:

```js
test.equal(true, false);
```

I saw the test fail (briefly), but then it reports "OK" and passes anyway.

**Comment by boneskull** [comment]
I'd send a PR to fix this, but I'm not familiar with `nodeunit`.  Want help switching to Mocha? :stuck_out_tongue_closed_eyes:

**Comment by rwaldron** [comment]
> line 1650

I'm confused, this line has a silly test of the contents of the annoying tesselinclude message—is that definitely the line?


> Want help switching to Mocha?

Nope ;)

**Comment by rwaldron** [comment]
Also, good to see you here ❤️

**Comment by rwaldron** [comment]
Oh wow, I have no idea how to explain how on earth I made that weird mistake.

**Comment by rwaldron** [comment]
When I put that code at line 1650, the tests fail: 

```
$ grunt nodeunit:only:deploy
Running "nodeunit:only:deploy" (nodeunit:only) task

Running "nodeunit:tests" (nodeunit) task
Testing deploy.js.........................................F..........................
>> deploy.tarBundle - bothDetectAssetsWithoutInclude
>> Error: true == false
>> at /Users/rwaldron/clonez/t2-cli/test/unit/deploy.js:1651:12

>> deploy.tarBundle - bothDetectAssetsWithoutInclude
>> Error: Expected 10 assertions, 11 ran
>> at Object.exports.Tessel.prototype.memoryInfo.meminfo.exports.Tessel.prototype.deployScript.bundling.test.runScript.runScriptSingle.pushScript.pushScriptSingle.writeToFileDefaultEntryPoint.test.writeToFileSendsCorrectEntryPoint.exports.deploy.compress.ourAcornParseOptions.ourUglifyParseOptions.exports.deploy.tarBundle.tearDown (test/unit/deploy.js:645:5)

Warning: 2/282 assertions failed (3348ms) Use --force to continue.

Aborted due to warnings.
```


I'm going to close this to address the larger issue with this warning (which is complete removal)

**Comment by boneskull** [comment]
> I'm confused, this line has a silly test of the contents of the annoying tesselinclude message—is that definitely the line?

Yes.  I modified the behavior and make some assertions, but regardless of whatever assertions I was making, the tests would pass anyway.  Something fishy going on maybe.  I used npm@3 / Node.js @5.x
