### ISSUE TITLE
WARN Pre-compiled module is missing: bluetooth-hci-socket

### ISSUE THREAD

**Issue by sanderblue** [tessel/t2-cli#652]
Using recommended [USB BLE device](http://www.amazon.com/Plugable-Bluetooth-Adapter-Raspberry-Compatible/dp/B009ZIILLI?ie=UTF8&psc=1&redirect=true&ref_=od_aui_detailpages00)

Output follows with:
```
This might be caused by any of the following:

1. The binary is platform specific and cannot be compiled for OpenWRT.
2. A pre-compiled binary has not yet been generated for this module.
3. The binary didn't compile correctly for the platform that you're developing on.
    It's possible that the binary is Linux-only or even OpenWRT specific,
    try npm installing with "--force" and rerun your deployment command.
```

Error:
```
INFO Running ble.js...
node: '/tmp/remote-script/node_modules/bluetooth-hci-socket/build/Release/binding.node' is not an ELF file
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: File not found
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/node_modules/bluetooth-hci-socket/lib/native.js:1:160)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

```

**Comment by rwaldron** [comment]
Thanks for filing this report. I've precompiled and pushed `bluetooth-hci-socket@0.4.3` to the packages server just now. 

Is there a specific reason that you're not using the `noble` module that's shown here: http://tessel.github.io/t2-start/modules/ble.html?

**Comment by sanderblue** [comment]
@rwaldron, thanks for the quick reply. I went through that quick tutorial step for step and that was the resulting output when running `t2 run ble.js`.

After accessing the Tessel's main OS via  `t2 root` and checking for the proper OpenWRT package dependencies for [noble](https://github.com/sandeepmistry/noble), it seems that `bluez` was the only one that showed up. No results showed up when attempting to search for the following packages - `libbluetooth-dev`, `libudev`, or `udev`. 

Within my Tessel 2
```
root@Ramses:~# opkg list-installed | grep bluez
bluez-libs - 5.30-1
bluez-utils - 5.30-1
```

After some digging within the Tessel repos, I came across the [openwrt-tessel issue #35](https://github.com/tessel/openwrt-tessel/issues/35) as well as [openwrt-tessel issue #36](https://github.com/tessel/openwrt-tessel/issues/36).

Gonna give this a retry in a bit.

**Comment by sanderblue** [comment]
@rwaldron, it looks like your fix worked. Was able to successful run `t2 run ble.js`. Thanks!

```
// ...
INFO Writing project to RAM on Ramses (496.128 kB)...
INFO Deployed.
INFO Running ble.js...
waiting for power up...
beginning to scan...
```


**Note:** Still seeing output regarding `usb` dependency when running the script, but the code is running.
```
WARN Pre-compiled module is missing: usb.
This might be caused by any of the following:

1. The binary is platform specific and cannot be compiled for OpenWRT.
2. A pre-compiled binary has not yet been generated for this module.
3. The binary didn't compile correctly for the platform that you're developing on.
    It's possible that the binary is Linux-only or even OpenWRT specific,
    try npm installing with "--force" and rerun your deployment command.
```

**Comment by rwaldron** [comment]
Ok, I will see about getting that pre-compiled and pushed out as well

**Comment by rwaldron** [comment]
Actually, I'm not seeing any reference there to the usb module? I have to take a 4 hour drive shortly, so I won't be able to help any more until tomorrow

**Comment by sanderblue** [comment]
@rwaldron no worries man. I'm not exactly sure why the `usb` issue is showing up. I have a funny feeling it's because I'm using the USB port + USB pluggable BLE device.

**Comment by peterschmiz** [comment]
We still have the same, original problems mentioned in this thread, we can't it work under Windows 7, the error still exists.

We tried everything, the Tessel has the latest firmware updated.

Any tips?

**Comment by rwaldron** [comment]
@peterschmiz are you trying to `npm install tessel` in your project?

**Comment by peterschmiz** [comment]
I switched to OSX, its working now, haven't made any further tries on Windows, but will try to use tessel package also in my project (right now I didn't installed it)

**Comment by rwaldron** [comment]
No no, do not use the `tessel` package, that's for Tessel 1, not Tessel 2.

**Comment by peterschmiz** [comment]
ok :)
