### ISSUE TITLE
[binary-dep] WARN Pre-compiled module is missing: usb

### ISSUE THREAD

**Issue by sanderblue** [tessel/t2-cli#653]
Using recommended [USB BLE device](http://www.amazon.com/Plugable-Bluetooth-Adapter-Raspberry-Compatible/dp/B009ZIILLI?ie=UTF8&psc=1&redirect=true&ref_=od_aui_detailpages00)

Output follows with:
```
This might be caused by any of the following:

1. The binary is platform specific and cannot be compiled for OpenWRT.
2. A pre-compiled binary has not yet been generated for this module.
3. The binary didn't compile correctly for the platform that you're developing on.
    It's possible that the binary is Linux-only or even OpenWRT specific,
    try npm installing with "--force" and rerun your deployment command.
```

Error:
```
INFO Running ble.js...
node: '/tmp/remote-script/node_modules/bluetooth-hci-socket/build/Release/binding.node' is not an ELF file
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: File not found
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/node_modules/bluetooth-hci-socket/lib/native.js:1:160)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

```

**Comment by johnnyman727** [comment]
Strange that I haven't seen this before, but sure enough, it's as a result of https://github.com/sandeepmistry/node-bluetooth-hci-socket.

It's actually not needed because it's an optional dependency for windows/linux but super annoying. 

Anyone that sees this should just ignore it for now.

**Comment by sanderblue** [comment]
@johnnyman727 Yup, thanks for the reply. I had noticed this was negligible, but like you said, still a bit annoying. I was seeing that warning simultaneously with a `bluetooth-hci-socket` and just posted them as separate issues. 

Here's the [bluetooth-hci-socket thread](https://github.com/tessel/t2-cli/issues/652). @rwaldron quickly took care of the `bluetooth-hci-socket` issue so I closed that one.

**Comment by DamonOehlman** [comment]
Seeing this also when attempting to use the [usb](https://github.com/nonolith/node-usb) package.  Happy for a pointer to instructions on how to hack around and get this working if there are some :)

**Comment by johnnyman727** [comment]
@DamonOehlman `usb` binary dep support is currently hung on https://github.com/tessel/openwrt-tessel/issues/36. If you want to get your hands dirty and investigate, that would be 💯

**Comment by aaronshaf** [comment]
I'm seeing this when not even attempting to use the usb package. I can't get the `t2 init` hello world app to work.

**Comment by sanderblue** [comment]
@aaronshaf This issue shouldn't affect you're ability to run `t2 init`. If you follow [this guide](http://tessel.github.io/t2-start/) to get started, you should be just fine. If you end up seeing any errors at any step, try to diagnose then create a new issue explaining what error you're seeing and at what step the error happened. 

The Tessel team does a good job at responding to issues and helping out.

**Comment by sanderblue** [comment]
@johnnyman727 I'm going to close this issue given it's negligible and really shouldn't affect anyone doing basic dev work with Tessel 2. I've been using a 3rd party BLE module just fine with USB ports on two different Tessels.

**Comment by sanderblue** [comment]
@aaronshaf also, try running `t2 update` and see if that fixes your problem.

**Comment by rwaldron** [comment]
@sanderblue ok to close then?

**Comment by sanderblue** [comment]
@rwaldron sorry, I got distracted. Yep, I'll close now

**Comment by rwaldron** [comment]
Thank you :)
