### ISSUE TITLE
t2 update failed

### ISSUE THREAD

**Issue by majgis** [tessel/t2-cli#654]
Yesterday, I updated to the latest version.  It erased the name I had assigned to my tessel.  In order to reproduce that issue so I could create an issue here, I attempted to rollback to version 0.0.11.  After a long time, my tessel was stuck in an infinite loop of rebooting.  I killed the process, disconnected the power and it is still stuck rebooting.

Is there a way to do a factory reset?  I didn't find anything in the docs to troubleshoot this problem, feel free to point me at any links I missed or offer suggestions on recovery.

```
$ t2 list
INFO Searching for nearby Tessels...
	robbie	USB	

$ t2 update -v 0.0.11
INFO Looking for your Tessel...
INFO Connected to robbie.
INFO Beginning update download. This could take a couple minutes..
  downloading [====================] 100% 0.0s remaining
INFO Download complete!
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 20.19 MB
INFO Starting OpenWRT update. Please do not remove power from Tessel.
^C

$ t2 list
INFO Searching for nearby Tessels...
WARN Detected a Tessel that may be booting.
WARN No Tessels Found.

$ t2 list
INFO Searching for nearby Tessels...
WARN Detected a Tessel that may be booting.
WARN No Tessels Found.
```

**Comment by majgis** [comment]
https://forums.tessel.io/t/t2-update-stuck-on-openwrt-update/2235/5

My bad for not waiting.  Just curious if I can correct my mistake or I'm out of luck?

**Comment by majgis** [comment]
I'm working through these instructions:
https://github.com/tessel/t2-firmware

We'll say this was my fault for not waiting, and it looks like there is a PR to reduce the wait.

**Comment by strawherotk** [comment]
Hi majgis,

Did you find solution for that?
I failed updating Tessel too.
It keep blink the blue LED, and nothing happened.
I tried to find tessel using t2 -list but didn't work.

My log:
`PS C:\Users\10202> t2 update
node-pre-gyp INFO Looking for your Tessel...
node-pre-gyp INFO Connected to TesselBoard.
node-pre-gyp INFO New firmware version found... 0.1.0
node-pre-gyp INFO Updating TesselBoard to latest version (0.1.0)...
node-pre-gyp INFO Downloading files...
node-pre-gyp INFO Download complete!
node-pre-gyp INFO Updating OpenWRT (1/2)
node-pre-gyp INFO Transferring image of size 15.99 MB. This will take 2-4 minutes...
node-pre-gyp INFO Transfer complete.
node-pre-gyp INFO Starting OpenWRT update.
node-pre-gyp INFO Please do not remove power from Tessel.
node-pre-gyp INFO This process will take at least 2 minutes...
node-pre-gyp INFO Configuration is saved during update.
node-pre-gyp INFO Updating firmware (2/2)
node-pre-gyp ERR! Detected CLI crash Error: No device found in bootloader mode
node-pre-gyp ERR!     at C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:364:19
node-pre-gyp ERR!     at new Promise (<anonymous>)
node-pre-gyp ERR!     at USB.Connection._findBootedDeviceBySerialNumber (C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:348:10)
node-pre-gyp ERR!     at Timeout.retry [as _onTimeout] (C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:325:12)
node-pre-gyp ERR!     at ontimeout (timers.js:475:11)
node-pre-gyp ERR!     at tryOnTimeout (timers.js:310:5)
node-pre-gyp ERR!     at Timer.listOnTimeout (timers.js:270:5) Error: No device found in bootloader mode
node-pre-gyp ERR!     at C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:364:19
node-pre-gyp ERR!     at new Promise (<anonymous>)
node-pre-gyp ERR!     at USB.Connection._findBootedDeviceBySerialNumber (C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:348:10)
node-pre-gyp ERR!     at Timeout.retry [as _onTimeout] (C:\Users\10202\AppData\Roaming\npm\node_modules\t2-cli\lib\usb-connection.js:325:12)
node-pre-gyp ERR!     at ontimeout (timers.js:475:11)
node-pre-gyp ERR!     at tryOnTimeout (timers.js:310:5)
node-pre-gyp ERR!     at Timer.listOnTimeout (timers.js:270:5)
undefined
Submit Crash Report to help Tessel Developers improve the CLI ?
    If yes(y), subsequent crashes will be submitted automatically. Yes
node-pre-gyp INFO Crash Reported: http://crash-reporter.tessel.io/crashes?fingerprint=0x493daad6
\

`
