### ISSUE TITLE
Rename files to use either dash or underscore, but not both

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#656]
This is gross, let's fix it.

**Comment by rwaldron** [comment]
Oh, I vote for dashes.

**Comment by LinusU** [comment]
My vote goes to dashes as well :+1:

**Comment by johnnyman727** [comment]
No preference

**Comment by rwaldron** [comment]
I'll pretend that your preference is for dashes ;)

**Comment by wyze** [comment]
I prefer dashes as well. :)
