### ISSUE TITLE
Pre-compiled module is missing: midi and `Could not locate the bindings file`

### ISSUE THREAD

**Issue by albatrocity** [tessel/t2-cli#659]
I'm trying to use the [node-midi](https://github.com/justinlatimer/node-midi) package and I'm getting the `Pre-compiled module is missing: midi.` warning when running `t2 run index.js`. That doesn't stop the build, but it eventually fails with 
```
Error: Could not locate the bindings file. Tried:
 → /tmp/remote-script/node_modules/midi/build/midi.node
 → /tmp/remote-script/node_modules/midi/build/Debug/midi.node
 → /tmp/remote-script/node_modules/midi/build/Release/midi.node
 → /tmp/remote-script/node_modules/midi/out/Debug/midi.node
 → /tmp/remote-script/node_modules/midi/Debug/midi.node
 → /tmp/remote-script/node_modules/midi/out/Release/midi.node
 → /tmp/remote-script/node_modules/midi/Release/midi.node
 → /tmp/remote-script/node_modules/midi/build/default/midi.node
 → /tmp/remote-script/node_modules/midi/compiled/4.2.1/linux/mipsel/midi.node
```

There _is_ a `midi.node` file at `node_modules/midi/build/Release/midi.node`. I've also tried running it with the `--full` flag, which fails with 

```
node: '/tmp/remote-script/node_modules/midi/build/Release/midi.node' is not an ELF file
```

I'm on Node `v5.9.1` and `node-gyp v3.3.1` on OS X. Same error appears with Node `v4.2.1`.

Looks like someone had a [similar issue](https://github.com/justinlatimer/node-midi/issues/89) with this package on a RaspberryPie. 

Any insight into what's causing this? I'm happy to defer this to the `node-midi` repo, just thought it might be handy to have here too. Thanks!

**Comment by johnnyman727** [comment]
Thanks! We need to compile `midi` for T2's architecture (MIPS). @reconbot this is for you.

**Comment by albatrocity** [comment]
Great, thanks @johnnyman727! Excited to get hacking on my new Tessel :smile:

**Comment by rwaldron** [comment]
Compiled and deployed: 

- midi@0.9.4

If you need a different version, we can re-open

**Comment by albatrocity** [comment]
@rwaldron I'm getting `ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory` when trying to initialize the MIDI library.

After a bit of searching, like a driver/kernel thing. Are there any plans to support this sort of connectivity?

* Issue thread for [UDOO](http://www.udoo.org/forum/threads/midi-configuration.1183/)
* [Issue thread](https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/14851) on an Ubuntu support forum

**Comment by johnnyman727** [comment]
@albatrocity thanks for researching that. Would you be interested in installing the kernel dependencies on your T2 and reporting back on whether it works?
You would need to:
- [ ] Connect your T2 to WIFI
- [ ] Run `t2 root` (must be discoverable via LAN with (`t2 list` first)
- [ ] Once you have shell access, use opkg to install MIDI dependencies. [Here](https://gist.github.com/mitsuhito/f54e37a4f17aba1ec49f) is a list with some midi-related deps but I'm not sure which you'll need. You can install them with `opkg install PKG_NAME`.

**Comment by albatrocity** [comment]
@johnnyman727 definitely. Just tried `alas-utils` which didn't seem to affect much. A bunch of the other packages on that list threw `Unknown package` errors. I'll check later on for direct downloads to source. Seems like `alas-utils-midi` and/or `kernel-module-snd-usbmidi` would be relevant.

**Comment by johnnyman727** [comment]
yeah anything with `midi` in the name seems like a good plan :)

**Comment by rwaldron** [comment]
Change `alas` to `alsa`?

```
root@bishop:~# opkg install alsa-utils
Package alsa-utils (1.0.28-2) installed in root is up to date.
```

**Comment by albatrocity** [comment]
@rwaldron just a typo in my issue. I've installed the following with `opkg`:
* `alas-lib`
* `alas-utils`
* `alsa-utils-seq`

I keep getting the `ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory` error, both when attempting to initialize a [node-midi](https://github.com/justinlatimer/node-midi) connection or running `aconnect` from the t2 root.

[This](http://tuxguitar.herac.com.ar/forum/5/825/i-got-problem-with-setting-timidity/) seemed somewhat relevant. Any idea if this is a kernel thing or something with not actually having a sound card that supports MIDI?

**Comment by rwaldron** [comment]
> Any idea if this is a kernel thing or something with not actually having a sound card that supports MIDI?

I honestly don't know :\


Can you paste the output of `lsmod` (ssh to the board to run that)

**Comment by albatrocity** [comment]
```
ac97_bus                 528  1 snd_ac97_codec
arc4                    1312  2 
bluetooth             241598 11 rfcomm
bnep                    8365  2 
btusb                  17808  0 
cdc_acm                13520  0 
cfg80211              213345  2 rt2x00lib
ch341                   3680  0 
compat                  1332  3 rt2800soc
crc16                   1015  1 bluetooth
crc_ccitt               1019  2 rt2800lib
crc_itu_t               1019  0 
crypto_blkcipher       10487  2 ecb
crypto_hash             9698  1 bluetooth
ecb                     1328  0 
eeprom_93cx6            1807  0 
ehci_hcd               31516  1 ehci_platform
ehci_platform           3744  0 
evdev                   8432  0 
fat                    46895  1 vfat
ftdi_sio               28624  0 
gpio_button_hotplug     6000  0 
hci_uart                8799  0 
hid                    79970  3 usbhid
hid_generic              592  0 
hidp                   10961  0 
input_core             24510  4 uvcvideo
ip6_tables              9185  3 ip6table_raw
ip6t_REJECT             1184  2 
ip6table_filter          608  1 
ip6table_mangle         1040  1 
ip6table_raw             576  1 
ip_tables               9389  4 iptable_nat
ipt_MASQUERADE           624  0 
ipt_REJECT               912  2 
iptable_filter           672  1 
iptable_mangle           928  1 
iptable_nat              768  1 
iptable_raw              640  1 
ipv6                  256232 32 nf_conntrack_ipv6
leds_gpio               2896  0 
ledtrig_usbdev          1936  0 
mac80211              378483  3 rt2800lib
nf_conntrack           47691 11 nf_nat_ipv4
nf_conntrack_ftp        5280  1 nf_nat_ftp
nf_conntrack_ipv4       4624  6 
nf_conntrack_ipv6       4944  3 
nf_conntrack_rtcache    2448  0 
nf_defrag_ipv4           806  1 nf_conntrack_ipv4
nf_defrag_ipv6          9031  1 nf_conntrack_ipv6
nf_log_common           2351  2 nf_log_ipv4
nf_log_ipv4             3248  0 
nf_log_ipv6             3376  0 
nf_nat                  8939  5 nf_nat_ipv4
nf_nat_ftp              1216  0 
nf_nat_ipv4             3713  1 iptable_nat
nf_nat_masquerade_ipv4    1372  1 ipt_MASQUERADE
nf_reject_ipv4          1795  1 ipt_REJECT
nf_reject_ipv6          2055  1 ip6t_REJECT
nls_base                5008  6 vfat
nls_cp437               4432  0 
nls_iso8859_1           2896  0 
nls_utf8                 864  0 
ohci_hcd               21951  1 ohci_platform
ohci_platform           3248  0 
option                 26976  0 
pl2303                  6656  0 
ppp_async               6352  0 
ppp_generic            20658  3 pppoe
pppoe                   8112  0 
pppox                   1354  1 pppoe
rfcomm                 27338  0 
rt2800lib              91393  2 rt2800soc
rt2800mmio              6338  1 rt2800soc
rt2800soc               2496  0 
rt2x00lib              34239  5 rt2800soc
rt2x00mmio              1904  2 rt2800soc
rt2x00soc               1202  1 rt2800soc
scsi_mod               85591  3 ums_cypress
sd_mod                 26272  0 
slhc                    4347  1 ppp_generic
snd                    40656 12 snd_usb_audio
snd_ac97_codec         79790  1 snd_intel8x0
snd_compress            6319  0 
snd_hwdep               4558  1 snd_usb_audio
snd_intel8x0           20352  0 
snd_mixer_oss          12601  1 snd_pcm_oss
snd_pcm                60391  4 snd_usb_audio
snd_pcm_oss            33873  0 
snd_rawmidi            15203  1 snd_usbmidi_lib
snd_seq_device          4381  1 snd_rawmidi
snd_timer              14590  1 snd_pcm
snd_usb_audio          93686  0 
snd_usbmidi_lib        15361  1 snd_usb_audio
soundcore               3756  1 snd
ums_alauda              8272  0 
ums_cypress             2256  0 
ums_datafab             4688  0 
ums_freecom             1952  0 
ums_isd200              5040  0 
ums_jumpshot            3632  0 
ums_karma               1536  0 
ums_sddr09              8720  0 
ums_sddr55              4832  0 
ums_usbat               7344  0 
usb_common              1740  1 usbcore
usb_storage            37359 10 ums_usbat
usb_wwan                4391  1 option
usbcore               116724 28 option
usbhid                 21557  0 
usbserial              18043  5 option
uvcvideo               62151  0 
v4l2_common             2966  1 videobuf2_core
vfat                    7840  0 
videobuf2_core         28748  1 uvcvideo
videobuf2_memops        1216  1 videobuf2_vmalloc
videobuf2_vmalloc       2145  1 uvcvideo
videodev               97278  3 uvcvideo
x_tables               10741 26 ipt_REJECT
xt_CT                   2224  2 
xt_LOG                   768  0 
xt_REDIRECT             1056  0 
xt_TCPMSS               2656  0 
xt_comment               480 18 
xt_conntrack            2144  8 
xt_id                    480  0 
xt_limit                 992  2 
xt_mac                   624  0 
xt_mark                  672  0 
xt_multiport            1200  0 
xt_nat                  1072  0 
xt_state                 688  0 
xt_tcpudp               1728  4 
xt_time                 1648  0 
```

**Comment by albatrocity** [comment]
Seeing `snd_seq_device` in there. Now suspecting it's the sound card issue.

**Comment by albatrocity** [comment]
My `/dev/snd` directory only has a `timer` file, no `seq` file.

There's a `--with-sequencer` flag that can be used when compiling `alsa`. I'm not really sure how it gets compiled in the first place, but maybe it's related?

**Comment by johnnyman727** [comment]
@albatrocity perhaps `alsa` should be compiled into the OpenWRT build rather than installed as a package afterwards? I honestly don't know. 

I was looking through the build options (you can get this by cloning https://github.com/tessel/openwrt-tessel, `cd openwrt`, `make menuconfig`, scroll down to "kernel" and found these options:
![screen shot 2016-04-20 at 5 56 53 pm](https://cloud.githubusercontent.com/assets/432909/14694864/7f367e16-0721-11e6-80a5-b543acfb17f5.png)

Once you select the options you want and save, run `make -j50` and it will start compiling. This will take a *long* time. Once you have your build, you can `scp` it to the `/tmp` folder of Tessel and run `sysupgrade PATH_TO_NEW_BINARY`. 

For the sake of convenience, I tried created a build with just the sequencer highlighted but the build failed with:
```
[mktplinkfw2] *** error: rootfs image is too big
```
So this fish might not be useful but the fishing pole above might help.

**Comment by johnnyman727** [comment]
I might also suggest reviewing [this guide](http://www.tldp.org/HOWTO/MIDI-HOWTO-7.html) for ideas.

**Comment by rwaldron** [comment]
@johnnyman727 https://github.com/tessel/openwrt-tessel/blob/master/config.mk#L52-L53 ?

**Comment by johnnyman727** [comment]
Yep, it looks like we already have `alsa` support, but I'm guessing some kernel modules have to be compiling for sequencing.
