### ISSUE TITLE
t2 update: autocheck for out of date CLI

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#661]
..and prompt update if out of date. T1 CLI did this as well as https://github.com/tessel/t2-cli/issues/257 (the same, but for firmware).

Important, because otherwise there's every chance we'll fix something, but users won't know to update for a fix.

**Comment by LinusU** [comment]
I can recommend [update-notifier](https://npmjs.org/packages/update-notifier), it's widely used and it's awesome!

**Comment by Frijol** [comment]
oh, perfect! Thanks!
