### ISSUE TITLE
[docs] add something about grunt or unit tests to readme?

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#666]
@rwaldron is there a proper process contributors should follow with respect to Grunt or adding unit tests when creating a new feature on the CLI? If so, this would be great to have in the readme.

**Comment by rwaldron** [comment]
Yes, this is a good idea.

**Comment by rwaldron** [comment]
@HipsterBrown is pretty awesome at docs writing, so I'm going to assign this one to him and he can accept it or not ;)
