### ISSUE TITLE
Show LAN / USB first when running "t2 list"

### ISSUE THREAD

**Issue by dudleyjosh** [tessel/t2-cli#669]
This is just for aesthetics, but I think it would make more sense to show LAN / USB then the name of the t2 device... it would be consistent and easier to read this way.

```
USB     name
LAN     name
LAN     a_longer_name
```
vs
```
name     USB
name     LAN
a_longer_name     LAN
```

**Comment by johnnyman727** [comment]
I also like this suggestion. @dudleyjosh do you prefer this suggestion or https://github.com/tessel/t2-cli/issues/409?

**Comment by dudleyjosh** [comment]
@johnnyman727 either way I think the connection type should be shown first, it would be nice to have it output in such a way that it looks like they are in columns for ease of readability... perhaps just add spaces to the output of the connection type if it only has one of the connections?

```
USB/LAN     name
USB             a_longer_name
```

**Comment by rwaldron** [comment]
I didn't mean to assign myself. I want to assign @dudleyjosh, but I also just remembered that @github still doesn't support assigning arbitrary users. Blah.

@dudleyjosh this is all you. Let me know if you need any help. 

- https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L107
- https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L230-L235

Both places need to be updated with your new ordering. This might cause tests to fail, so you'll need to update them if they do. Ping me on slack if you want to DM for guidance

**Comment by dudleyjosh** [comment]
Closed with PR-671
