### ISSUE TITLE
unable to run t2 list

### ISSUE THREAD

**Issue by vic317yeh** [tessel/t2-cli#670]
I got this error when I attempted to run t2 list:

t2-cli/bin/tessel-2.js:14
}).notify();
^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Any idea on what's going on?

**Comment by HipsterBrown** [comment]
@vic317yeh what version of Node are you using? 

You can find out by running `node -v` in your command line.

**Comment by vic317yeh** [comment]
v0.10.28

**Comment by HipsterBrown** [comment]
Ok. The minimum requirement for the cli is v4.2.0. [Reference](https://github.com/tessel/t2-cli/blob/master/package.json#L83)

**Comment by vic317yeh** [comment]
Got it. Thanks!

**Comment by vic317yeh** [comment]
@HipsterBrown Sorry I still have no ideas what I'm doing. I got the following error when running t2 list

node(5786,0x7fff7db00300) malloc: *** error for object 0xffffffff: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by HipsterBrown** [comment]
@vic317yeh I would try re-installing the cli now that you've upgraded your version of node. That can affect some of the cli's dependencies.

**Comment by vic317yeh** [comment]
I downgraded my node to 5.1 and it worked! Thanks!
