### ISSUE TITLE
[root] Need more clear "No-LAN" error message

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#672]
You can only use the `t2 root` command when your Tessel is detectable over mDNS. We need to have a more clear error message if someone runs `t2 root` and a connection is found over USB but not LAN. Something like "The `root` is only functional over LAN connections but we only found a USB connection to your Tessel. Please connect your Tessel to Wifi with `t2 wifi -n SSID -p PASS`. See `t2 help` for more info`.

**Comment by aaronshaf** [comment]
This bit me this morning.

**Comment by johnnyman727** [comment]
@aaronshaf, this was *sorta* fixed by https://github.com/tessel/t2-cli/commit/ef0a5e2ae0a1439b33c757927a9f4f4a64f3502a. 

Assuming you're on the latest version of the CLI, did you see those warnings? Do you feel like more is needed?

**Comment by johnnyman727** [comment]
I'm going to mark this as fixed for now.
