### ISSUE TITLE
Fix spelling error of `tesselFirmwareVerion`

### ISSUE THREAD

**Issue by wyze** [tessel/t2-cli#682]
See incorrect spelling here: [lib/controller.js#L941](https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L941)

While I am in there, since it displays node version as well. Would just `tesselVersion` or `tesselVersions` (plural) be a more appropriate name?

cc @rwaldron

**Comment by rwaldron** [comment]
Maybe even... `tesselEnvVersions`?

**Comment by rwaldron** [comment]
Do up a patch with "Fixes gh-682" in the commit message and I'll land it as soon as it's green

**Comment by wyze** [comment]
That works too.

**Comment by rwaldron** [comment]
Is it accurate though? Push back if you think not.

**Comment by wyze** [comment]
Might not be. When I hear environment variables. I think more like flags. `NODE_ENV=production` or `PORT=3001`. I think, in this case, you wouldn't set the version this way.

On the other hand, the versions here define the environment you are working with. So, really, I think it could go either way.

**Comment by wyze** [comment]
I thought about it a little more, and `tesselVersions` could be construed as versions of Tessel, ie. 1 or 2.

And `tesselEnvVersions` more accurately describes the environment within Tessel which you are working with.

**Comment by rwaldron** [comment]
I agree with that. `tesselEnvVersions` it is!

I have to step out for a bit, so if I don't follow land right away, no worries—I will do it as soon as I have a chance :)

**Comment by wyze** [comment]
Sounds good and no worries!
