### ISSUE TITLE
Adding Contributors to package.json

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#686]
I think we should add the list of contributors to the `package.json`as described by [NPM](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)

**Comment by johnnyman727** [comment]
I don't have very strong opinions about this but I think it can be kind of annoying to have to update the package.json so often. As long as new contributors do so when submitting their patches (or in a subsequent PR), it shouldn't be a problem. I'm curious about how other medium/large open-source projects handle this.

**Comment by rwaldron** [comment]
@johnnyman727 I've maintained the contributors list in johnny-five for over 4 years and it's not that bad. We might even consider making a grunt task to manage it for us.

**Comment by rwaldron** [comment]
Looks like @scottgonzalez has already made such a thing: https://www.npmjs.com/package/grunt-git-authors.

**Comment by scottgonzalez** [comment]
Indeed. That module is designed to work with `AUTHORS.txt`, but I'd be fine adding a `updatePackageJson()` similar to the `updateAuthors()` method. You could also use the `getAuthors()` method and do the `package.json` update manually. If you'd like the new method, feel free to file an issue or PR and I'll get a new version out ASAP.

**Comment by HarleyKwyn** [comment]
Automation makes me smile. I say it'd be awesome to do this.

**Comment by johnnyman727** [comment]
@scottgonzalez issue filed! https://github.com/scottgonzalez/grunt-git-authors/issues/8

**Comment by scottgonzalez** [comment]
Thanks. I'll work on that tonight. Shouldn't take long, so I'll likely have a new version published tonight as well.

**Comment by rwaldron** [comment]
@scottgonzalez 👏 thank you sir :)

**Comment by scottgonzalez** [comment]
I just published grunt-git-authors@3.2.0 which adds an `update-contributors` Grunt task and an `updatePackageJson()` method for standalone use.

**Comment by rwaldron** [comment]
@scottgonzalez do you want to do the patch for t2-cli to introduce that?

**Comment by scottgonzalez** [comment]
Sure.
