### ISSUE TITLE
[crash-reporter] Crashes reported before being displayed

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#691]
I'm running into an issue where a crash is being reported to the crash reporter service but the CLI is not actually displaying the error that was thrown.

Steps to reproduce:
```
mkdir audio
cd audio
t2 init
npm install tessel-av
wget http://www.stephaniequinn.com/Music/Vivaldi%20-%20Spring%20from%20Four%20Seasons.mp3 -O vivaldi.mp3
echo vivaldi.mp3 >> .tesselinclude
t2 run index.js
```
Output:
```
➜  audio t2 run index.js
INFO Looking for your Tessel...
INFO Connected to lyon.
INFO Building project.
INFO Writing project to RAM on lyon (550.4 kB)...
INFO Crash Reported: http://crash-reporter.tessel.io/
```

Perhaps an error is being thrown by the remote Node process and it's being gobbled by the crash reporter?

**Comment by rwaldron** [comment]
Did you try this with the crash reporter off?

**Comment by tikurahul** [comment]
That should not happen. Let me make sure that we don't swallow the real error. Also I should really update the message that says `Crash Report submitted at...` to include the fingerprint. We have that information.

**Comment by tikurahul** [comment]
Oops. Fat fingered the close issue button. My apologies. 🙃

**Comment by johnnyman727** [comment]
> Did you try this with the crash reporter off?

@rwaldron No, not yet but will do.

Also reported here: https://forums.tessel.io/t/red-error-led-on-boot-and-blue-led-blinking-forever/2401/4?u=jon
