### ISSUE TITLE
"No Tessel Found" when t2 list

### ISSUE THREAD

**Issue by sharkee89** [tessel/t2-cli#701]
I have one problem that is failry straightforward to explain. 

I brought a new Tessel 2 hardware plug it via mini USB port and install node and npm. Also I do installation from tessel website instruction: 

- apt-get install libusb-1.0-0-dev libudev-dev
- npm install -g t2-cli

After I try 't2 list' to see my connected tessel hardware it says "WARN: No Tessel found".

I was searching for that in the internet but didn't find the appropriate answer.

My OS is Ubuntu Linux.

Do you maybe have some anwser, solution or suggestion because it is really frustrating because it fails on start.

Thanks.

**Comment by sharkee89** [comment]
I did install-drivers and now on t2-list I get "INFO Crash Reported: http://crash-reporter.tessel.io/".

Regarding the LED it is turned on a blue led and green one near the WLAN plug.

**Comment by johnnyman727** [comment]
@sharkee89 out of curiosity, does `sudo t2 list` print out your USB Connection?

**Comment by johnnyman727** [comment]
> Regarding the LED it is turned on a blue led and green one near the WLAN plug. The yellow and red LEDs are turned on upon plugin but then they turn off.

Is the Blue LED pulsating or solid blue?

**Comment by sharkee89** [comment]
@johnnyman727 sudo t2 list is not working.

Regarding blue LED it is first pulsating (during initialization process) and then it is solid one. The Tessel is fully functional because it is working on my MAC but on the other one Ubuntu laptop it is not. 

I have to cases:

t2 list
INFO Crash Reported: http://crash-reporter.tessel.io/

and

sudo t2 list
INFO Searching for nearby Tessels...
WARN Detected a Tessel that may be booting.
WARN No Tessels Found.

**Comment by johnnyman727** [comment]
Can I see the output from when you run `npm install t2-cli -g`?

**Comment by sharkee89** [comment]
@johnnyman727 Sorry to bother you I repeated all the install process with sudo and then sudo t2 list is working I even uploaded the code on Tessel and run blinking example. 

Thanks for help, I still don't know what is the problem because without sudo is not working anything (and on my MAC everything is working out of the box without sudo).

Thanks again..

**Comment by sharkee89** [comment]
Here is the output you asked:

sudo npm install -g t2-cli

/usr/local/bin/t2 -> /usr/local/lib/node_modules/t2-cli/bin/tessel-2.js

> t2-cli@0.0.19 postinstall /usr/local/lib/node_modules/t2-cli
> t2 install-drivers || true

INFO Crash Reported: http://crash-reporter.tessel.io/
/usr/local/lib
└── t2-cli@0.0.19

**Comment by johnnyman727** [comment]
Okay thanks a ton - so to be clear - you had to use `sudo` for the `npm install` and every `t2` command in order to get it to work on Ubuntu?

**Comment by sharkee89** [comment]
Yes. And it is working only for now. Maybe it was something to do with this because I unplug and plug again the Tessel via MicroUSB after install drivers.

**Comment by johnnyman727** [comment]
> And it is working only for now

What do you mean by this? It's not working consistently after the install with `sudo`?

**Comment by sharkee89** [comment]
Sorry. I meant it began to work after various numbers of reinstalling t2-cli and drivers.

**Comment by johnnyman727** [comment]
Okay - so you actually ran `sudo npm install t2-cli -g` previously and it did not yield a working CLI?

**Comment by sharkee89** [comment]
Yes it was not working. But I made a mistake because whole time my Tessel was connected to the computer.

**Comment by johnnyman727** [comment]
So you had to:

1. Have the T2 disconnected from USB
2. `sudo npm install t2-cli -g`
3. Plug in T2 via USB
4. `t2 list`

Is that correct?

**Comment by sharkee89** [comment]
Actually:

1. Have the T2 disconnected from USB
2. sudo apt-get install libusb-1.0-0-dev libudev-dev
3. sudo npm install -g t2-cli
4. sudo t2 install-drivers
5. Plug in T2 via USB
6. sudo t2 list

That worked for me.

**Comment by johnnyman727** [comment]
Okay, thank you!

**Comment by sharkee89** [comment]
No worries, thank you again on help.
