### ISSUE TITLE
list should list IP address for LAN with --verbose flag

### ISSUE THREAD

**Issue by huseyinkozan** [tessel/t2-cli#705]
Hi,
It will be very good to get the IP address with _t2 list_ for LAN devices. I cannot find any option to get currnet IP addresses of the device. Maybe adding VID:PID and USB device address for the USB devices be informative.

**Comment by rwaldron** [comment]
https://tessel.io/docs/cli#using-wifi

> #### USING WIFI
> `t2 wifi` show details about an existing WiFi connection


From mine, right now: 

```
$ t2 wifi
INFO Looking for your Tessel...
INFO Connected to maria.
INFO Connected to "JLY4Q_EXT"
INFO IP Address: 192.168.1.13
INFO Signal Strength: (70/70)
INFO Bitrate: 43mbps
```


> Maybe adding VID:PID and USB device address for the USB devices be informative.

How so?

**Comment by johnnyman727** [comment]
@huseyinkozan do you feel like it would be more intuitive if we also had the IP Address in `t2 list`?

The reason we did not add it was because (in theory) the user shouldn't have to worry about it. Once we improve `t2 list` capabilities on more networks, it could be a non-issue.

**Comment by wyze** [comment]
What about adding a `--verbose` flag to `t2 list` command and that could give more information, like IP address?

**Comment by johnnyman727** [comment]
@wyze I think the real problem is poor documentation. There is currently nowhere to look to find out how to print the IP Address. It could be helped with https://github.com/tessel/t2-cli/issues/722.

**Comment by huseyinkozan** [comment]
@johnnyman727 : In my opinion `t2 list` is the right place to state the IP information. Listing is actually resolving the IP address (with mdns?). You may add a new column for addresses.

@wyze : I prefer directly see the address.

**Comment by johnnyman727** [comment]
I'm going to go ahead and close this issue because I'd prefer not to make `t2 wifi` redundant. Thanks for the input everyone!
