### ISSUE TITLE
run and push should use the main from package.json

### ISSUE THREAD

**Issue by finnp** [tessel/t2-cli#717]
Hey :)

I'm couldn't find an existing issue for this, but I think it would be nice when `t2 run` would parse the package.json in the current working directory and push the `main` file.

I can send a PR if you think this is a good idea :)

Best,
Finn

**Comment by tikurahul** [comment]
@finnp We have been talking about it here (https://github.com/tessel/t2-cli/issues/716). If you want to take a stab at it, please send us a PR. :cookie:

**Comment by johnnyman727** [comment]
@finnp what if the user wants to run a file within a project that's not the main file (like `examples/ambient.js`)? We should run the file that they explicitly call out in that case.

In the case that some runs `t2 run` without any arguments, I think it makes sense to run the `main` file as parsed from the `package.json`. The CLI in its current form will actually do that if you do `t2 run .` from the root directory.

**Comment by rwaldron** [comment]
> In the case that some runs t2 run without any arguments, I think it makes sense to run the main file as parsed from the package.json

I like this, but I vaguely recall discussing this before... I might be imagining that. While I think that would be nice, @tikurahul is right in calling out the multi-language support, which would have impact here

**Comment by rwaldron** [comment]
Here's where I landed on this: 

- If `--single` is `true`, allow pushing the file specified from the CWD. No package.json necessary, remote is not cleared before deployment.
- If `--single` is `false` and no package.json present and the file exists in CWD, and the `pushdir` fails to be determined by the existing algorithm, assume the user literally wants to push the `<file>` from the CWD.
