### ISSUE TITLE
t2 list --lan should dedupe output

### ISSUE THREAD

**Issue by boneskull** [tessel/t2-cli#719]
When your local machine has *n* network interfaces connected to the same network, each Tessel will show *n* times in the resulting list (in theory):

```shell
$ t2 list --lan
INFO Searching for nearby Tessels...
	LAN	bloath	(USB connect and run `t2 provision` to authorize)
	LAN	bloath	(USB connect and run `t2 provision` to authorize)
```

See the single machine:

```shell
$ arp bloath.local
? (10.0.0.22) at 2:a3:60:d1:47:44 on en4 ifscope [ethernet]
? (10.0.0.22) at 2:a3:60:d1:47:44 on en0 ifscope [ethernet]
```

I'm also wondering if you have your Tessel plugged into ethernet *and* connected via WiFi, it won't show 2*n* times...?  It'd certainly have two different IP's and MAC addresses...

**Comment by rwaldron** [comment]
Yikes, definitely needs to be deduped. 

Start here: https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L93-L107

**Comment by johnnyman727** [comment]
Thanks for bringing this up @boneskull!
