### ISSUE TITLE
`t2 list` crashes and hangs when board is first connected

### ISSUE THREAD

**Issue by dlindahl** [tessel/t2-cli#720]
When running `t2 list` immediately after plugging in a board, the cli crashes and hangs:

##### No boards plugged in
```
> t2 list
INFO Searching for nearby Tessels...
WARN No Tessels Found.
```

##### Board plugged in and `t2 list` immediately run
```
> t2 list
INFO Searching for nearby Tessels...
INFO Crash Reported: http://crash-reporter.tessel.io/
^CWARN No Tessels Found.
```

`Ctrl-C`'d after ~4-minutes

##### Board plugged in and `t2 list` run 1-second or so afterwards
```
> t2 list
INFO Searching for nearby Tessels...
	USB [NAME]	
```

Obviously not a common path, but the fact that the crash reporter is hanging may be of interest.

**Comment by johnnyman727** [comment]
@dlindahl thanks for the report. What OS/Version are you running? Also what version of Node are you on?

**Comment by dlindahl** [comment]
El Cap with Node 5.1.0. Tho I think I heard that might be too high and have
since downgraded to 4.2.4. I'll test again when I'm back near a computer.

**Comment by rwaldron** [comment]
@dlindahl yeah, nvm to 4.4.x and try. If there are further issues, please report here. 

Also, since I know you're the curious and motivated type: you can/should clone this repo, do `npm install && npm link` and then try the same commands and see if the latest still has the issue.

**Comment by johnnyman727** [comment]
To add to @rwaldron's comment - if you do clone locally, make sure you re-run `npm install` between changing your Node versions because you will need to recompile the `usb` module.

**Comment by rwaldron** [comment]
Ah! Yes—thank you @johnnyman727 for catching that

**Comment by dlindahl** [comment]
I installed `t2-cli` locally, `link`'d it up and received the same results.

Let me know if there is anything else I can do to assist!

**Comment by johnnyman727** [comment]
@dlindahl can you `npm uninstall t2-cli -g` and then re-run `npm install -g t2-cli` and post the output of the latter command here?
