### ISSUE TITLE
better cli help

### ISSUE THREAD

**Issue by GuidoS** [tessel/t2-cli#722]
Could the bin possibly use yargs to document commands and options? I would be happy to help make this happen, just want to make sure that this type of update would be accepted as a pull request. My thought is that yargs does a really nice job of self documenting commands and options and the current '-h' help option is pretty lacking.

**Comment by johnnyman727** [comment]
@GuidoS I agree with you completely about the poor --help output. We've been meaning to switch to `commander` for a while but haven't gotten around to it. Would you be willing to do that instead of `yargs`?

**Comment by johnnyman727** [comment]
Since October in fact! https://github.com/tessel/t2-cli/issues/356

**Comment by GuidoS** [comment]
I would like to convince you that yargs is a better choice:
- It's a more  active a project (last updated 19 days ago) (from [npmcompare](https://npmcompare.com/compare/commander,minimist,nomnom,optimist,yargs))
- it's got json argument passing, similar to what you have already done in nomnom

**nomnom**

```javascript
    .option('timeout', {
        abbr: 't',
        metavar: 'TIMEOUT', // not sure what this is for?
        help: 'Set timeout in seconds for scanning for networked tessels',
        default: 5   
    })
```

**commander**   

```javascript
  .option('-t, --timeout', 'Set timeout in seconds for scanning for networked tessels')
  // no default options
```

**yargs**

```javascript
  .option('size', {
    alias: 't',
    describe:'Set timeout in seconds for scanning for networked tessels',
    default: 5
  }
```

- I have used yargs on other projects and it is very newb friendly
- Pirate themed, but no actual pirates (cause real pirates were frightening and not fun)

**Comment by johnnyman727** [comment]
Sounds reasonable to me! :+1:

**Comment by GuidoS** [comment]
To be clear, if i spend the time making this update, and it works, you can
assure me that it will be accepted?

**Comment by johnnyman727** [comment]
Yeah, I am okay with it but I don't have much experience with `yargs`. @rwaldron or @LinusU or @Frijol or @HipsterBrown might have more experience and thus objections. I'd say wait 24 hours and if you don't hear any dissent from them, we're good to go.

**Comment by HipsterBrown** [comment]
I believe we were looking to switch to `commander` because of [deprecation notice](https://github.com/harthur/nomnom#deprecation-notice) in the `nomnom` repo. Based on @GuidoS's reasoning, it looks like `yargs` would be an easier transition and more approachable for new contributors. :+1: for the update.

**Comment by wyze** [comment]
I've only ever used [meow](//github.com/sindresorhus/meow), but if Sindre recommends `yargs` (https://github.com/tessel/t2-cli/issues/356#issuecomment-146196189), then I say that would be good enough for us. 👍

**Comment by rwaldron** [comment]
Re: metavar... https://github.com/harthur/nomnom#metavar

**Comment by johnnyman727** [comment]
@guido since nobody has strong opinions, let's move forward with 'yargs'.

**Comment by GuidoS** [comment]
OK, I will get going on this next week, I'm slammed right now...

**Comment by GuidoS** [comment]
I am new to contributing code with these community tools. I have setup a branch on my personal fork and am working there:
https://github.com/GuidoS/t2-cli/tree/bin-yargs-integration

Once I have the functionality fully functional I will do a pull request. Is this the correct way to do this? Is there a CONTRIBUTE.md somewhere?

**Comment by wyze** [comment]
Yes, it is just in a different repo: https://github.com/tessel/project/blob/master/CONTRIBUTING.md

And then you will also need to sign the [CLA](http://dojofoundation.org/about/claForm).

**Comment by GuidoS** [comment]
I have signed it ;)

**Comment by johnnyman727** [comment]
@GuidoS were you able to make any progress on this?

**Comment by bcoe** [comment]
@johnnyman727 @GuidoS I'm a [little biased](https://github.com/yargs/yargs/commits?author=bcoe), so not going to make too noisy of a pitch for yargs. But, I'm here to help if you need me.

**Comment by GuidoS** [comment]
This has been back burnered for me. I will make some time this weekend to get the ball rolling and would be happy to get support from others.

**Comment by GuidoS** [comment]
looks like this was deprecated, so I will happily close this.
