### ISSUE TITLE
blacklist `tessel` module 

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#725]
I'm thinking it might be a good idea to blacklist the `tessel` module from deploys because I've seen many people get confused about whether or not it's needed (since you always `require('tessel')`), it's a really big package (something like 23 MB), and it currently won't compile one of its binary deps properly.

If someone *does* actually want to use it for running the Tessel 1 CLI, they can explicitly add it to their `.tesselinclude`. @rwaldron what do you think?

**Comment by rwaldron** [comment]
I think that's a super smart idea.
