### ISSUE TITLE
WARN Pre-compiled module is missing: fsevents

### ISSUE THREAD

**Issue by sanderblue** [tessel/t2-cli#731]
If requiring the filesystem Node module (`var fs = require('fs')`), I am receiving the following warning. 

```
WARN Pre-compiled module is missing: fsevents.
This might be caused by any of the following:

1. The binary is platform specific and cannot be compiled for OpenWRT.
2. A pre-compiled binary has not yet been generated for this module.
3. The binary didn't compile correctly for the platform that you're developing on.
    It's possible that the binary is Linux-only or even OpenWRT specific,
    try npm installing with "--force" and rerun your deployment command.
```

I can still execute my program without issues, but wanted to surface the warning. If I get some extra time, I can dig into the issue and possibly attempt to fix.

**Comment by jsimmonds2** [comment]
Similar: I had very similar problem for 'usb'
when pushing a simple script . . . but I'm on Fedora Linux 23 (virtual)

**Comment by johnnyman727** [comment]
@sanderblue, I'm not able to reproduce. Here is what I'm doing:
```
t2 init
echo "var fs = require('fs');" > index.js
t2 run index.js
```
It just executes as normal. How can I reproduce your issue?

@jsimmonds2 I think you're likely having a separate issue. Make sure you do not have the `tessel` module in the node_modules folder of your project - you don't need it. The module is hosted on T2 itself.

**Comment by rwaldron** [comment]
Why would the built in `var fs = require('fs')` be associated with `fsevents`?

> WARN Pre-compiled module is missing: fsevents.

Not, `fs` ;)

Also... `fsevents` is for OSX, not OpenWRT, so there is nothing to be done here. Don't use `fsevents` in your Tessel 2 application code, because it's not compatible with the operating system on the board.

**Comment by sanderblue** [comment]
You're correct. My bad.  I went down the line and cleaned up my `package.json` file and found the true culprit. It was the `nunjucks` library that had `fsevents` as a dependency.
