### ISSUE TITLE
[minimization] extract-opts package cannot be pushed as slim

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#734]
I was attempting to use the [`getmac`](https://www.npmjs.com/package/getmac) module which has a dependency of [`extract-opts`](https://www.npmjs.com/package/extract-opts). This dependency is not able to be deployed to Tessel without a slim flag because of the strange way it exports modules:

```
module.exports = require('esnextguardian')(
    require('path').join(__dirname, 'esnext', 'lib', 'index.js'),
    require('path').join(__dirname, 'es5', 'lib', 'index.js'),
    require
)
```

See the source code [here](https://github.com/bevry/extract-opts/blob/master/esnextguardian.js#L4-L8).

**Comment by rwaldron** [comment]
This isn't something we can do anything about. There is no way for the dependency to be statically resolved—that needs to be changed in the module. (That module code would have the same problem with browserify or webpack). I've found that module authors are super open to changes that make their module usable by Tessel 2 applications.

**Comment by johnnyman727** [comment]
@rwaldron that's seems reasonable. I'm happy to open a PR on this repo. Do you know why authors would write something like that? How is it better than just `require('module')`?

**Comment by LinusU** [comment]
> why authors would write something like that?

Some reasoning here, I personally don't think it's a good idea to ship to versions of the module though...

https://www.npmjs.com/package/esnextguardian

**Comment by rwaldron** [comment]
> I'm happy to open a PR on this repo. Do you know why authors would write something like that? How is it better than just require('module')?

The issue not _why_ they are doing it, but _how_. Take a look at this: https://github.com/rwaldron/johnny-five/pull/464/files

**Comment by johnnyman727** [comment]
Well, I'll go ahead and close this issue since it's not something we can solve by modifying the CLI.

**Comment by LinusU** [comment]
> The issue not why they are doing it, but how. 

This is not exactly the same thing though, they are conditionally loading only one of two files depending on some runtime variable. I'm not sure that they'll be happy to `require` both since that will negate some of the effect of splitting it up in the first place...

**Comment by rwaldron** [comment]
Conditional requires won't specifically break anything though... I guess I'll just have to try it and see what happens
