### ISSUE TITLE
t2 crash-reporter: do not register process event handlers unless crash-reporter is "on". 

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-cli#735]
These are compelling enough to flip crash-reporter into "opt-in": 

- https://github.com/tessel/t2-cli/issues/714
- https://github.com/tessel/t2-cli/issues/730

**Comment by tikurahul** [comment]
Will patching `0.0.19` with https://github.com/tessel/t2-cli/pull/696 help ? 
At least they will be able to look at the contents of the crash and the crash report.

**Comment by rwaldron** [comment]
Actually, yes I think we should release that first before making crash reporter "opt-in". Thanks for reminding

**Comment by johnnyman727** [comment]
Going to close this for now. @rwaldron feel free to re-open if you think this is still a need.
