### ISSUE TITLE
Automatic crash submission vs privacy

### ISSUE THREAD

**Issue by flaki** [tessel/t2-cli#745]
This was raised (legitimately) as a issue at today's workshop.

We should have an opt-in for this (or something) during CLI install, alternatively we could ask _before_ submitting each crash.

It would be also nice to log the data to the console that's going to be submitted in the crash report.

**Comment by tikurahul** [comment]
We have an opt out which is exposed via the CLI. We should make that option more prominent. 

We also log the unsanitized stack that we are about to submit as long as you are using a recent version of the CLI, as well as the URL to the crash report (which should tell you exactly what we collected). 

I agree that the first time we submit a crash report, we might want to prompt them and tell them about what is going to happen. I will take that as an action item. Do you think that is sufficient?

--

Making the crash reporter opt-in would greatly reduce its usefulness. We have discovered many problems proactively.

**Comment by johnnyman727** [comment]
Fixed with #749.
