### ISSUE TITLE
t2 push ends with error ENOENT: no ... 'sys'

### ISSUE THREAD

**Issue by huseyinkozan** [tessel/t2-cli#757]
Hello,

I got this error message after `t2 push`:
```
ERR! Error: ENOENT: no such file or directory, open 'sys'
```

I could repeat the case with these steps. I hope you can.

* $ mkdir t2-test && cd t2-test
* $ t2 init
* Append this dependencies to `package.json`:
     <pre>
  "dependencies": {
    "body-parser": "^1.15.0",
    "buffer-layout": "^0.13.0",
    "cookie-parser": "^1.4.1",
    "diskspace": "^1.0.2",
    "express": "^4.13.4",
    "fs-extra": "^0.30.0",
    "moment-timezone": "^0.5.4",
    "multer": "^1.1.0",
    "node-json-db": "^0.7.2",
    "node-monkey": "^0.2.16",
    "semantic-ui": "^2.1.8",
    "serialport": "^3.1.2",
    "string": "^3.3.1"
  }</pre>
* Include this lines to `index.js` after `require('tessel')`:
    <pre>
    var express = require('express');
    var body_parser = require('body-parser');
    var layout = require('buffer-layout');
    var cookie_parser = require('cookie-parser');
    var diskspace = require('diskspace');
    var fs_extra = require('fs-extra');
    var moment_timezone = require('moment-timezone');
    var multer = require('multer');
    var node_json_db = require('node-json-db');
    var node_monkey = require('node-monkey');
    var string = require('string');</pre>
* Add `node_modules/serialport` in to `.tesselignore`. Cannot find serialport binary, I prefer skip. I am using [serialport](https://www.npmjs.com/package/serialport) at PC and `require('tessel')` at Tessel.
* $ t2 push index.js

I tried to debug the case, but could not find a general solution. I wrote something at #support channel at Slack. You can find my debug trials in this gist:
https://gist.github.com/huseyinkozan/7d07dce450512662563f2ac337ec94a0

Finally I made a temporary hack to `t2-project`. These are the steps:

* $ npm install -g t2-cli
* Edit file : `/opt/node/lib/node_modules/t2-cli/node_modules/t2-project/lib/index.js`:
      Change this line:
      ```
      filter: (file) => state.filters.every(filter => filter(file)),
      ```

      With this lines:
      ```
      filter: (file) => {
          if (file === 'sys') return false;
          return state.filters.every(filter => filter(file))
      },
      ```

My configuration :
* Node Version : v6.2.0
* NPM Version : 3.8.9
* Tessel Node Version : 6.1 (OpenWRT image is grabbed from [this pull request](https://github.com/tessel/openwrt-tessel/pull/58) )
* OS Version : Ubuntu 14.04 x86_64.

**Comment by HipsterBrown** [comment]
@huseyinkozan Thanks for making this issue. I will investigate this error this weekend.

**Comment by huseyinkozan** [comment]
Thank you @HipsterBrown. Hope to improve.

**Comment by rwaldron** [comment]
I'm afraid that I'm not convinced this is a bug in t2-cli or t2-project. What code is using `sys`? The module that t2-project is using to provide a list of built-ins is blacklisting `sys`

**Comment by huseyinkozan** [comment]
Actually I dont know which one is using. I gave my dependency list to reproduce the error. Cant you repeat it @rwaldron ?

**Comment by rwaldron** [comment]
Yes, it reproduces consistently. I want to figure out who the culprit is! This is nuts!

**Comment by rwaldron** [comment]
https://www.npmjs.com/package/redis is conditionally requiring `sys`, unfortunately `module-deps` doesn't know how to resolve conditional require. I'm going to patch this in t2-project

**Comment by rwaldron** [comment]
Here's an explanation of the entire bug: https://github.com/rwaldron/t2-project/blob/master/lib/index.js#L14-L30
