### ISSUE TITLE
t2 rename

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#77]
Current status: no such command

Spec: [T2 CLI spec](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743)
**tessel rename <name> [-r | --reset]**

Names the Tessel by changing the hostname of the device. Name restrictions found here: http://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names
```sh
$ tessel rename
> Usage: tessel rename <name> [-r | --reset] [--help]
>  name:		the name to rename the currently selected tessel
>  -r | --reset:	reset the name of the device
$ 

$ tessel rename Jigglypuff
> Changed name of device Tessel-0123456789ab to Jigglypuff
$ 

$ tessel rename Snorlax
> Changed name of device Jigglypuff to Snorlax
$ 

$ tessel rename --reset
> Reset the name of device to Tessel-0123456789ab
$ 
```

* [ ] rename
* [ ] reset name to MAC address
* [ ] make sure hostname is valid based on hostname restrictions

**Comment by Frijol** [comment]
Is `--force` needed here @nplus11 ?

**Comment by nplus11** [comment]
nope!

**Comment by johnnyman727** [comment]
I can build this feature.
