### ISSUE TITLE
Question: Stop a script while is running

### ISSUE THREAD

**Issue by pmcalabrese** [tessel/t2-cli#775]
Hello everyone,
I'm building and IDE extension for Visual Studio Code, and it's basically a wrapper for the t2-cli. I would like to programmatically stop a script that is running on the Tessel 2 (launched with `t2 run`) without the CTRL+C, is that possible? Or any other suggestions?

Thank you in advance

**Comment by rwaldron** [comment]
First, this is totally awesome. 

Second... there is no command that `t2-cli` could provide that would unambiguously determine which node process was started by another run of `t2-cli` in order to terminate the process (because there could be other node processes, or even > 1 `t2 run` or `t2 push` process). Let's leave this open and think about it a bit more

**Comment by pmcalabrese** [comment]
@rwaldron Thank you. Here is a sneak peek! I'll opensource it in few days ... everything works well enough but i would like to find a way to communicate better to the user when something goes wrong.

![image](https://cloud.githubusercontent.com/assets/1509241/16258358/d1189b16-385d-11e6-99c1-6350dc0a693c.png)

This problem I've highlighted is the one i really cannot solve, right now i need to unplug and plug back the Tessel board... but I really would like to avoid that. I was wondering if it's possible to grab the pid of  `t2 run` or `t2 push` node processes.

**Comment by pmcalabrese** [comment]
I did not solved the issue yet, but... there is a repo now :). Is not in Visual Studio Code Extension Market place yet, but it will came soon, I'd love to publish it on the market after i solved it.

https://github.com/pmcalabrese/vsce-tessel

**Comment by pmcalabrese** [comment]
I've solved the problem. Basically instead of execFile, I can use spawn which allows you to kill the process with the .kill() method where you can also pass kill signals.

**Comment by johnnyman727** [comment]
I can't wait to try this when I'm re-united with my Windows machine. @pmcalabrese when do you plan to publish to the market?

**Comment by pmcalabrese** [comment]
It's already there
https://marketplace.visualstudio.com/items?itemName=pmcalabrese.vsce-tessel

but consider yourself a beta tester, my team and me are using it, and we know that is not finished 👍
