### ISSUE TITLE
t2 erase console.logs edit

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#78]
Current status: erases everything in /app folder

Spec: [T2 CLI spec](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743)
**tessel erase**

Erases files pushed to Flash using the tessel push command.
```sh
$ tessel erase --help
> Erases files pushed to Flash using the tessel push command.
$ 

$ tessel erase
> Erasing files from flash...
> Files erased
$ 
```

To do:

* [ ] console.log edit to match spec
* [ ] --help flag

**Comment by Frijol** [comment]
Is deleting /app the same as erasing the code pushed to Flash? In other words, does changing the console.log fully resolve this issue?

**Comment by johnnyman727** [comment]
Deleting /app will obviously remove the script that would run on boot but you need to also call `etc/init.d/tessel-app stop` to make sure that openWRT doesn't attempt to run the script on bootup.

I don't think that necessarily answers the root of your question though. I do believe this is just a `console.log` output change for the `--help` flag (which doesn't exist at this time) and the output when the command is run.

**Comment by Frijol** [comment]
Ok, it already does that. So this issue is just a console.log edit.
