### ISSUE TITLE
Unable to program T2 over LAN

### ISSUE THREAD

**Issue by ShawnHymel** [tessel/t2-cli#781]
t2-cli version 0.0.21

```
sgmustadio@ifrit MINGW64 /c/Users/sgmustadio/Documents/NodeJS/j5ik
$ t2 list
INFO Searching for nearby Tessels...
        LAN     squirtle
        USB     squirtle

sgmustadio@ifrit MINGW64 /c/Users/sgmustadio/Documents/NodeJS/j5ik
$ t2 run exp_07a.js --lan
INFO Looking for your Tessel...
WARN No Authorized Tessels Found.
```

I'm on an enterprise WLAN guest network.

**Comment by HipsterBrown** [comment]
@ShawnHymel Have you tried running `t2 run exp_07a.js --lan` again right after that warning. Sometimes, it doesn't discover on the first attempt but if it was found by `t2 list` then it should find that Tessel again.

**Comment by ShawnHymel** [comment]
Yup, that seemed to work, thanks!

**Comment by HipsterBrown** [comment]
We have an issue tracking the LAN discovery problems folks are having on some networks/systems, so I'm going to close this issue since this seems like a duplicate now. Thanks for bringing it up, I'm glad that was a quick resolution for now.

**Comment by rwaldron** [comment]
@ShawnHymel @HipsterBrown thanks for the quick resolution. @HipsterBrown do we have this troubleshooting tip somewhere in the docs?

**Comment by HipsterBrown** [comment]
@rwaldron No tips in the docs but I believe there is an issue to do that. Will take a look this weekend.
