### ISSUE TITLE
t2 restart does not work properly for code in Flash

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#785]
I ran `t2 restart index.js --type=flash` and expected it to re-run code that was in Flash. The problem is that we deploy to [`/app/remote-script/`](https://github.com/tessel/t2-cli/blob/34a16f5ad03e8aa8e6a7aa61e234096b4c3d0ec7/lib/tessel/deploy.js#L319) but when we try to restart with the `flash` flag we [check for code in `/app`](https://github.com/tessel/t2-cli/blob/34a16f5ad03e8aa8e6a7aa61e234096b4c3d0ec7/lib/tessel/deploy.js#L194). The CLI reports that the specified entry point does not exist.

**Comment by rwaldron** [comment]
We can't change the path from `/app/remote-script`, because the shell scripts are created in the `/app/` directory before the contents of `/tmp/remote-script` are moved.

**Comment by rwaldron** [comment]
I'll have a patch for this by tomorrow morning.
