### ISSUE TITLE
Tessel 2 Not Detected on Win7

### ISSUE THREAD

**Issue by ivelin-andreev** [tessel/t2-cli#788]
Hi all,

I have a brand new Tessel 2 which I did not manage to run on my HP Elitebook machine.
1. Followed the initial instructions with no luck - driver could not be installed even with windows update
2. Then followed the instructions here: https://gist.github.com/tcr/992978a5dbe5bff2e18f495c5c0973c3
and here: https://github.com/tessel/t2-cli/issues/742
At the end it does not seem as tessel is detected at all, although some kind of USB driver was installed after following the instructions from the first link.

The result is as below: (**The err led turns on and the error below is displayed.**)

node driver-install.js
note: make sure t2 is in dfu-util mode (hold down the reset button while plugging in)

Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
Cannot open DFU device 1209:7551
No DFU capable USB device available
child_process.js:507
    throw err;
    ^

Error: Command failed: dfu-util-static.exe -a0 -d 1209:7551 -D firmware-winusb.bin
Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
Cannot open DFU device 1209:7551
No DFU capable USB device available

    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at Object.<anonymous> (C:\Users\ivelin.andreev\Downloads\driver clean\t2-windows-fix\t2-windows-fix\driver-install.js:8:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by johnnyman727** [comment]
Hi @ivelin-andreev, sorry to hear that you're having trouble. Can you post the output from [these steps](https://github.com/tessel/t2-cli/issues/742#issuecomment-220487881)? I know you said you already tried this route but it would be useful to see what failed exactly.

**Comment by ivelin-andreev** [comment]
Hi Jon, 

I just wanted to test with yet another computer (not mine) and the experience was 100% the same.
Then the board is plugged in - drivers cannot be installed automatically.

1. I am currently running node.js v.6.2.2 (as of node -v). The friend on whose laptop I tried was running 5.*
2. After downloading the t2-windows-fix. Here is the output of **node driver-clean.js**

devcon-x64.exe remove "@USB\VID_1209&PID_7551&MI_00\7&37E956E8&1&0000"
USB\VID_1209&PID_7551&MI_00\7&37E956E8&1&0000               : Removed
1 device(s) were removed.

devcon-x64.exe remove "@USB\VID_1209&PID_7551&MI_01\7&37E956E8&1&0001"
USB\VID_1209&PID_7551&MI_01\7&37E956E8&1&0001               : Removed
1 device(s) were removed.

devcon-x64.exe remove "@USB\VID_1209&PID_7551&MI_02\7&37E956E8&1&0002"
USB\VID_1209&PID_7551&MI_02\7&37E956E8&1&0002               : Removed
1 device(s) were removed.

devcon-x64.exe remove "@USB\VID_1209&PID_7551\JQ6PK0Q928S16BMC4SCS3Z07TS"
USB\VID_1209&PID_7551\JQ6PK0Q928S16BMC4SCS3Z07TS            : Removed
1 device(s) were removed.

t2 drivers have been uninstalled.

done. you can now run node driver-install.js with t2 in dfu mode.
(hold the reset button while plugging in t2 to enter this mode)

3. I hold the SW401 button on the board and plug it in the USB while holding. Windows shows "Device driver software not successfully installed". The Err led is on with very pale light(not sure whether this indicates anything)

4. The result of **node driver-install.js** is below: (most probably it indicates that DFU was not successful)

note: make sure t2 is in dfu-util mode (hold down the reset button while plugging in)

Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
No DFU capable USB device available
child_process.js:529
    throw err;
    ^

Error: Command failed: dfu-util-static.exe -a0 -d 1209:7551 -D firmware-winusb.bin
Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
No DFU capable USB device available

    at checkExecSyncError (child_process.js:486:13)
    at execSync (child_process.js:526:13)
    at Object.<anonymous> (C:\Users\ivelin.andreev\Downloads\t2-windows-fix\t2-windows-fix\driver-install.
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)

**Comment by johnnyman727** [comment]
@ivelin-andreev I just realized the start experience doesn't say this (and I created [an issue](https://github.com/tessel/t2-start/issues/137)) but you need to use Node LTS (4.x) in order to use the CLI.

**Comment by ivelin-andreev** [comment]
@johnnyman727 

Hi, unfortunately this does not solve the problem
1. I uninstalled node.js and installed v4.4.4
2. Followed the instructions on https://gist.github.com/tcr/992978a5dbe5bff2e18f495c5c0973c3 
3. Uninstall went OK but node driver-install.js does not and gives the same error:
(Note: I of course keep the SW401 button pushed while plugging in the USB and release it few seconds after the board is plugged in)
note: make sure t2 is in dfu-util mode (hold down the reset button while plugging in)

Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
Cannot open DFU device 1209:7551
No DFU capable USB device available
child_process.js:507
    throw err;
    ^

Error: Command failed: dfu-util-static.exe -a0 -d 1209:7551 -D firmware-winusb.bin
Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
Cannot open DFU device 1209:7551
No DFU capable USB device available

    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at Object.<anonymous> (C:\Users\ivelin.andreev\Downloads\t2-windows-fix\t2-windows-fix\driver-install.js:8:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by ivelin-andreev** [comment]
@johnnyman727 
I have a bit of a progress following instructions on another thread:
https://forums.tessel.io/t/tessel-2-driver-issues-on-windows-10/2238/158

The key was on 4A - when opening Zadig to:
1) open Options menu and select "List All Devices" and "Advanced Mode" (to show logging info)
2) Select Tessel 2 DFU
3) Click to install driver and watch for progress
4) For me it failed to make Windows restore point and put out a number of strange messages while waiting 5 minutes. The installation timed out and a log for failure was recorded.  
(my first attempt failed because my Windows Update service was turned off but I understood it from the log.)
5) However after plugging out Tessel board and plugging it in again a popup window appeared from the task bar saying that Tessel 2 DFU driver installation succeeded.
6) Ran the node driver-install.js in CMD and the output seemed to be OK

note: make sure t2 is in dfu-util mode (hold down the reset button while plugging in)

Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
unable to read DFU status after completion
dfu-util 0.8

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

Opening DFU capable USB device...
ID 1209:7551
Run-time device DFU version 0101
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0101
Device returned transfer size 256
Copying data from PC to DFU device
Download        [=========================] 100%        14736 bytes
Download done.
state(7) = dfuMANIFEST, status(0) = No error condition is present

firmware flashing complete.

**Comment by ivelin-andreev** [comment]
@johnnyman727 

Now there seems to be another problem , when trying the sample servo code to verify everything is running as expected:
1) t2 update seems to update but shows an error:

> INFO Looking for your Tessel...
> INFO Connected to Tessel-02A3E328629C.
> INFO New firmware version found...0.0.13
> INFO Updating Tessel-02A3E328629C to latest version (0.0.13)...
> INFO Beginning update download. This could take a couple minutes..
>   Downloading [====================] 100% 0.0s remaining/
> INFO Download complete!
> INFO Updating OpenWRT (1/2)
> INFO Transferring image of size 19.14 MB. This will take 2-4 minutes...
> INFO Transfer complete.
> INFO Starting OpenWRT update.
> INFO Please do not remove power from Tessel.
> INFO This process will take at least 2 minutes...
> INFO Configuration is saved during update.
> INFO Updating firmware (2/2)
> ERR! Detected CLI crash { [Error: LIBUSB_TRANSFER_STALL] errno: 4 } Error: LIBUSB_TRANSFER_STALL
> ERR!     at Error (native)
> undefined
> Submit Crash Report to help Tessel Developers improve the CLI ?
> INFO Firmware update complete!hes will be submitted automatically. (Y/n) \
> INFO Updated Tessel-02A3E328629C from  0.0.11  to  0.0.13

2) t2 version shows that firmware has been updated.

> INFO Looking for your Tessel...
> INFO Connected to Tessel-02A3E328629C.
> INFO Tessel [Tessel-02A3E328629C] CLI version: 0.0.23
> INFO Tessel [Tessel-02A3E328629C] Firmware version: 0.0.13
> INFO Tessel [Tessel-02A3E328629C] Node version: 4.4.3

3) when running the sample servo code:

> INFO Looking for your Tessel...
> INFO Connected to Tessel-02A3E328629C.
> INFO Building project.
> INFO Writing project to RAM on Tessel-02A3E328629C (10.24 kB)...
> INFO Deployed.
> ERR! Error writing preference cli.entrypoint servo.js
> ERR! Error: ENOENT: no such file or directory, open 'C:\Users\[user]\.tessel\preferences.json'

I read through some check-ins and especially https://github.com/tessel/t2-cli/issues/750
but it seems this is not fixed in my version

https://github.com/tessel/t2-cli/pull/751/files

**Comment by rwaldron** [comment]
> I read through some check-ins and especially #750 but it seems this is not fixed in my version

There is another related patch being released later today

**Comment by ivelin-andreev** [comment]
@rwaldron & @johnnyman727 

In C:\Users\\[user]\\AppData\Roaming\npm\node_modules\t2-cli\lib

I have the following: 
var preferencesJson = path.join(os.homedir(), '.tessel', 'preferences.json');

Would you please let me know how to run the code on a Windows machine? How are other users running this code?

Is the patch going to be generally available as latest version or it is a kind of a branch I should get?

**Comment by ivelin-andreev** [comment]
@johnnyman727 , @rwaldron 

Guys do you have any input on that - a workaround or a fix?

**Comment by johnnyman727** [comment]
@ivelin-andreev just FYI, a new version of the CLI has been released that fixes the problem you worked around.

**Comment by ivelin-andreev** [comment]
Thanks, I am working on it now :)
