### ISSUE TITLE
Deduce security type

### ISSUE THREAD

**Issue by huseyinkozan** [tessel/t2-cli#802]
I did a guess function to get security which can passed to connection function:

```
function guessSec(security) {
    var s = S(security);
    if (s.contains('none')) { return 'none'; }
    if (s.contains('WPA2') && s.contains('PSK')) { return 'psk2'; }
    if (s.contains('PSK')) { return 'psk'; }
    if (s.contains('WPA2')) { return 'wpa2'; }
    if (s.contains('WPA')) { return 'wpa'; }
    if (s.contains('WEP')) { return 'wep'; }
    return 'none';
}
```
Note: S is stringjs.

**Comment by johnnyman727** [comment]
Thanks @huseyinkozan. Feel free to open a PR with your change.

**Comment by rwaldron** [comment]
@HipsterBrown how does this factor into your latest security type work?

**Comment by HipsterBrown** [comment]
So I have logic like this in an open PR to `t2-firmware` when getting network information (https://github.com/tessel/t2-firmware/pull/195/files#diff-84087272b70af9498872cf6f791003abR1441). This could be added to the information returned by `t2 wifi` and `t2 wifi --list` to match the security values used when connected to a network.

**Comment by rwaldron** [comment]
Since we can't actually use this code as-is and no PR was ever opened, I'm going to close this and we can site the OP as a contributing author whenever it becomes appropriate to do so.

**Comment by huseyinkozan** [comment]
Sorry, I am so busy now. Maybe later : ^ (
