### ISSUE TITLE
t2 update

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#81]
Current status: no such command

Spec: [T2 CLI spec](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743)
**tessel update [-l | --list] [-b | --build] [-f | --force]**

Updates tessel to most recent build if it’s not already on that build, displays info including when tessel was last updated, when build was published

```sh
$ tessel update --help
> Usage: tessel update [-l | --list] [-b | --build]
>  -l | --list:	show the last five builds and current build
>  -b | --build:	update to a specific build
>  -f | --force:	force tessel to update to the specified version
$ 

$ tessel update
> New firmware version found...
> Updating Bulbasaur to latest build...
> Updated Bulbasaur from v0.3.12 to v0.3.14
$ tessel update
> Bulbasaur is already on the latest firmware build. You can force an update with “tessel update --force”
$ 

$ tessel update -b
> Usage: tessel update -b <build_number>
> Example: “tessel update -b 0.3.12”
> tessel update -b 0.3.12
> Updating Bulbasaur to v0.3.12...
> Updated Bulbasaur to v0.3.12
$ 

$ tessel update -l
> Latest builds:
>  v0.3.14 Published 04/1/2015 03:35:57
>  v0.3.13
>  v0.3.12 Bulbasaur last updated 03/31/2015 08:22:03
>  v0.3.11
>  v0.3.10
>  v0.3.09
$ tessel update
> New firmware version found...
> Updating Bulbasaur to latest build...
> Updated Bulbasaur from v0.3.12 to v0.3.14
$ tessel update -l
> Latest builds:
>  v0.3.14 Bulbasaur last updated 03/31/2015 08:22:03 to latest firmware
>  v0.3.13
>  v0.3.12 
>  v0.3.11
>  v0.3.10
>  v0.3.09
$ 
```

* [x] update to latest build
* [x] list builds
* [x] update to specific build

**Comment by kevinmehall** [comment]
There are two pieces of firmware to deal with: coprocessor firmware and openwrt image.

For the coprocessor half of this: #109

**Comment by johnnyman727** [comment]
@kevinmehall what's the easiest way to update the OpenWRT image? The co-processor can just overwrite the SPI Flash, correct?

**Comment by kevinmehall** [comment]
It can, but that also erases all the settings and data in the overlay partition. If you run the `sysupgrade` command, it backs up the data, performs the update, and restores it.

**Comment by johnnyman727** [comment]
Okay great. Does it matter which chip gets updated first? My instinct would be to update the co-processor first but I can't really articulate why.

**Comment by kevinmehall** [comment]
It usually won't matter, except if there's a breaking change in the bridge protocol and you're updating over USB, in which case you should update OpenWrt first while you can still get to it via the old coprocessor firmware.

**Comment by johnnyman727** [comment]
I'd like to suggest a couple of changes to the print out of this command:

For `t2 list`, I believe it should print release dates next to each version.

I also think that it should not print the exact time Tessel was updated to a specific version. This is a fair amount of work for some text that's not entirely useful.

**Comment by Frijol** [comment]
Track progress here: https://github.com/tessel/t2-cli/pull/231
