### ISSUE TITLE
Link to t2-cli docs broken

### ISSUE THREAD

**Issue by lyzadanger** [tessel/t2-cli#812]
Hi! The README directs one to the t2-cli docs repository for documentation on t2-cli usage:

> See docs on T2 CLI usage on the t2-docs repo.

The link here (https://github.com/tessel/t2-docs/blob/master/cli.md) is broken. I can get to https://github.com/tessel/t2-docs but it looks like I'd need to clone the repo and build to get docs.

Is there another link that could be dropped in here to point at quick-reference docs (assuming they exist)? I'd submit a PR but am not sure what link should really go here.

**Comment by lyzadanger** [comment]
One candidate: https://tessel.gitbooks.io/t2-docs/content/API/CLI.html

But again, not sure if that's a good place to direct folks?

**Comment by HipsterBrown** [comment]
Thanks for catching this @lyzadanger :clap:

That link probably broke when we switched the docs over to GitBook. We could continue to link to the markdown version of the CLI documentation (https://github.com/tessel/t2-docs/blob/master/API/CLI.md) or the full documentation site (https://tessel.io/docs/cli redirects to the correct page in the GitBook). 

My instinct is for linking the gitbook docs to avoid breaking the links if the file structure changes in the `t2-docs` repo again. I would like to get @Frijol's feedback on that idea as well.
