### ISSUE TITLE
t2 wifi needs filling out

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#82]
Current status:
* tessel wifi -l lists networks
* tessel wifi -n -p copies the wifi network into the configuration file, but doesn't check to see if the network/password are valid or if we connect

Spec: [T2 CLI spec](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743)
**tessel wifi**

```sh
$ tessel wifi -h
> Usage: tessel wifi [-l] [-n <ssid>] [-p <pass>] [-s <security>] [--off] [-t]
>  -l:			list available networks
>  -n <ssid>:	name of the network to connect with
>  -p <pass>:	password to access network
>  -s <security>:	security protocol to connect with (i.e. WEP, WPA, PSK)
>  -t:			attempt to connect for the provided number of seconds
>  --off:		disconnect from a wifi connection
$ 

$ tessel wifi
> Connected to "technicallyWifi"
> IP Address: 192.168.128.149
> Signal Strength: 27/70
> Bitrate: 145mbps up / 24 mbps down

$ tessel wifi
> Not Connected (run 'tessel wifi -l' to see available networks)

$ tessel wifi -l
> INFO Requesting wifi status...
> Currently visible networks (10):
>	Gaumenkitzel (47/127)
>	XFBSECA7HE6H (30/127)
>	HP-Print-8f-LaserJet 200 color (49/127)
>	technicallyWifi (40/127)
>	tessel (38/127)
>	KeetsaBerkeley (37/127)
>	ATT219_EXT (38/127)
>	xfinitywifi (38/127)
>	CableWiFi (32/127)
>	Max4 (30/127)

$ tessel wifi -n test-network
> Connecting to network “test-network”...
> Connected to network “test-network”
$ 

$ tessel wifi -n test-network -p super-secret
> Connecting to network “test-network”...
> Failed to connect to “test-network” (ssid or password incorrect)
$ tessel wifi -n test-network -p secret
> Connecting to network “test-network”...
> Connected to network “test-network”
$ 

$ tessel wifi -n test-network -p secret -s WPA
> Connecting to network “test-network”...
> Connected to network “test-network”
$ 

$ tessel wifi -n test-network -t 1
> Connecting to network “test-network”...
> Failed to connect to “test-network” (timeout)
$

$ tessel wifi --list
> Currently connected to “test-network”
> Scanning for wifi connections...
>  technicallyWifi (67/75)
>  test-network (65/75) [connected]
>  Gaumenkitzel (33/75)
$
```

To do:

* [x] tessel wifi
* [x] tessel wifi --help
* [ ] -s flag
* [x] -t flag
* [ ] --off flag
* [ ] check whether network/password authenticate and whether the Tessel connects
* [x] Show connection status, IP address, signal strength, bitrate

**Comment by Frijol** [comment]
@johnnyman727 did you have further ideas for the `-l` command, re bitrate etc?

**Comment by johnnyman727** [comment]
According to the spec, there is no bitrate log for `-l`. I was mistaken (it's part of `tessel wifi`).

**Comment by nplus11** [comment]
We already agreed somewhere to remove `tessel status -c` I think it was in the doc.

**Comment by johnnyman727** [comment]
Just adding a note for anyone that's looking that connecting to an open network doesn't work yet!

**Comment by johnnyman727** [comment]
Another note that a recently flashed image of OpenWRT doesn't by default have `encryption` set as `psk` and the current wifi credential setting logic doesn't set it either. I had to go in and manually add that. Once this feature is completed, this shouldn't be an issue.

**Comment by johnnyman727** [comment]
@kteza1 What's the best way to confirm that setting the WiFI credentials was successful with openWRT? We could parse `ifconfig` after some timeout but that seems hacky.

**Comment by kteza1** [comment]
How do you make sure if connection is successful using `ifconfig`? By checking for ip address on wlan0 interface? I've tried some uci commands but none them shows ip address on wlan interface on my raspberry pi running openwrt. Will check if there is any other way to get this other than using ifconfig

**Comment by kteza1** [comment]
Here is what I tried on my raspberry pi which is in client mode

Before connection

```
ubus call wireless.network status

{
	"radio0": {
		"up": true,
		"pending": false,
		"autostart": true,
		"disabled": false,
		"config": {
			"channel": "11",
			"hwmode": "11g",
			"path": "platform\/bcm2708_usb\/usb1\/1-1\/1-1.2\/1-1.2:1.0",
			"htmode": "HT20",
			"txpower": 20,
			"country": "00"
		},
		"interfaces": [
			
		]
	}
}
```
After connecting it to my router 

```
{
	"radio0": {
		"up": true,
		"pending": false,
		"autostart": true,
		"disabled": false,
		"config": {
			"channel": "11",
			"hwmode": "11g",
			"path": "platform\/bcm2708_usb\/usb1\/1-1\/1-1.2\/1-1.2:1.0",
			"htmode": "HT20",
			"txpower": 20,
			"country": "00"
		},
		"interfaces": [
			{
				"section": "@wifi-iface[0]",
				"ifname": "wlan0",
				"config": {
					"ssid": "OpenWrt",
					"encryption": "psk",
					"mode": "sta",
					"bssid": "E8:94:F6:68:59:8E",
					"key": "abc@12345",
					"network": [
						"wwan"
					]
				}
			}
		]
	}
}
```

**Comment by johnnyman727** [comment]
Thanks @kteza1! So you're suggestion is to poll the `ubus call wireless.network.status` until it shows connected. Do you know if it's possible to tell if the password for a network is incorrect (rather than poor signal strength)?

**Comment by johnnyman727** [comment]
Also, @kteza1 do you know other security options folks might be interested in besides `psk2`?

**Comment by johnnyman727** [comment]
@Frijol there is no simply way to utilize `nomnom`'s built in `usage` print out if no arguments/flags are provided. 

What do you think about just printing:
```
ERR! No arguments provided. Type tessel wifi -h for usage information. 
```
if a user tries `t2 wifi`. 

The other alternative is to do the same as `t2 wifi -l`.

**Comment by Frijol** [comment]
I'm confused. From the spec above, this is what `tessel wifi` is meant to do with no flags:

```
$ tessel wifi
> Connected to "technicallyWifi"
> IP Address: 192.168.128.149
> Signal Strength: 27/70
> Bitrate: 145mbps up / 24 mbps down

$ tessel wifi
> Not Connected (run 'tessel wifi -l' to see available networks)
```

**Comment by johnnyman727** [comment]
@Frijol Yes, you're correct. Not sure how I misread that!

**Comment by johnnyman727** [comment]
@MrNice is going to take a stab at this one!

**Comment by MrNice** [comment]
@Frijol #282 Implements "tessel wifi", but doesn't do any bitrate log analysis, only reports what iwinfo reports when invoked.

**Comment by Frijol** [comment]
moved to https://github.com/tessel/t2-cli/pull/362

**Comment by Frijol** [comment]
Closing in favor of the three bite-sized issues linked above ^
