### ISSUE TITLE
Error submitting crash report

### ISSUE THREAD

**Issue by kaefer3000** [tessel/t2-cli#838]
I often get the error in:
````
$ t2 list
INFO Searching for nearby Tessels...
 	USB	Tessel-02A38E068B3D	
ERR! Error submitting crash report Property argv is required undefined
````
even if everything looks fine to me (like in the example provided)

**Comment by rwaldron** [comment]
@tikurahul there was no follow up here: https://github.com/tessel/t2-cli/pull/834 about the argv addition. We can't have hard-required fields that produce errors in the CLI

**Comment by tikurahul** [comment]
Sorry., i accidentally introduced a bug in the service. Will fix asap.

**Comment by tikurahul** [comment]
Crash reporting service also has error notifications turned on (so I now the next time if I introduce a bug). It feels like I am on call again 😄

**Comment by rwaldron** [comment]
@tikurahul thanks for fixing this so quickly! I've just landed the argv addition and will have @HipsterBrown do a release today

**Comment by tikurahul** [comment]
Awesome. Let me add labels and argv to the GitHub issue as well. Thanks @rwaldron
