### ISSUE TITLE
t2 update did not terminate although it completed

### ISSUE THREAD

**Issue by kaefer3000** [tessel/t2-cli#839]
My tessel updated successfully, but after the following line in the log, the spinning dash did never finished:

```
INFO Updated Tessel-02A38E068B3D from  0.0.12  to  0.0.13
```

I Ctrl+C'ed the process and the tessel is fine.

**Comment by rwaldron** [comment]
Thanks for the report. 

Looks like it's not resolving the operation

**Comment by ducks** [comment]
@rwaldron I am seeing this too and have been digging for a fix in https://github.com/tessel/t2-cli/issues/852.

I see this every time updating from 0.0.13 (the version mine shipped with and the upgrade path I originally saw this on) and back down to 0.0.16.

I had (still kind of do) the feeling that it was something not resolving right but the promise chain gets deep quickly.

It seems like https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L991 is the final step and so https://github.com/tessel/t2-cli/blob/master/bin/tessel-2.js#L88 should resolve to the successful command function which stops the spinner but it just doesn't.

**Comment by rwaldron** [comment]
Hi @ducks, I'm traveling until next week. I will take a look as soon as I can

**Comment by akrigline** [comment]
Greetings @ducks @rwaldron 
Figured I'd add my report to the mix, I just experienced the same thing updating from 0.0.13 to 0.0.16 on mine.

**Comment by Frijol** [comment]
@rwaldron are these two duplicate? https://github.com/tessel/t2-cli/issues/852

**Comment by rwaldron** [comment]
@Frijol yes
