### ISSUE TITLE
Upgrade to Node 6

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#842]
Per 
![image](https://cloud.githubusercontent.com/assets/454690/18174138/75676904-703a-11e6-93b6-ab61d0121143.png)

It's going to LTS in October, and we should move with it

**Comment by Frijol** [comment]
related:  https://github.com/tessel/t2-cli/issues/830

**Comment by HipsterBrown** [comment]
I believe this was resolved by the release of v0.0.29.
