### ISSUE TITLE
2 Tessels plugged in, CLI can find both but one of them hangs

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#850]
My left USB port Tessel just hangs trying to execute. Sample output:

```sh
➜  t2-cli git:(adhoc) t2 wifi --off
INFO Looking for your Tessel...
INFO Connected to Mariano.
INFO Connected to trendelmame.
/ (spinning)
```
indefinitely.

Works ok if I disconnect one of the two. I believe the one that hangs is always the one that connected second.

@HipsterBrown says he ran into this as well

**Comment by johnnyman727** [comment]
Probably a duplicate of #721.
