### ISSUE TITLE
t2 list

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#86]
Current status:

* prints out USB devices and LAN devices
* takes a timeout flag
* shows authorization status of tessels
* doesn't show which tessel is selected

Spec: [T2 CLI spec](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743)
**tessel list**

Lists all connected tessels. Shows which tessel is selected and authorization status of each tessel.

Find default per https://github.com/tessel/t2-cli/issues/93
```sh
# Help command example
$ tessel list --help
> Lists all connected tessels. Shows which tessel is selected and authorization status of each tessel.
$ 

# Single Tessel found example
$ tessel list
> Searching for nearby Tessels...
>           Jigglypuff    USB
$ 

# Same Tessel with both USB and LAN connections
$ tessel list
> Searching for nearby Tessels...
>           Jigglypuff    USB
>           Jigglypuff    LAN
$ 

# Many Tessels available
$ tessel list
> Searching for nearby Tessels…
>            Rafael        LAN
>            Bulbasaur     USB       (run `tessel provision` to authorize)
>            Mewcat        LAN       (USB connect and run `tessel provision` to authorize)
>            Jigglypuff    USB
>            Jigglypuff    LAN
>
> Multiple Tessels found. Will default to Bulbasaur.
> Set default Tessel with environment variable (e.g. export TESSEL=Bulbasaur) or use the --name flag.
$ 

# No Tessels available
$ tessel list
> Searching for nearby tessels...
> ERR! No Tessels Found
$
```

Option: tessel list -t to set a timeout

To do:
* [x] Change functionality to display both authorized and unauthorized devices
* [ ] Change printout style to match spec (layout, connection, authorization, hostname)
* [ ] Remove timeout flag
* [ ] Show which tessel is selected
* [ ] Make help flag match spec

**Comment by nplus11** [comment]
I don't think the most important piece is the connection type. The name of the device should come first.

Also it should probably mention that `tessel provision` should be used via USB. First thing user is going to run after reading this is something like `tessel provision Mewcat`

**Comment by Frijol** [comment]
Sure, switching the order seems like a good idea. Maybe even:

```sh
[selected] Rafael       LAN
           Bulbasaur    USB       (run `tessel provision` to authorize)
           Mewcat       LAN       (USB connect and run `tessel provision` to authorize)
           Jigglypuff   USB/LAN
```

**Comment by nplus11** [comment]
Printing format needs to be updated. I recommend using the following: https://www.npmjs.com/package/sprintf

**Comment by Frijol** [comment]
Should also error out consistently if no Tessels are found, similar to run:

```sh
➜  t2-cli git:(kb-run) ✗ t2 list
INFO Scanning for connections...
➜  t2-cli git:(kb-run) ✗ t2 run test/test-deploy-script.js
INFO Connecting to Tessel...
ERR! No Tessels Found
➜  t2-cli git:(kb-run) ✗
```

**Comment by johnnyman727** [comment]
I've started implementing parts of this in my efforts towards #72.

**Comment by johnnyman727** [comment]
I'd like to propose a change to the intended functionality for `t2 list`. I think that by default `t2 list` should run indefinitely and print out Tessels as it finds them:
```
> t2 list
INFO Searching for nearby Tessels... CTRL+C to stop
INFO    Hippo    USB
INFO    Frog  	 LAN
/ <---- this is a spinner
```
The reason behind this is that we don't know how long it will take to detect a Tessel over the LAN using mDNS. In my experience, with our current timeout of 1.5 seconds, `t2 list` will find my Tessel ~75% of the time. I also like it better because wireless devices show up as soon as they're found rather than them all showing up a few seconds after the command is run. It just feels faster and more responsive.

If we do this, we won't necessarily be able to show users which Tessel would be 'selected' (the Tessel that would be chosen if they performed an action like `tessel run`) because the devices are coming in asynchronously. We could still have a default timeout for these commands upon Tessels and encourage folks to set the TESSEL_NAME env variable so we could start executing on the device as soon as it's found, before the timeout is hit, to speed up development.

Thoughts? @nplus11 @frijol @rwaldron @tcr

**Comment by Frijol** [comment]
Codifying from a past discussion – I don't think it's a good idea to have it run indefinitely for a couple of reasons:

1. Users shouldn't have to cancel out of the process – too much complexity & not a natural action when things are working right. We should just set a reasonable timeout and let them set a longer/different timeout as an option.
1. Since we have to run the tessel list command with a timeout and come up with a selected tessel when we run any commands using the tessel anyway, it makes more sense for tessel list to show the same behavior as other commands.

**Comment by Frijol** [comment]
From what I understand, you're looking for input on what the readout should look like?
I think this depends on the outcome of https://github.com/tessel/t2-cli/issues/93, did this ever get resolved?

**Comment by johnnyman727** [comment]
Yeah, the heuristics at the top of the issue are up to date.

**Comment by adkron** [comment]
If there is going to be a spinner could this be an curses screen? The user could then move up and down the list and have buttons like p for provision, w for wifi, u for update, etc.

**Comment by adkron** [comment]
Could use https://github.com/chjj/blessed for a curses interface.

**Comment by johnnyman727** [comment]
@adkron as is, t2 list just prints out all found Tessels. When you try to do something to a Tessel (like `t2 run`), the CLI will use a set of heuristics to deduce which Tessel you want to use (USB Tessel is more likely than unauthorized LAN, etc.). If it can't determine which to use, then the user is presented with an interface that lets them move up and down to select the Tessel they want.

**Comment by adkron** [comment]
I didn't know that it gave a menu. Since I only have one Tessel. Is there a way to force the menu. That is nice.

**Comment by Student007** [comment]
> Is there a way to force the menu. That is nice.

@adkron no it isn't - but if you like to play around with this, you can use https://github.com/tessel/t2-vm and duplicate the VMs with new Hardware-Addresses. The workflow:
1) `t2-vm create`
2) open the VirtualBox  GUI
3) Clone the Tessel-VM with option selected to create new hardware addresses for all network devices
4) start the VM out of VirtualBox GUI
5) use `t2 list` to find out the virtual Tessels name
6) `t2 rename NewTesselName1`
7) start from 3)
