### ISSUE TITLE
ECONNREFUSED on simple blink tutorial

### ISSUE THREAD

**Issue by patrickkeenan** [tessel/t2-cli#860]
I'm 10 minutes into playing with my new tessel. Seems its already broken. Any help here?

I pushed a previous project with tessel-av which is when the problems started. But now,even when I erase and run the blink project, it crashes after a second. It still says "i'm blinking" but then immediately crashes.

Thanks!

I'm blinking! (Press CTRL + C to stop)
Socket: Error occurred,  { [Error: connect ECONNREFUSED /var/run/tessel/port_a]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/var/run/tessel/port_a' }
Socket: Error occurred,  { [Error: connect ECONNREFUSED /var/run/tessel/port_b]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/var/run/tessel/port_b' }
/usr/lib/node/tessel-export.js:218
      throw new Error('Socket: The Port socket has closed.');
      ^

Error: Socket: The Port socket has closed.
    at Socket.<anonymous> (/usr/lib/node/tessel-export.js:218:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)

**Comment by Frijol** [comment]
oh no! If you run `t2 list`, does your T2 show up?

**Comment by Frijol** [comment]
and, assuming yes, can you please run `t2 version` and `node v` and paste the output?

**Comment by patrickkeenan** [comment]
It shows up, but only on LAN now:
INFO Searching for nearby Tessels...
 	LAN	pk

--- FROM t2 version ---
INFO Looking for your Tessel...
INFO Connected to pk.
INFO Tessel [pk] CLI version: 0.0.27
INFO Tessel [pk] Firmware version: 0.0.14
INFO Tessel [pk] Node version: 4.4.3

--- from node -v ---
v4.4.5

**Comment by Frijol** [comment]
Appears to be the same issue as https://forums.tessel.io/t/econnrefused-var-run-tessel-port-a/2321, which never got fully resolved – but if you unplug & plug it in again, it should run normally

cc @johnnyman727 @rwaldron

**Comment by patrickkeenan** [comment]
yeah that actually worked, thanks

**Comment by rwaldron** [comment]
This will happen if a previous execution left a port open and new execution attempts to use that port. Either way, it's not a t2-cli bug, so closing.
