### ISSUE TITLE
Unused dependencies coveralls and grunt-contrib-watch

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#861]
According to [Depcheck](https://www.npmjs.com/package/depcheck) the NPM packages `coveralls` and `grunt-contrib-watch` are specified in our package.json but never called.

They are both in the Dev Dependencies section.

Ok to remove these?

**Comment by rwaldron** [comment]
I added coveralls in an effort to start doing code coverage checking, but never finished.
