### ISSUE TITLE
Switch Travis & Appveyor to only test on PR.

### ISSUE THREAD

**Issue by tcr** [tessel/t2-cli#866]
Testing on push as well takes 2x the time.

**Comment by rwaldron** [comment]
I'd rather not eliminate testing of any sort. The test execution duration isn't a blocker :P

**Comment by tcr** [comment]
This is referring to testing a PR as well as a "push", which is running the same test twice. Is there any circumstance we'd want to test a branch push that isn't in a PR? We can also use whitelists or blacklists to run on specific branch punches (like just testing master pushes).

**Comment by tcr** [comment]
One reason to do this is because we would encourage *more* testing, inevitably, by being able to list more Node versions in the Travis and Appveyor builds. Different payoffs.

**Comment by rwaldron** [comment]
> This is referring to testing a PR as well as a "push",

If you eliminate "run on push", then pushing to development branches, or master, or whatever will also be shut off.

**Comment by tcr** [comment]
K, confirming that's the intended goal. The converse—disabling tests on PRs—would be my next suggestion, but that doesn't work for third party pull requests. :( Guess that is a non-starter!
