### ISSUE TITLE
t2 ap

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#87]
Current status: no such command

Spec: [T2 CLI spec](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743)
**tessel ap [-n <ssid>] [-p <pass>] [-s <security>] [on | off]**

Creates a wireless access point.
```sh
$ tessel ap
> Usage: tessel ap [-n <ssid>] [-p <pass>] [-s <security>] [on | off]
>  -n <ssid>:      name of the network
>  -p <pass>:      password to access network
>  -s <security>:  encryption to use on network (i.e. WEP, WPA, PSK)
>  on:             bring up an access point that’s turned off
>  off:            turn off the access point
$

$ tessel ap -n test-network
> Created access point “test-network”
$ 

$ tessel ap off
> Turned off access point “test-network”
$ 

$ tessel ap -n test-network -p secret
> Created password protected access point “test-network”
$ 

$ tessel ap -n test-network -p secret -s WPA
> Created password protected access point “test-network” secured with WPA
$ 

$ tessel ap off
> Turned off access point “test-network”
$ tessel ap on
> Turned on access point “test-network”
$ 
```

**Comment by Frijol** [comment]
What is an entry point for this issue/relevant docs? @kevinmehall probably

**Comment by kevinmehall** [comment]
Things to look at are http://wiki.openwrt.org/doc/uci/wireless + the existing code for `t2 wifi`. It will need to add a second `wifi-iface` and configure it.

**Comment by Frijol** [comment]
Thanks!

**Comment by HipsterBrown** [comment]
I was looking into doing this before seeing this issue. Looks pretty straightforward. I know the default settings are available here: https://github.com/tessel/openwrt-tessel/blob/6a4021b1ff100d9bdd2200d7d14f4cea5c86312f/files/etc/config/wireless

@kevinmehall Are there two `wifi-devices`? Or a different `mode` we can set to support a `station` and `ap`?

**Comment by johnnyman727** [comment]
:clap: go get 'em @HipsterBrown!

**Comment by johnnyman727** [comment]
And to answer your other question, we can set up multiple `wifi-devices`.

**Comment by HipsterBrown** [comment]
@johnnyman727 I'm a bit stumped about setting up another `wifi-device` and `wifi-iface` after looking through [this doc](http://wiki.openwrt.org/doc/uci/wireless#wifi_networks) and [this setup page](http://wiki.openwrt.org/zh-cn/meta/playground?s[]=radio0).

According to the former link:

> `mac80211` STA mode supported on trunk. STA and AP at the same time is not yet supported(r22989).

Which has me wondering if we can change the `mode` of the `radio0` `wifi-device` OR can we register another `wifi-device` called `radio1` to setup as an access point? Maybe I need to just try some stuff out and see what works.

**Comment by kevinmehall** [comment]
You can create multiple `wifi-iface`s on the same `wifi-device`, but you can't create a new `wifi-device`, because that represents a hardware PHY.

That doc is outdated -- the commit referenced is from 2010. I've done it on T2 just by adding another `wifi-iface` block and putting it in the right firewall zone. The only limitation is that all the networks joined or created have to be on the same channel.

**Comment by HipsterBrown** [comment]
> putting it in the right firewall zone

Could you clarify this a bit more? Is this something set in the `wifi-iface` or the `wifi-device` config?

If a password is given but no `security` option, what should we set as the default security?
