### ISSUE TITLE
`tessel status` spec

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#9]
Do we have a format planned for all of the information this is supposed to provide, or any -tags to make this interaction cleaner?

(Moved here from https://github.com/tessel/v2-cli/pull/5)

**Comment by johnnyman727** [comment]
Here are some items I thought might be of interest to someone running this command:
* Is tessel `running` or `pushing` a script?
* How long has the script been running
* How much memory is currently being used?
* Is Tessel connected to WiFi and what's its signal strength and speed?
* Which Tessel is connected and over what medium (USB or WiFi)

**Comment by Frijol** [comment]
designing here https://gist.github.com/Frijol/f9171471b32440de77a4 see a couple of questions in the connection section

**Comment by johnnyman727** [comment]
This is superseded by #60.
