### ISSUE TITLE
Select which Tessel to use

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#93]
From comments on the [T2 CLI spec](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743).
The CLI should select a tessel based on this list in order of priority:

1. [x] using the --name flag
1. [x] an environment variable in the terminal, set as `export TESSEL=Bulbasaur`
* [x] if there is a single tessel connected over USB, prefer that one
* [x] if there is only one tessel visible, use that one

Meta:
* [x] document this selection process

**Comment by Frijol** [comment]
@kevinmehall @nplus11 @ekolker

**Comment by nplus11** [comment]
The config file is under debate here: https://github.com/tessel/t2-cli/issues/94

**Comment by johnnyman727** [comment]
[Cross posting from #93]

I still think this is a bad idea. Folks would have to look up how to select a particular Tessel anyway so showing them how to set an environment variable is just as much effort (but more useful down the road).

I have rarely seen people want to set a project to a specific Tessel. This could cause confusion if they ever try to do a demo with a different Tessel than they built the project with.

In addition, project configuration files already exist (like package.json) and adding another file is more of a headache.

**Comment by nplus11** [comment]
I agree. I think we need a clear picture of env vars rather than project mapped tessels

**Comment by johnnyman727** [comment]
Any more opinions on this or should I close it? @Frijol

**Comment by Frijol** [comment]
I think the listing in the top comment is correct– unless there was a decision re config files that changes that?

Is the listed order implemented in code?

**Comment by johnnyman727** [comment]
I feel strongly that there should be no config file option for the reasons listed in my comment from May 5.

**Comment by johnnyman727** [comment]
@Frijol if there are no other opinions on this, I think we should remove the config file option. Sound good?

**Comment by Frijol** [comment]
Sure, removing now.

**Comment by johnnyman727** [comment]
Partially fixed with #151. We just need to implement the selection mechanism if you have multiple USB or LAN Tessels.
