### ISSUE TITLE
init should automatically make config file selecting a tessel

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#94]
Per discussion on the [T2 CLI spec](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743)

Dependent on https://github.com/tessel/t2-cli/issues/93

**Comment by johnnyman727** [comment]
I still think this is a bad idea. Folks would have to look up how to select a particular Tessel anyway so showing them how to set an environment variable is just as much effort (but more useful down the road). I have rarely seen people want to set a project to a specific Tessel

**Comment by nplus11** [comment]
I agree. I think we need a clear picture of env vars rather than project mapped tessels

**Comment by Frijol** [comment]
@johnnyman727 your comments belong on https://github.com/tessel/t2-cli/issues/93

**Comment by johnnyman727** [comment]
Closing this based on removal in #93.
