### ISSUE TITLE
tessel status

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#95]
Current status: no such command

Spec: [T2 CLI spec](https://forums.tessel.io/t/t2-cli-spec-comments-requested/1743)
**tessel status**

Prints name of the tessel and information about connection and running scripts

```sh
$ tessel status --help
> Prints name of the tessel and information about connection and running scripts
$ 

$ tessel status
> Name:	Bulbasaur
> IP:		192.168.2.5
> Script:	index.js in RAM (16MB) started 03/31/2015 18:10:28
$ 


$ tessel status
> Name:	Rafael
> IP:		192.168.4.2
> USB: 	/dev/tty.usbmodem1422
> Script:	no script running
$ 
```

**Comment by nplus11** [comment]
All references to `Ident` should disappear. It was old. Again the doc had this updated.

**Comment by Frijol** [comment]
Fixed

**Comment by nodebotanist** [comment]
Noted via Slack with @johnnyman727 : I guess the helpful thing is that we always deploy to the same place so if the script was executed with `t2 run` it will be in `/tmp/remote-script` on T2 and if it was executed with `t2 push` it will be in `/app`

**Comment by johnnyman727** [comment]
@nodebotanist are you still working on this task? Just trying to get an idea of what's available for new contributors.

**Comment by nodebotanist** [comment]
Yup, still chipping away. Will push up later this week.



—Kas

Kassandra Perch
nodebotani.st

**Comment by nodebotanist** [comment]
Wait, sorry, I am not. Thought this was something else. /cc @johnnyman727

**Comment by johnnyman727** [comment]
Ah okay, no worries. Which issue are you working towards? I want to make sure it's marked that way so nobody else jumps on it.

**Comment by nodebotanist** [comment]
Working on https://github.com/tessel/t2-firmware/issues/24

**Comment by Frijol** [comment]
This is essentially an abbreviated combination of the `t2 wifi` printout:

```sh
➜  ~  t2 wifi
INFO Looking for your Tessel...
INFO Connected to Frank over USB
INFO Connected to "technicallyHome"
INFO IP Address: 192.168.8.144
INFO Signal Strength: (47/70)
INFO Bitrate: 30mbps
```

and `t2 logs` https://github.com/tessel/t2-cli/issues/88

**Comment by johnnyman727** [comment]
@Frijol since this is already covered by the two other commands, why don't we close this unless we see some relevant demand?

**Comment by Frijol** [comment]
Fine with that
