### ISSUE TITLE
t2 key

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#99]
We'd like a way to create an SSH key and without having to transfer it to a USB-connected device like `tessel provision` does. This is immediately useful for creating a simple and functional VM story but will ultimately be useful for managing the lifecycle of the key. 

It will tie into most of the functionality already created by #64.

```
$ t2 key generate
> Creating public and private keys for Tessel authentication...
> Private key written.
> Public key written.

$ t2 key generate
> Key already exists. Run `key delete` to delete it first before creating a new key.

$ t2 key display-public
> Displaying public key...
> <dd dd dd..... >

$ t2 key delete
> Deleting key...
> Key deleted.
```

- [x] key generate
- [ ] key display-public
- [ ] key remove

**Comment by tcr** [comment]
`delete` instead of `remove` (so that `add` and `remove` have pairity, for specifying named things, versus `generate` and `delete` which refer to one thing)

Also `display` is ambiguous, does that just mean the public key? (I imagine) Then we might make that `t2 key display-public` or something similar.

**Comment by johnnyman727** [comment]
+1 to `delete`

I changed `display` to `display-public` to make it more clear.

**Comment by johnnyman727** [comment]
`generate` added with #100.

**Comment by kevinmehall** [comment]
Why would you want to `delete` (`tessel lock-me-out-of-all-my-tessels`), and do we care to support that vs just tell someone to  `rm -rf ~/.tessel`?

**Comment by johnnyman727** [comment]
I don't really have an issue with having a `delete` command (it should at least prompt you to make sure you know what you're doing) but I also don't really see the use case besides building tests for the CLI.

**Comment by johnnyman727** [comment]
I'm going to go ahead and close this issue for now because I haven't heard a single person request it.
