### ISSUE TITLE
Pre-compiled module is missing: usb@1.2.0.

### ISSUE THREAD

**Issue by ctlss67** [tessel/t2-cli#997]
WARN This warning might be caused by one of the following:
WARN
WARN 1. A pre-compiled binary has not yet been built for this module.
WARN 2. The binary didn't compile correctly for the platform that you're developing on.
WARN    Binaries that are Linux-only or even OpenWRT-specific may cause this issue.
WARN    Try to npm install --force the affected module, then rerun your deployment command.
WARN 3. The binary may be platform specific and impossible to compile for OpenWRT.

**Comment by johnnyman727** [comment]
Thanks for reporting this @ctlss67. This is a repro of https://github.com/tessel/t2-compiler/issues/37. The module you're trying to use should be available once that issue is resolved.

**Comment by tcr** [comment]
@johnnyman727 We may want to change the t2-cli warning to post issues to t2-compiler instead? That way users can have better luck searching if the issue exists already.

**Comment by Frijol** [comment]
@tcr if so make sure to change the docs in "languages.md"

**Comment by rwaldron** [comment]
> change the t2-cli warning to post issues to t2-compiler instead? 

It's not clear that t2-compiler is more appropriate. It's not the compiler's problem if some precompiled module is not present—it's the cli's problem, because it's the user-facing application. If the cli cannot deploy something—because that thing is not present—then it's the cli's problem to resolve. If something won't compile correctly, then it's the problem of the compiler. Basically: I can see your reasoning, but I don't agree with it.

**Comment by tcr** [comment]
@rwaldron That's fine by me. In that case, to aid searching, I think it would be desirable to then leave open close cross-compile issues in this repo then until they're resolved.

**Comment by rwaldron** [comment]
That's been my practice (ie. it gets closed when I actually upload the tgz to the remote host), so I'm definitely 👍

**Comment by tcr** [comment]
@ctlss67 node-usb is now published. Make sure you run `t2 update` before testing the node-usb module, or you may have a linker error looking for `*udev.so`.

Example code run on Tessel using my [node-lsusb](http://github.com/tcr/node-lsusb) crate:

```
➜  node-lsusb git:(master) t2 run index.js
INFO Looking for your Tessel...
INFO Connected to Tessel-02A34C9AB2FE.
INFO Building project.
INFO Writing project to RAM on Tessel-02A34C9AB2FE (510.976 kB)...
INFO Deployed.
INFO Running index.js...
Bus 002 Device 001: ID 1d6b:0001 Linux 3.18.17 ohci_hcd Generic Platform OHCI controller
Bus 001 Device 002: ID 1a40:0101  USB 2.0 Hub [MTT]
Bus 001 Device 001: ID 1d6b:0002 Linux 3.18.17 ehci_hcd EHCI Host Controller
```

**Comment by rwaldron** [comment]
AWESOME!
